-- CAMS 144건 DELETE + RAMP 추가 INSERT
-- DELETE: 145건 / INSERT: 79건
BEGIN;

-- 1) CAMS 144건 DELETE
DELETE FROM quality.tb_word
WHERE comm_stnd_yn='N' AND cret_user_id='space' AND cret_dt LIKE '20260519%';

-- 2) 추가 RAMP 단어 INSERT (CAMS 충돌 없으니 모두 가능)
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('0aSud-670s70i0p-2EPdZh','감독','SPRVS','SUPERVISION','監督
 어떤 사람이나 기관이 다른 사람이나 기관을 감시하고 지휘?명령하거나 제재를 가하는 일.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('QrFEExEgyk78WOc7dtyKAb','드라이브','DRVE','DRIVE','<컴퓨터>디스크를 동작하게 하여 데이터를 판독하거나 기록하는 장치
예) DVD수록네트워크드라이브명','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('BFvqxmvYr0hbqLRw7dbaqz','시트','SHEET','SHEET','서류철, 표 등의 시트','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('6PrKH8ueSXaCmptMmrzibr','액션','ACTION','ACTION','(어떤 목적이나 문제 해결을 위한) 행동, 조치  (사람의) 동작','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('JT4IuRpo7VTYPLb9uNRK0D','재생','RVL','REVIVAL','再生
 낡거나 못 쓰게 된 물건을 가공하여 다시 쓰게 함.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('AeFWFS5mpZu3fJM_7Bhr9E','커맨드','CMMND','COMMAND','<컴퓨터>컴퓨터의 시동, 정지, 계속 따위의 동작을 지시하는 명령    예) 커맨드명','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('ew3rh5obsTHIMpg2N2J7PS','CLASS','CLASS','Class in Object Oriented Programming','객체 지향 프로그램에서 속성과 기능을 포함한 단위','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('I8I4SfSHqtylkmUY5z3naj','감염','INFC','INFECTION','感染
 병원체가 몸에 옮음','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('MPxk8GoYuVTHzEHnIdsaaI','경광등','LTBR','LIGHT BAR','警光燈 긴급함을 알리기 위해 차의 위쪽에 다는 붉은빛을 발하는 등     예) 경광등IP, 경광등PORT, 경광등종류코드','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('gTLhupPGZ6KIsBiKfySWwb','계열','SERS','SERIES','서로 관련이 있거나 유사한 점에서 한 갈래로 이어지는 계통이나 조직.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('hKTfxe7rvMVSv4VaZAy1nd','광디스크','OPDS','OPTICAL DISC','레이저 광을 이용하여 문서, 음성, 화상정보 등을 기록·재생하는 원반 모양의 기록매체의 총칭','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('-pOaX0XhrzAopcaJnedgZ5','구술','ORST','ORAL STATEMENT','口述 입으로 말함','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('TUzqkSdvGv8Tdi8Vn9SX5F','기록물건','RITM','RECORDS ITEM','더 이상 나눌 수 없는 기록물의 최소단위. 하나의 기록물건에는 다양한 유형의 첨부물이 존재할 수 있다.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('T5TFlcWe4f11sgLduUdZYo','납본','POSC','PRESENTATION OF A SPECIMEN COPY','納本
 새로 발간한 출판물을 본보기로 해당 기관에 제출함','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('OaIwFcBoEddfPVnJ1k2Smk','네트워크','NTWK','NETWORK','랜(LAN)이나 모뎀 따위의 통신 설비를 갖춘 컴퓨터를 이용하여 서로 연결시켜 주는 조직이나 체계.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('2N0pcYLGuvmJyYltjCi6zI','녹음','REC','RECORDING','錄音
 소리를 재생할 수 있도록 기계로 기록하는 일. 원판을 쓰는 기계적 녹음, 필름을 쓰는 광학적 녹음, 테이프를 쓰는 자기적 녹음 등이 있음','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('gLV4B_ft_diNCP5J6JNcew','대통령','PRSD','PRESIDENT','大統領
 외국에 대하여 국가를 대표하는 국가의 원수.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('UQaQp7XQdFHGGr-ovv7LdB','데몬','DMON','DEMON','유닉스 등에서 백그라운드에서 프로세스 상태로 있다가 접근요청이 있을 때 이를 처리해 주는 일종의 서버 프로세스.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('qplSoJesbJJh5lcawJLlHW','두께','THCK','THICKNESS','물건의 두꺼운 정도.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('7j_EVz3pokpemKLP5rgOZJ','디지털화','DGTZ','DIGITIZATION','스캐닝 또는 인코딩 장비를 이용하여 비전자기록물을 디지털 형태로 변환하는 과정

비고 디지털화의 사례로는 스캐닝 또는 이미징 작업을 통해 원본 기록물을 디지털 사진 형태로 촬영하는 것, 또는 아날로그 음성 또는 영상 기록을 디지털 매체로 변환하는 것 등이 있다.
   ?스캐닝 : 비전자 기록물을 이미지(화상) 형태로 컴퓨터에 입력하여 디지털화하는 것
   ?인코딩 : 비전자 음성 및 영상 등 동영상 기록물을 컴퓨터로 입력하여 디지털화하는 것
[KS X ISO 13028 디지털화 이행지침 참조하여 개작]','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('FwYD1qrdc9IxAR6uZhLrhp','띄어쓰기','WDSP','WORD SPACING','글을 쓸 때, 각 낱말을 띄어 쓰는 일.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('I-avk7rqHfMaUiJTfuwlvq','마이그레이션','MGR','MIGRATION','기록의 진본성, 무결성, 신뢰성, 이용가능성을 유지하면서 한 시스템에서 다른 시스템으로 기록을 이전하는 행위

비고 일반적으로 기술적인 변화에 따라 전자기록물의 하드웨어 및 소프트웨어 구성을 다른 하드웨어 및 소프트웨어로 이전하는 체계적인 행위로 볼 수 있다.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('25AkmJIDZ-gJpHg-1OWv8_','메타','META','META','근원적인 정의 또는 설명.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('P6oVnii-S4HyoFOQ6JU5vD','무단','WOPM','WITHOUT PERMISSION','無斷
 사전에 허락이 없음.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('hOecahWA6DkjEfh0EXAjvA','미상','UNKN','UNKNOWN','미ː상(迷想)[명사]어지럽게 헷갈린 생각. 갈피를 잡지 못하는 생각.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('WqdzdgXY6lRePOSuGhR_CV','복제','RPRD','REPRODUCE','複製
 본디의 것과 똑같이 만듦
[법률정의] (온라인디지털콘텐츠산업발전법) 온라인디지털콘텐츠를 전자적 매체 등 유형물에 고정하거나 유형물로 다시 제작하는 것.
(국립박물관유물복제규칙) 유물의 촬영?탁본?모사 및 모조를 하거나 사진자료를 이용하는 것.
(컴퓨터프로그램보호법) 프로그램을 유형물에 고정시켜 새로운 창작성을 더하지 아니하고 다시 제작하는 행위.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('AAj4nlC1K5ifXYbaumlWsb','봉투','ENVL','ENVELOPE','封套
 편지나 서류 따위를 넣기 위하여 종이 따위로 만든 주머니','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('POfj6oems3nYAdPKoPEFSb','비디오','VID','VIDEO','영상 신호를 다루는 장치나 회로','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('X0XrEwjax7HD__SLbOR62Q','비밀','SRET','SECRET','秘密
 남에게 보이거나 알려서는 안 되는 일의 내용
[법률정의] (보안업무규정) 그 내용이 누설되는 경우 국가안전보장에 유해로운 결과를 초래할 우려가 있는 국가 기밀로서 이 영에 의하여 비밀로 분류된 것.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('pXmDEkBECF69BdAjfd4gZS','사료','HSMT','HISTORICAL MATERIAL','史料
 역사 연구에 필요한 문헌이나 유물. 문서, 기록, 건축, 조각 따위를 이른다.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('ZWVFSJCgVu4si4-OPYmPHw','상자','BOX','BOX','箱子
 물건을 넣어 두기 위하여 나무, 대나무, 두꺼운 종이 같은 것으로 만든 네모난 그릇.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('3pDwZ7tPhXus-GJS2E5RM6','상정','SBMS','SUBMISSION','上程
 토의할 안건을 회의 석상에 내어 놓음.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('WNekainZ2dbmqU0ZRgU55r','색채','CLOR','COLOR','色彩
 어떤 사물이 지닌 경향이나 성질을 비유하여 이르는 말.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('kqe6K3H1-Ll3tdBWFceqLA','서고','STK','STACKS','기록물을 보존하기에 적합한 시설과 설비를 구비한 장소','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('LtHusgJiGayuHQvasNR41p','서열','ORD','Order','序列
 일정한 기준에 따라 순서대로 늘어섬. 또는 그 순서','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('_pt7qgBpO5XKVoOrhTtwZa','소장','OAK','OWN AND KEEPING','소유하여 간직함','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('PYV0CQKtrw7T5Xo6M0_t5k','소장처','HDPL','HOLDING PLACE','소장하고 있는 장소','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('X0U1js2FIJVzQXfgmw2C9g','스캐닝','SCNN','SCANNING','비전자 기록물을 이미지(화상) 형태로 컴퓨터에 입력하여 디지털화하는 것','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('AhibFWUgbMTeYeDa1HdUMp','스캔','SCAN','SCAN','그림?사진 따위를 이전 부호로 변환하여 하나의 파일로 저장하는 일','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('4xGkL6IGXX1szUrC3H3_7q','시대','ERA','ERA','역사적으로 어떤 표준에 의하여 구분한 일정한 기간.  지금 있는 그 시기. 또는 문제가 되고 있는 그 시기.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('qhEV1FZLfnb4LwZU4rdBA5','시소러스','THE','THESAURUS','키워드들 간의 계층관계와 동의어, 관련어 등을 설정하고 구조화한 어휘집','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('VnBXYNib4Z4LmHqdDn1U69','시점','PNTM','POINT TIME','時點
 시간의 흐름 가운데 어느 한 순간.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('Y4Jp_7ZMM-K5zxAaeVZUGY','시청각','AUDV','AUDIOVISUAL','시ː청?각(視聽覺)[명사] ‘시각’과 ‘청각’을 아울러 이르는 말.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('E6oZGLxcqNLCCK1tMqATDd','앨범','ALBM','ALBUM','사진첩. 사진을 붙여 두기 위한, 두꺼운 종이로 만든 책.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('-rfSkovgtIxmS3plKbIyPn','양화','PSTV','POSITIVE','陽畵. 촬영을 한 음화 필름을 현상하여 인화한 필름을 통틀어 이르는 말','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('CdgN_1Mq2UHw56U2OZpe4O','역사','NHIS','NATIONAL HISTORY','인류 사회의 변천과 흥망의 과정 또는 그 기록','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('TdpXLrjxvD1E7iDaM00m08','영구','PRMN','PERMANENCE','永久
 어떤 상태가 시간상으로 무한히 이어짐.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('z8NDw-gMsrDftKnFA90WkN','오디오','AUD','AUDIO','음성 매체','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('I_5TiDJZEDEI3rvFRVxVVt','용기','CTNR','CONTAINER','容器
 물건을 담는 그릇
[법률정의] (고압가스 안전관리법) 고압가스를 충전하기 위한 것(부속품을 포함한다)으로서 이동할 수 있는 것.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('qtKR_3jYb9RjJ8Yy20WsPF','워터마크','WM','WATER MARK','워터마크','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('EuP55O2SIRUYbrrYfOMh0u','원어','SRLN','SOURCE LANGUAGE','원어(原語)[명사]번역하거나 고치거나 한 말의 본디의 말. 원말. 밑말. ↔역어(譯語).','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('j79-YxlhN4Zb1DYmeZphFc','유지','KP','KEEPING','계속하여 지속함','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('v6izZcs-4B4pHOHfegyP4P','유출','EFFL','EFFLUX','流出
 귀중한 물품이나 정보 따위가 불법적으로 나라나 조직의 밖으로 나가 버림.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('H8xRKwgfvUJYbmWtTAIdoE','육안','NKE','NAKED EYE','안경이나 망원경, 현미경 따위를 이용하지 아니하고 직접 보는 눈.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('71_v8HALaQMamg5Efti9wV','음향','SOND','SOUND','音響
 소리의 울림. 울리어 귀로 느끼게 되는 소리.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('2vje2VCoS8Yy-G4cnfGgyJ','음화','NGTV','NEGATIVE','陰?. 사진의 건판(乾板)에 감광시켜 현상한 모양.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('RkYImhKUsLHvJNg7rur1bq','잉크','INK','INK','글씨를 쓰거나 인쇄하는 데 쓰는, 빛깔 있는 액체     예) 잉크상태설명','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('S-oK1FtYiAaqks5Tvgz_ZB','작곡자','CPSR','COMPOSER','작곡?자(作曲者)[?꼭짜][명사]작곡한 사람.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('VmRrbV42ZcsHCqELFXc58a','작사자','LYWR','LYRIC WRITER','作詞者 노랫말을 지은 사람 예) 작사자명','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('3lDzGdYR3kZKOU4YAkxIdV','정정','CRRC','CORRECTION','訂正
 글자나 글 따위의 잘못을 고쳐서 바로잡음.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('yfWXWA81BAuoKPWrKX1nch','준영구','SMPM','SEMI-PERMANENT','기록물 보존기간 준영구','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('1W4HBYiEpNEt1SkgVZm0bT','준칙','RGLT','REGULATION','準則 준거할 기준이 되는 규칙이나 법칙.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('EzICmZUn5cn8IGjBfHvKhs','총독부','GVGN','GOVERNMENT GENERAL','식민지를 다스리기 위하여 설치하는 최고 행정 기관. 총독이 이곳에서 정무를 맡아본다.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('ckWjf3dmPWC7Wu0D3nS8pl','추적','CHS','CHASE','추적','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('exqmNWCAo83F4Kk89IrOhC','컴포넌트','CMP','COMPONENT','기록물건을 구성하는 기록물의 최소단위. 일반문서 유형인 경우 종이문서, 전자문서의 본문, 첨부 데이터파일 등이 기록물건을 구성하는 컴포넌트가 되고, 다른 기록 유형인 경우 각 기록물건을 구성하는 고유의 컴포넌트 형식을 가진다.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('bIEVeByMXOqPwG7ecLgcTs','컷','CUT','CUT','촬영시의 컷.  예)M/F촬영세부내역 - 시작컷, 종료컷','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('xDoq_F094MoH1TCjo_soES','코너','CRNR','CORNER','백화점 따위의 큰 상가에서 특정한 상품을 진열하고 팔기 위한 곳.   예) 코너구분코드','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('qkZzGLndabIYsYM_KTsBJK','콜렉션','CLLC','COLLECTION','관련된 물건들이나 상품들의 집합.     예) 콜렉션명','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('3Bx62FygoMpzbGldVnF4t4','클립','CLIP','CLIP','탄력이나 나선(螺旋)을 이용하여 종이나 서장(書狀) 같은 것을 끼워 두는 기구 예) 클립ID','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('IqNsFoXDkIcwVOC_eTKcac','타임스탬프','TSTMP','Timestamp','IT : A variable containing the date and time at which an event occurred, often included in a log to track the sequence of events','Y','값','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('pA24gUtpFyxCUQ0dEMHxWl','통권','CNOV','CONSECUTIVE NUMBER OF VOLUMES','通卷 잡지나 책 따위의 전체에 걸친 권수.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('I7TGoCopdeA1CjmJkqZavf','파싱','PARS','PARSING','문장을 문법적으로 분석함. 문장 구문 분석.   예) 생산현황관리 - 생산현황접수(RG) - XML파싱의뢰검사키','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('JG6OvbbUQpKmXzUBKC2NIM','판단','JGT','JUDGMENT','判斷
사물을 인식하여 논리나 기준 등에 따라 판정을 내림','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('R68PA1_wk1TzMNUWWe7tCO','판본','BLBK','BLOCK BOOK','版本 목판으로 인쇄한 책 =판각본(板刻本)   예) 판본구분코드','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('vfkyK5NbYBpmeXx0saAV-A','편철','FLN','FILING','동일한 성격을 가진 기능과 주제별로 기록물을 분류하여 기록물철로 모으는 행위 

비고 이를 통해 기록을 체계적으로 보관하고, 필요로 할 때 신속하게 검색·활용하고 적시에 적절하게 처분조치를 할 수 있도록 한다.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('1cbh8FhpWKc2RkQ7pMjcC3','필름','FILM','FILM','투명 물질인 셀룰로이드나 폴리에스테르 따위에 감광제를 칠한 물건.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('kO2qURgFJY38X9jkqXbM5l','합사','ESTG','ENSHRINING TOGETHER','合祀 둘 이상의 혼령을 한곳에 모아 제사를 지냄','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('b3Mv2-JFYANS4dd2z8GiUV','해쉬','HASH','HASH','<컴퓨터>특정 데이터를 그 길이에 관계없이 고정된 길이의 값으로 변환한 값     예) 해쉬알고리즘명, 해쉬값','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');
INSERT INTO quality.tb_word (word_id,word_nm,word_eng_abrv_nm,word_eng_nm,word_desc,word_clsf_yn,domain_clsf_nm,comm_stnd_yn,aprv_yn,cret_dt,cret_user_id,use_yn) VALUES ('rVWQYzqxx657jEJu8GTyCK','헤더','HDR','HEADER','컴퓨터에서 출력될 때 각 페이지 맨 윗부분에 자동으로 붙는 부분.','N','','N','Y',to_char(now(),'YYYYMMDDHH24MISS'),'admin','Y');

-- 검증
SELECT 'tb_word Y' as t, count(*) FROM quality.tb_word WHERE comm_stnd_yn='Y';
SELECT 'tb_word N' as t, count(*) FROM quality.tb_word WHERE comm_stnd_yn='N';
SELECT 'CAMS 남은 (space)' as t, count(*) FROM quality.tb_word WHERE cret_user_id='space';

COMMIT;