-- ============================================================
-- Oracle 용 DDL — TESTUSER 스키마에 진단 대상 3개 테이블 생성
-- 적용: SYSTEM 으로 sqlplus 실행 (TESTUSER 권한으로 적용 가능)
-- ============================================================

-- 기존 테이블 안전 DROP (Oracle 은 IF EXISTS 미지원)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TESTUSER.TB_TEST_MEMBER  PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TESTUSER.TB_TEST_ORDER   PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TESTUSER.TB_TEST_PRODUCT PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- TB_TEST_MEMBER
CREATE TABLE TESTUSER.TB_TEST_MEMBER (
    MEMBER_ID    VARCHAR2(20)   NOT NULL,
    EMAIL        VARCHAR2(100),
    PHONE        VARCHAR2(20),
    NAME         VARCHAR2(50),
    AGE          NUMBER(5),
    GENDER       VARCHAR2(2),
    REG_DT       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDT_DT      TIMESTAMP,
    CONSTRAINT PK_TB_TEST_MEMBER PRIMARY KEY (MEMBER_ID)
);
COMMENT ON TABLE TESTUSER.TB_TEST_MEMBER IS '품질진단 테스트용 회원';

-- TB_TEST_ORDER
CREATE TABLE TESTUSER.TB_TEST_ORDER (
    ORDER_ID     VARCHAR2(20)   NOT NULL,
    MEMBER_ID    VARCHAR2(20),
    AMOUNT       NUMBER(15,2),
    STATUS       VARCHAR2(10),
    START_DT     DATE,
    END_DT       DATE,
    REG_DT       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDT_DT      TIMESTAMP,
    CONSTRAINT PK_TB_TEST_ORDER PRIMARY KEY (ORDER_ID)
);
COMMENT ON TABLE TESTUSER.TB_TEST_ORDER IS '품질진단 테스트용 주문';

-- TB_TEST_PRODUCT  (PK 미정의 — UNIQUE 룰 검증용)
CREATE TABLE TESTUSER.TB_TEST_PRODUCT (
    PRODUCT_CODE VARCHAR2(20),
    NAME         VARCHAR2(100),
    PRICE        NUMBER(15,2),
    CATEGORY     VARCHAR2(20),
    REG_DT       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDT_DT      TIMESTAMP
);
COMMENT ON TABLE TESTUSER.TB_TEST_PRODUCT IS '품질진단 테스트용 상품 (PK 미정의 — UNIQUE/LENGTH 검증용)';

-- TESTUSER 가 본 테이블에 SELECT/DML 권한 (테이블 owner 는 이미 TESTUSER 라 자동)

EXIT;
