-- 85번 — TB_DATA_MODEL_ATTR 에 FK 부모 컬럼 추가 (XMI 2.1 관계 매핑용, idempotent)
SET search_path TO quality;

ALTER TABLE TB_DATA_MODEL_ATTR ADD COLUMN IF NOT EXISTS FK_PARENT_OBJ_NM  VARCHAR(255);
ALTER TABLE TB_DATA_MODEL_ATTR ADD COLUMN IF NOT EXISTS FK_PARENT_ATTR_NM VARCHAR(255);

COMMENT ON COLUMN TB_DATA_MODEL_ATTR.FK_PARENT_OBJ_NM  IS '85번 — FK 일 때 참조 부모 테이블 (XMI 2.1 type id 참조 해석)';
COMMENT ON COLUMN TB_DATA_MODEL_ATTR.FK_PARENT_ATTR_NM IS '85번 — FK 일 때 참조 부모 컬럼 (없으면 부모 PK 추정)';
