-- 83번 Step 5 — TB_QUAL_DIAG_HISTORY 진행률 컬럼 추가 (idempotent)
SET search_path TO quality;

ALTER TABLE TB_QUAL_DIAG_HISTORY ADD COLUMN IF NOT EXISTS PROGRESS_DONE  INTEGER DEFAULT 0;
ALTER TABLE TB_QUAL_DIAG_HISTORY ADD COLUMN IF NOT EXISTS PROGRESS_TOTAL INTEGER DEFAULT 0;

COMMENT ON COLUMN TB_QUAL_DIAG_HISTORY.PROGRESS_DONE  IS '83번 Step5 — 처리 완료 컬럼 수 (실시간 갱신)';
COMMENT ON COLUMN TB_QUAL_DIAG_HISTORY.PROGRESS_TOTAL IS '83번 Step5 — 진단 대상 총 컬럼 수';
