server.port = 28098
#spring.main.web-application-type=reactive

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# encryptor
jasypt.encryptor.bean=jasyptStringEncryptor

spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=false

# jpa / hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.mapping-resources=META-INF/dm-collect.xml

#postgresql
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.hikari.jdbc-url=jdbc:postgresql://127.0.0.1:25433/postgres?currentSchema=quality
spring.datasource.hikari.username=admin
spring.datasource.hikari.password=ENC(H1B4ZhIn8Jx2sC7VOwVrNZc5bBRuV9OHY58U60297dEbIInIrQAoxw==)
spring.datasource.hikari.auto-commit=false

#using simple message broker of q-center
stomp.broker.simple = true
#using wss://localhost:28091 if manager doesn't open both of https and http port
stomp.broker.url = ws://localhost:28091
#stomp.broker.ssl-key-store = ${ND_HOME}/logger/naraedata.p12
stomp.broker.ssl-key-store = c:/temp/logs/naraedata.p12
stomp.broker.ssl-key-store-password = ENC(XbMYUOy1SDM0clfuiCFWT8kTXHD3bBP7Pl6GvfWK7WpFVZrVbvStxg==)
stomp.broker.ssl-keyStoreType = PKCS12

# LogBack config
logging.level.org.springframework.messaging=debug
spring.profiles.active=dev
logging.config=classpath:logging-config-${spring.profiles.active}.xml
log.level=DEBUG
log.path=/home/nd_suite/q-executor/logs
#log.path=c:/temp/logs
log.file.name=q-executor
