server.port = 28090
#spring.main.web-application-type=reactive
#additional http port for websocket
server.http.port=28091
# session timeout
server.servlet.session.timeout=120m

# encrytor
jasypt.encryptor.bean=jasyptStringEncryptor

spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=false
spring.main.allow-bean-definition-overriding=true
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

#postgresql
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.hikari.jdbc-url=jdbc:postgresql://127.0.0.1:25433/postgres?currentSchema=quality
spring.datasource.hikari.username=admin
spring.datasource.hikari.password=admin!123
spring.datasource.hikari.auto-commit=false

#stomp.broker
stomp.broker.mode = dev
#using simple message broker of manager
stomp.broker.simple = true

# LogBack config
logging.level.org.springframework.messaging=debug
spring.profiles.active=prod
logging.config=classpath:logging-config-${spring.profiles.active}.xml
log.level=INFO
#log.path=/home/nd_suite/q-center/logs
log.path=c:/temp/logs
log.file.name=q-center

#mybatis
logging.level.org.apache.ibatis=DEBUG
logging.level.java.sql=DEBUG

#springdoc
#springdoc.default-consumes-media-type=application/json
#springdoc.default-produces-media-type=application/json
springdoc.api-docs.groups.enabled=true
#alpha or method
springdoc.swagger-ui.operations-sorter=alpha
#springdoc.swagger-ui.tags-sorter=alpha
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.swagger-ui.disable-swagger-default-url=true
#springdoc.swagger-ui.display-query-params-without-oauth2=true
springdoc.swagger-ui.doc-expansion=none
#springdoc.paths-to-match=/api/**
