-- =============================================================
-- Claude가 제공한 DDL 모음 (PostgreSQL)
-- 프로젝트: ndata-quality
-- 정리일: 2026-03-23
-- =============================================================

-- -------------------------------------------------------------
-- 1. TB_DATA_MODEL_SCHEMA
--    데이터모델별 수집 대상 스키마 관리
--    (세션: 278cae7d / 데이터모델 수집 스키마 기능 추가 시)
-- -------------------------------------------------------------
CREATE TABLE TB_DATA_MODEL_SCHEMA (
    DM_ID         VARCHAR(36)  NOT NULL,
    SCHEMA_NM     VARCHAR(100) NOT NULL,
    USE_YN        CHAR(1)      NOT NULL DEFAULT 'Y',
    CRET_DT       VARCHAR(14),
    CRET_USER_ID  VARCHAR(50),
    PRIMARY KEY (DM_ID, SCHEMA_NM)
);

-- -------------------------------------------------------------
-- 2. TB_DIAG_JOB
--    표준화 진단 작업(Job) 이력
--    (세션: 3f1ffb70 / 표준화 진단 기능 구현 시)
-- -------------------------------------------------------------
CREATE TABLE TB_DIAG_JOB (
    DIAG_JOB_ID     VARCHAR(50)     NOT NULL,
    DM_CLCT_ID      VARCHAR(50)     NOT NULL,
    DM_ID           VARCHAR(50)     NOT NULL,
    STATUS          VARCHAR(20)     NOT NULL DEFAULT 'READY',
    TOTAL_CNT       INTEGER         DEFAULT 0,
    PROCESS_CNT     INTEGER         DEFAULT 0,
    RESULT_CNT      INTEGER         DEFAULT 0,
    CRET_DT         VARCHAR(14),
    CRET_USER_ID    VARCHAR(50),
    START_DT        VARCHAR(14),
    END_DT          VARCHAR(14),
    CONSTRAINT PK_TB_DIAG_JOB PRIMARY KEY (DIAG_JOB_ID)
);

-- -------------------------------------------------------------
-- 3. TB_DIAG_RESULT
--    표준화 진단 결과 상세 (1건 = 1이슈)
--    (세션: 3f1ffb70 / 표준화 진단 기능 구현 시)
-- -------------------------------------------------------------
CREATE TABLE TB_DIAG_RESULT (
    RESULT_ID       BIGSERIAL       NOT NULL,
    DIAG_JOB_ID     VARCHAR(50)     NOT NULL,
    OBJ_NM          VARCHAR(200),
    ATTR_NM         VARCHAR(200),
    ATTR_NM_KR      VARCHAR(200),
    DIAG_TYPE       VARCHAR(50)     NOT NULL,
    DIAG_DETAIL     TEXT,
    STD_VALUE       VARCHAR(500),
    ACTUAL_VALUE    VARCHAR(500),
    CONSTRAINT PK_TB_DIAG_RESULT PRIMARY KEY (RESULT_ID)
);

-- -------------------------------------------------------------
-- 4. TB_WORD_DICT
--    미등록 단어 영문약어 추천용 한영 매핑 사전
--    TB_WORD에 없는 단어가 분석될 때 영문약어/영문명 추천에 사용
--    (세션: 3f1ffb70 / 표준화 추천 - 미등록 단어 추천 기능)
-- -------------------------------------------------------------
CREATE TABLE TB_WORD_DICT (
    WORD_KOR        VARCHAR(100)    NOT NULL,
    WORD_ENG        VARCHAR(200),
    WORD_ABRV       VARCHAR(50),
    DOMAIN_CLSF_NM  VARCHAR(100),
    CONSTRAINT PK_TB_WORD_DICT PRIMARY KEY (WORD_KOR)
);

COMMENT ON TABLE  TB_WORD_DICT IS '미등록 단어 영문 추천 사전';
COMMENT ON COLUMN TB_WORD_DICT.WORD_KOR       IS '한글 단어명';
COMMENT ON COLUMN TB_WORD_DICT.WORD_ENG       IS '영문 풀네임';
COMMENT ON COLUMN TB_WORD_DICT.WORD_ABRV      IS '영문 약어';
COMMENT ON COLUMN TB_WORD_DICT.DOMAIN_CLSF_NM IS '도메인 분류명 (금액, 일자, 코드 등)';

-- -------------------------------------------------------------
-- TB_WORD_DICT 시드 데이터
-- TB_WORD(공공 표준 단어사전 3,284건)에 없는 일상/일반 단어
-- 용도: 미등록 단어 분석 시 영문약어/영문명 자동 추천
-- -------------------------------------------------------------

-- ■ 일상 사물/기기
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('핸드폰', 'Mobile Phone', 'MBLPHN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('스마트폰', 'Smart Phone', 'SMTPHN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('노트북', 'Notebook', 'NTBK', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('태블릿', 'Tablet', 'TBLT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('키보드', 'Keyboard', 'KBD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('마우스', 'Mouse', 'MOS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('프린터', 'Printer', 'PRNT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('스캐너', 'Scanner', 'SCNR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('모니터', 'Monitor', 'MNTR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('냉장고', 'Refrigerator', 'REFR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('세탁기', 'Washing Machine', 'WSMN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('에어컨', 'Air Conditioner', 'ARCD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('텔레비전', 'Television', 'TV', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('카메라', 'Camera', 'CAM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('배터리', 'Battery', 'BTRY', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('센서', 'Sensor', 'SNSR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('로봇', 'Robot', 'ROBT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('드론', 'Drone', 'DRON', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('리모컨', 'Remote Control', 'RMTC', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('충전기', 'Charger', 'CHGR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('어댑터', 'Adapter', 'ADPT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('스피커', 'Speaker', 'SPKR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('이어폰', 'Earphone', 'ERPHN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('헤드셋', 'Headset', 'HDST', '');

-- ■ 소지품/의류/잡화
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('지갑', 'Wallet', 'WLET', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('가방', 'Bag', 'BAG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('안경', 'Glasses', 'GLSS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('시계', 'Watch', 'WTCH', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('열쇠', 'Key', 'KEY', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('우산', 'Umbrella', 'UMBR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('의류', 'Clothing', 'CLTH', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('신발', 'Shoes', 'SHOE', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('모자', 'Hat', 'HAT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('장갑', 'Gloves', 'GLVS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('넥타이', 'Necktie', 'NKTI', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('화장품', 'Cosmetics', 'COSM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('악세서리', 'Accessory', 'ACSR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('보석', 'Jewelry', 'JWLR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('향수', 'Perfume', 'PRFM', '');

-- ■ 교통/이동
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('자전거', 'Bicycle', 'BCYL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('오토바이', 'Motorcycle', 'MTCY', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('트럭', 'Truck', 'TRCK', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('버스', 'Bus', 'BUS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('택시', 'Taxi', 'TAXI', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('지하철', 'Subway', 'SBWY', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('기차', 'Train', 'TRAN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('비행기', 'Airplane', 'ARPL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('선박', 'Ship', 'SHIP', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('엘리베이터', 'Elevator', 'ELVT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('에스컬레이터', 'Escalator', 'ESCL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('주차', 'Parking', 'PRKG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('톨게이트', 'Tollgate', 'TLGT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('내비게이션', 'Navigation', 'NAVI', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('킥보드', 'Kickboard', 'KCBD', '');

-- ■ 건물/장소/시설
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('아파트', 'Apartment', 'APT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('오피스텔', 'Officetel', 'OFSTL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('빌딩', 'Building', 'BLDG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('공장', 'Factory', 'FCTY', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('창고', 'Warehouse', 'WRHS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('매장', 'Store', 'STOR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('식당', 'Restaurant', 'RSTR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('카페', 'Cafe', 'CAFE', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('편의점', 'Convenience Store', 'CVST', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('마트', 'Mart', 'MART', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('백화점', 'Department Store', 'DPST', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('약국', 'Pharmacy', 'PHRM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('미용실', 'Hair Salon', 'HRSN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('세차장', 'Car Wash', 'CWSH', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('주유소', 'Gas Station', 'GSTN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('체육관', 'Gymnasium', 'GYM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('수영장', 'Swimming Pool', 'SWPL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('놀이터', 'Playground', 'PLGD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('도서관', 'Library', 'LBRY', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('영화관', 'Cinema', 'CNMA', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('호텔', 'Hotel', 'HOTL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('펜션', 'Pension', 'PNSN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('콘도', 'Condominium', 'COND', '');

-- ■ 음식/식품
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('음식', 'Food', 'FOOD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('음료', 'Beverage', 'BVRG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('과일', 'Fruit', 'FRUT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('채소', 'Vegetable', 'VGTB', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('고기', 'Meat', 'MEAT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('생선', 'Fish', 'FISH', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('빵', 'Bread', 'BRAD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('과자', 'Snack', 'SNCK', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('우유', 'Milk', 'MILK', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('커피', 'Coffee', 'COFE', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('반찬', 'Side Dish', 'SDSH', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('도시락', 'Lunch Box', 'LNBX', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('레시피', 'Recipe', 'RCPE', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('식재료', 'Ingredient', 'INGR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('조미료', 'Seasoning', 'SASN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('냉동', 'Frozen', 'FRZN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('유통기한', 'Expiration Date', 'EXPDT', '일자');

-- ■ 의료/건강
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('환자', 'Patient', 'PTNT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('의사', 'Doctor', 'DCTR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('간호사', 'Nurse', 'NURS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('약사', 'Pharmacist', 'PHMC', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('처방전', 'Prescription', 'PRSC', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('진료', 'Medical Treatment', 'MDTRT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('진단', 'Diagnosis', 'DIAG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('수술', 'Surgery', 'SRGR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('입원', 'Hospitalization', 'HSPT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('퇴원', 'Discharge', 'DSCH', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('예방접종', 'Vaccination', 'VCTN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('혈압', 'Blood Pressure', 'BLPR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('혈당', 'Blood Sugar', 'BLSG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('체온', 'Body Temperature', 'BDTP', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('체중', 'Body Weight', 'BDWT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('신장', 'Height', 'HGHT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('알레르기', 'Allergy', 'ALRG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('증상', 'Symptom', 'SMTM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('복용', 'Medication', 'MDCT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('건강검진', 'Health Checkup', 'HLCK', '');

-- ■ 교육/학교
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('학생', 'Student', 'STDT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('교사', 'Teacher', 'TCHR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('교수', 'Professor', 'PROF', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('강사', 'Instructor', 'INST', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('학교', 'School', 'SCHL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('대학교', 'University', 'UNIV', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('학원', 'Academy', 'ACDM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('강의', 'Lecture', 'LCTR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('수업', 'Class', 'CLSS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('시험', 'Exam', 'EXAM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('성적', 'Grade', 'GRD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('학점', 'Credit', 'CRDT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('졸업', 'Graduation', 'GRDT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('입학', 'Admission', 'ADMN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('장학금', 'Scholarship', 'SCHLR', '금액');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('등록금', 'Tuition', 'TUTN', '금액');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('교과서', 'Textbook', 'TXBK', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('과제', 'Assignment', 'ASGN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('출석', 'Attendance', 'ATND', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('결석', 'Absence', 'ABSN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('자격증', 'Certificate', 'CERT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('연수', 'Training', 'TRNG', '');

-- ■ 부동산/주거
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('임대', 'Lease', 'LEAS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('임차', 'Rent', 'RENT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('월세', 'Monthly Rent', 'MRENT', '금액');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('전세', 'Jeonse Deposit', 'JNSE', '금액');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('보증금', 'Deposit', 'DPST', '금액');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('관리비', 'Maintenance Fee', 'MNTFE', '금액');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('평수', 'Floor Area', 'FLRA', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('층수', 'Floor Number', 'FLNO', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('세대', 'Household', 'HSHD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('동', 'Building Number', 'DONG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('호', 'Unit Number', 'HO', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('인테리어', 'Interior', 'INTR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('리모델링', 'Remodeling', 'RMDL', '');

-- ■ 사람/관계/신분
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('배우자', 'Spouse', 'SPSE', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('부모', 'Parents', 'PRNT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('자녀', 'Children', 'CHLD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('형제', 'Siblings', 'SBLG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('친구', 'Friend', 'FRND', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('이웃', 'Neighbor', 'NGBR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('손님', 'Guest', 'GUST', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('운전자', 'Driver', 'DRVR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('승객', 'Passenger', 'PSGR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('보호자', 'Guardian', 'GRDN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('수혜자', 'Beneficiary', 'BNFC', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('피해자', 'Victim', 'VCTM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('가입자', 'Subscriber', 'SBSC', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('수령자', 'Recipient', 'RCPN', '');

-- ■ IT/디지털 서비스 (TB_WORD에 없는 것들)
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('앱', 'Application', 'APP', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('위젯', 'Widget', 'WDGT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('블루투스', 'Bluetooth', 'BT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('와이파이', 'Wi-Fi', 'WIFI', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('클라우드', 'Cloud', 'CLD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('스트리밍', 'Streaming', 'STRM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('다운로드', 'Download', 'DNLD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('업로드', 'Upload', 'UPLD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('로그인', 'Login', 'LGIN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('로그아웃', 'Logout', 'LGOT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('알림', 'Notification', 'NTFN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('즐겨찾기', 'Bookmark', 'BKMK', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('검색어', 'Search Keyword', 'SRCHKW', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('해시태그', 'Hashtag', 'HTAG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('댓글', 'Comment', 'CMNT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('좋아요', 'Like', 'LIKE', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('팔로워', 'Follower', 'FLWR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('구독', 'Subscription', 'SBSC', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('쿠폰', 'Coupon', 'CUPN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('포인트', 'Point', 'PNT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('멤버십', 'Membership', 'MBRSP', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('리뷰', 'Review', 'REVW', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('별점', 'Star Rating', 'STRT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('장바구니', 'Shopping Cart', 'CART', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('위시리스트', 'Wish List', 'WSHL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('프로필', 'Profile', 'PRFL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('닉네임', 'Nickname', 'NKNM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('아바타', 'Avatar', 'AVTR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('채팅', 'Chatting', 'CHAT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('메신저', 'Messenger', 'MSGR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('팝업', 'Popup', 'PPUP', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('배너', 'Banner', 'BNBR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('썸네일', 'Thumbnail', 'THMB', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('QR코드', 'QR Code', 'QRCD', '');

-- ■ 물류/유통
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('택배', 'Parcel Delivery', 'PRCL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('운송장', 'Waybill', 'WBIL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('송장', 'Invoice', 'INVC', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('포장', 'Packaging', 'PCKG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('팔레트', 'Pallet', 'PLLT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('컨테이너', 'Container', 'CNTN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('바코드', 'Barcode', 'BRCD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('반품', 'Return', 'RTRN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('교환', 'Exchange', 'EXCH', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('입고', 'Warehousing', 'WRHS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('출고', 'Shipment', 'SHPM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('피킹', 'Picking', 'PICK', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('적재', 'Loading', 'LDNG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('하역', 'Unloading', 'UNLD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('통관', 'Customs Clearance', 'CSTM', '');

-- ■ 자연/환경/날씨
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('날씨', 'Weather', 'WTHR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('기온', 'Temperature', 'TEMP', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('습도', 'Humidity', 'HMDT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('풍속', 'Wind Speed', 'WNSP', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('강수량', 'Precipitation', 'PRCP', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('미세먼지', 'Fine Dust', 'FDST', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('자외선', 'Ultraviolet', 'UV', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('지진', 'Earthquake', 'EQKE', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('태풍', 'Typhoon', 'TPHN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('홍수', 'Flood', 'FLOD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('가뭄', 'Drought', 'DRGT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('탄소', 'Carbon', 'CRBN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('재활용', 'Recycling', 'RCYC', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('쓰레기', 'Waste', 'WAST', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('오염', 'Pollution', 'PLTN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('에너지', 'Energy', 'ENRG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('태양광', 'Solar Power', 'SLPW', '');

-- ■ 법률/행정
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('변호사', 'Lawyer', 'LWYR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('판사', 'Judge', 'JUDG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('검사', 'Prosecutor', 'PRSC', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('재판', 'Trial', 'TRIL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('소송', 'Lawsuit', 'LWST', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('벌금', 'Fine', 'FINE', '금액');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('과태료', 'Penalty', 'PNLT', '금액');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('위반', 'Violation', 'VLTN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('민원', 'Civil Complaint', 'CVCP', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('신고', 'Report', 'RPRT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('공증', 'Notarization', 'NOTR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('위임', 'Delegation', 'DLGT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('특허', 'Patent', 'PTNT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('상표', 'Trademark', 'TRMK', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('저작권', 'Copyright', 'CPRT', '');

-- ■ 스포츠/레저/취미
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('축구', 'Soccer', 'SCOR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('야구', 'Baseball', 'BSBL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('농구', 'Basketball', 'BSKT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('배구', 'Volleyball', 'VLBL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('테니스', 'Tennis', 'TNIS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('골프', 'Golf', 'GOLF', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('수영', 'Swimming', 'SWIM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('등산', 'Hiking', 'HIKE', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('캠핑', 'Camping', 'CAMP', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('낚시', 'Fishing', 'FSNG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('스키', 'Ski', 'SKI', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('요가', 'Yoga', 'YOGA', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('필라테스', 'Pilates', 'PLTS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('헬스', 'Fitness', 'FTNS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('마라톤', 'Marathon', 'MRTN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('경기장', 'Stadium', 'STDM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('티켓', 'Ticket', 'TCKT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('예매', 'Reservation', 'RSVN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('공연', 'Performance', 'PFMC', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('전시', 'Exhibition', 'EXHB', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('축제', 'Festival', 'FSTV', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('관광', 'Tourism', 'TRSM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('여행', 'Travel', 'TRVL', '');

-- ■ 동물/식물/자연물
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('강아지', 'Puppy', 'PPPY', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('고양이', 'Cat', 'CAT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('반려동물', 'Pet', 'PET', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('동물병원', 'Veterinary Clinic', 'VTCL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('사료', 'Feed', 'FEED', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('꽃', 'Flower', 'FLWR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('나무', 'Tree', 'TREE', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('식물', 'Plant', 'PLNT', '');

-- ■ 색상/크기/형태 (수식어)
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('빨강', 'Red', 'RED', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('파랑', 'Blue', 'BLUE', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('노랑', 'Yellow', 'YLLW', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('초록', 'Green', 'GRN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('검정', 'Black', 'BLK', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('흰색', 'White', 'WHT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('대형', 'Large', 'LRG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('중형', 'Medium', 'MID', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('소형', 'Small', 'SML', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('미니', 'Mini', 'MINI', '');

-- ■ 기타 일상 단어
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('선물', 'Gift', 'GIFT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('경품', 'Prize', 'PRIZ', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('이벤트', 'Event', 'EVNT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('프로모션', 'Promotion', 'PRMO', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('브랜드', 'Brand', 'BRND', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('모델', 'Model', 'MODL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('버전', 'Version', 'VER', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('시리즈', 'Series', 'SRS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('패키지', 'Package', 'PKG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('옵션', 'Option', 'OPT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('사이즈', 'Size', 'SIZE', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('색상', 'Color', 'COLR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('무게', 'Weight', 'WGHT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('높이', 'Height', 'HGHT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('너비', 'Width', 'WDTH', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('깊이', 'Depth', 'DPTH', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('용량', 'Capacity', 'CPCT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('속도', 'Speed', 'SPD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('거리', 'Distance', 'DIST', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('면적', 'Area', 'AREA', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('부피', 'Volume', 'VOLM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('밀도', 'Density', 'DNST', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('농도', 'Concentration', 'CNCT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('압력', 'Pressure', 'PRSR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('전압', 'Voltage', 'VLTG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('전류', 'Current', 'CRNT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('저항', 'Resistance', 'RSTN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('주파수', 'Frequency', 'FREQ', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('파장', 'Wavelength', 'WVLN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('진동', 'Vibration', 'VBRT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('소음', 'Noise', 'NOIS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('방수', 'Waterproof', 'WTPF', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('방음', 'Soundproof', 'SDPF', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('단열', 'Insulation', 'INST', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('환기', 'Ventilation', 'VNTL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('난방', 'Heating', 'HEAT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('냉방', 'Cooling', 'COOL', '');

-- ■ 인사/노무/HR
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('채용', 'Recruitment', 'RCRT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('퇴직', 'Retirement', 'RTMT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('면접', 'Interview', 'ITVW', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('이력서', 'Resume', 'RESM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('연봉', 'Annual Salary', 'ASAL', '금액');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('상여금', 'Bonus', 'BONS', '금액');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('퇴직금', 'Severance Pay', 'SVNC', '금액');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('근태', 'Attendance', 'ATND', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('출퇴근', 'Commute', 'CMUT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('잔업', 'Overtime', 'OVTM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('휴가', 'Vacation', 'VCTN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('병가', 'Sick Leave', 'SCLV', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('출장', 'Business Trip', 'BTRP', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('인사평가', 'Performance Review', 'PFRVW', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('복리후생', 'Welfare Benefits', 'WLFR', '');

-- -------------------------------------------------------------
-- 4. TB_STRUCT_DIAG_HISTORY
--    구조 진단 이력 (재수집 → diff 결과 요약)
--    (세션: 3f1ffb70 / 데이터 구조 진단 기능 추가 시)
-- -------------------------------------------------------------
CREATE TABLE TB_STRUCT_DIAG_HISTORY (
    DIAG_ID             VARCHAR(40)     NOT NULL,
    DS_ID               VARCHAR(40),
    SCHEMA_NM           VARCHAR(100),
    DIAG_DT             TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    PREV_COLLECT_DT     TIMESTAMP,
    TOTAL_TABLES        INTEGER         DEFAULT 0,
    TOTAL_COLUMNS       INTEGER         DEFAULT 0,
    ADDED_TABLES        INTEGER         DEFAULT 0,
    ADDED_COLUMNS       INTEGER         DEFAULT 0,
    MODIFIED_COLUMNS    INTEGER         DEFAULT 0,
    DELETED_TABLES      INTEGER         DEFAULT 0,
    DELETED_COLUMNS     INTEGER         DEFAULT 0,
    CRET_USER_ID        VARCHAR(40),
    CONSTRAINT PK_TB_STRUCT_DIAG_HISTORY PRIMARY KEY (DIAG_ID)
);

COMMENT ON TABLE TB_STRUCT_DIAG_HISTORY IS '구조 진단 이력';
COMMENT ON COLUMN TB_STRUCT_DIAG_HISTORY.DIAG_ID IS '진단 ID';
COMMENT ON COLUMN TB_STRUCT_DIAG_HISTORY.DS_ID IS '데이터소스 ID';
COMMENT ON COLUMN TB_STRUCT_DIAG_HISTORY.SCHEMA_NM IS '스키마명';
COMMENT ON COLUMN TB_STRUCT_DIAG_HISTORY.DIAG_DT IS '진단 일시';
COMMENT ON COLUMN TB_STRUCT_DIAG_HISTORY.PREV_COLLECT_DT IS '이전 수집 일시';

-- -------------------------------------------------------------
-- 5. TB_STRUCT_DIAG_DETAIL
--    구조 진단 상세 (변경된 컬럼 목록)
-- -------------------------------------------------------------
CREATE TABLE TB_STRUCT_DIAG_DETAIL (
    DIAG_ID             VARCHAR(40)     NOT NULL,
    SEQ                 INTEGER         NOT NULL,
    TABLE_NM            VARCHAR(200),
    COLUMN_NM           VARCHAR(200),
    CHANGE_TYPE         VARCHAR(20),
    PREV_DATA_TYPE      VARCHAR(50),
    CURR_DATA_TYPE      VARCHAR(50),
    PREV_DATA_LEN       INTEGER,
    CURR_DATA_LEN       INTEGER,
    PREV_NULLABLE       CHAR(1),
    CURR_NULLABLE       CHAR(1),
    CONSTRAINT PK_TB_STRUCT_DIAG_DETAIL PRIMARY KEY (DIAG_ID, SEQ)
);

COMMENT ON TABLE TB_STRUCT_DIAG_DETAIL IS '구조 진단 상세 (변경 컬럼)';
COMMENT ON COLUMN TB_STRUCT_DIAG_DETAIL.CHANGE_TYPE IS 'ADDED / MODIFIED / DELETED';
