-- =============================================================
-- Claude가 제공한 DDL 모음 (PostgreSQL)
-- 프로젝트: ndata-quality
-- 정리일: 2026-03-23
-- =============================================================

-- -------------------------------------------------------------
-- 1. TB_DATA_MODEL_SCHEMA
--    데이터모델별 수집 대상 스키마 관리
--    (세션: 278cae7d / 데이터모델 수집 스키마 기능 추가 시)
-- -------------------------------------------------------------
CREATE TABLE TB_DATA_MODEL_SCHEMA (
    DM_ID         VARCHAR(36)  NOT NULL,
    SCHEMA_NM     VARCHAR(100) NOT NULL,
    USE_YN        CHAR(1)      NOT NULL DEFAULT 'Y',
    CRET_DT       VARCHAR(14),
    CRET_USER_ID  VARCHAR(50),
    PRIMARY KEY (DM_ID, SCHEMA_NM)
);

-- -------------------------------------------------------------
-- 2. TB_DIAG_JOB
--    표준화 진단 작업(Job) 이력
--    (세션: 3f1ffb70 / 표준화 진단 기능 구현 시)
-- -------------------------------------------------------------
CREATE TABLE TB_DIAG_JOB (
    DIAG_JOB_ID     VARCHAR(50)     NOT NULL,
    DM_CLCT_ID      VARCHAR(50)     NOT NULL,
    DM_ID           VARCHAR(50)     NOT NULL,
    STATUS          VARCHAR(20)     NOT NULL DEFAULT 'READY',
    TOTAL_CNT       INTEGER         DEFAULT 0,
    PROCESS_CNT     INTEGER         DEFAULT 0,
    RESULT_CNT      INTEGER         DEFAULT 0,
    CRET_DT         VARCHAR(14),
    CRET_USER_ID    VARCHAR(50),
    START_DT        VARCHAR(14),
    END_DT          VARCHAR(14),
    CONSTRAINT PK_TB_DIAG_JOB PRIMARY KEY (DIAG_JOB_ID)
);

-- -------------------------------------------------------------
-- 3. TB_DIAG_RESULT
--    표준화 진단 결과 상세 (1건 = 1이슈)
--    (세션: 3f1ffb70 / 표준화 진단 기능 구현 시)
-- -------------------------------------------------------------
CREATE TABLE TB_DIAG_RESULT (
    RESULT_ID       BIGSERIAL       NOT NULL,
    DIAG_JOB_ID     VARCHAR(50)     NOT NULL,
    OBJ_NM          VARCHAR(200),
    ATTR_NM         VARCHAR(200),
    ATTR_NM_KR      VARCHAR(200),
    DIAG_TYPE       VARCHAR(50)     NOT NULL,
    DIAG_DETAIL     TEXT,
    STD_VALUE       VARCHAR(500),
    ACTUAL_VALUE    VARCHAR(500),
    CONSTRAINT PK_TB_DIAG_RESULT PRIMARY KEY (RESULT_ID)
);

-- -------------------------------------------------------------
-- 4. TB_WORD_DICT
--    미등록 단어 영문약어 추천용 한영 매핑 사전
--    TB_WORD에 없는 단어가 분석될 때 영문약어/영문명 추천에 사용
--    (세션: 3f1ffb70 / 표준화 추천 - 미등록 단어 추천 기능)
-- -------------------------------------------------------------
CREATE TABLE TB_WORD_DICT (
    WORD_KOR        VARCHAR(100)    NOT NULL,
    WORD_ENG        VARCHAR(200),
    WORD_ABRV       VARCHAR(50),
    DOMAIN_CLSF_NM  VARCHAR(100),
    CONSTRAINT PK_TB_WORD_DICT PRIMARY KEY (WORD_KOR)
);

COMMENT ON TABLE  TB_WORD_DICT IS '미등록 단어 영문 추천 사전';
COMMENT ON COLUMN TB_WORD_DICT.WORD_KOR       IS '한글 단어명';
COMMENT ON COLUMN TB_WORD_DICT.WORD_ENG       IS '영문 풀네임';
COMMENT ON COLUMN TB_WORD_DICT.WORD_ABRV      IS '영문 약어';
COMMENT ON COLUMN TB_WORD_DICT.DOMAIN_CLSF_NM IS '도메인 분류명 (금액, 일자, 코드 등)';

-- -------------------------------------------------------------
-- TB_WORD_DICT 시드 데이터
-- TB_WORD(공공 표준 단어사전 3,284건)에 없는 일상/일반 단어
-- 용도: 미등록 단어 분석 시 영문약어/영문명 자동 추천
-- -------------------------------------------------------------

-- ■ 일상 사물/기기
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('핸드폰', 'Mobile Phone', 'MBLPHN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('스마트폰', 'Smart Phone', 'SMTPHN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('노트북', 'Notebook', 'NTBK', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('태블릿', 'Tablet', 'TBLT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('키보드', 'Keyboard', 'KBD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('마우스', 'Mouse', 'MOS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('프린터', 'Printer', 'PRNT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('스캐너', 'Scanner', 'SCNR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('모니터', 'Monitor', 'MNTR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('냉장고', 'Refrigerator', 'REFR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('세탁기', 'Washing Machine', 'WSMN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('에어컨', 'Air Conditioner', 'ARCD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('텔레비전', 'Television', 'TV', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('카메라', 'Camera', 'CAM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('배터리', 'Battery', 'BTRY', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('센서', 'Sensor', 'SNSR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('로봇', 'Robot', 'ROBT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('드론', 'Drone', 'DRON', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('리모컨', 'Remote Control', 'RMTC', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('충전기', 'Charger', 'CHGR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('어댑터', 'Adapter', 'ADPT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('스피커', 'Speaker', 'SPKR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('이어폰', 'Earphone', 'ERPHN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('헤드셋', 'Headset', 'HDST', '');

-- ■ 소지품/의류/잡화
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('지갑', 'Wallet', 'WLET', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('가방', 'Bag', 'BAG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('안경', 'Glasses', 'GLSS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('시계', 'Watch', 'WTCH', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('열쇠', 'Key', 'KEY', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('우산', 'Umbrella', 'UMBR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('의류', 'Clothing', 'CLTH', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('신발', 'Shoes', 'SHOE', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('모자', 'Hat', 'HAT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('장갑', 'Gloves', 'GLVS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('넥타이', 'Necktie', 'NKTI', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('화장품', 'Cosmetics', 'COSM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('악세서리', 'Accessory', 'ACSR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('보석', 'Jewelry', 'JWLR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('향수', 'Perfume', 'PRFM', '');

-- ■ 교통/이동
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('자전거', 'Bicycle', 'BCYL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('오토바이', 'Motorcycle', 'MTCY', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('트럭', 'Truck', 'TRCK', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('버스', 'Bus', 'BUS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('택시', 'Taxi', 'TAXI', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('지하철', 'Subway', 'SBWY', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('기차', 'Train', 'TRAN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('비행기', 'Airplane', 'ARPL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('선박', 'Ship', 'SHIP', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('엘리베이터', 'Elevator', 'ELVT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('에스컬레이터', 'Escalator', 'ESCL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('주차', 'Parking', 'PRKG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('톨게이트', 'Tollgate', 'TLGT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('내비게이션', 'Navigation', 'NAVI', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('킥보드', 'Kickboard', 'KCBD', '');

-- ■ 건물/장소/시설
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('아파트', 'Apartment', 'APT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('오피스텔', 'Officetel', 'OFSTL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('빌딩', 'Building', 'BLDG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('공장', 'Factory', 'FCTY', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('창고', 'Warehouse', 'WRHS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('매장', 'Store', 'STOR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('식당', 'Restaurant', 'RSTR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('카페', 'Cafe', 'CAFE', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('편의점', 'Convenience Store', 'CVST', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('마트', 'Mart', 'MART', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('백화점', 'Department Store', 'DPST', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('약국', 'Pharmacy', 'PHRM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('미용실', 'Hair Salon', 'HRSN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('세차장', 'Car Wash', 'CWSH', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('주유소', 'Gas Station', 'GSTN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('체육관', 'Gymnasium', 'GYM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('수영장', 'Swimming Pool', 'SWPL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('놀이터', 'Playground', 'PLGD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('도서관', 'Library', 'LBRY', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('영화관', 'Cinema', 'CNMA', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('호텔', 'Hotel', 'HOTL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('펜션', 'Pension', 'PNSN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('콘도', 'Condominium', 'COND', '');

-- ■ 음식/식품
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('음식', 'Food', 'FOOD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('음료', 'Beverage', 'BVRG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('과일', 'Fruit', 'FRUT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('채소', 'Vegetable', 'VGTB', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('고기', 'Meat', 'MEAT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('생선', 'Fish', 'FISH', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('빵', 'Bread', 'BRAD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('과자', 'Snack', 'SNCK', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('우유', 'Milk', 'MILK', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('커피', 'Coffee', 'COFE', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('반찬', 'Side Dish', 'SDSH', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('도시락', 'Lunch Box', 'LNBX', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('레시피', 'Recipe', 'RCPE', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('식재료', 'Ingredient', 'INGR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('조미료', 'Seasoning', 'SASN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('냉동', 'Frozen', 'FRZN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('유통기한', 'Expiration Date', 'EXPDT', '일자');

-- ■ 의료/건강
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('환자', 'Patient', 'PTNT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('의사', 'Doctor', 'DCTR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('간호사', 'Nurse', 'NURS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('약사', 'Pharmacist', 'PHMC', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('처방전', 'Prescription', 'PRSC', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('진료', 'Medical Treatment', 'MDTRT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('진단', 'Diagnosis', 'DIAG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('수술', 'Surgery', 'SRGR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('입원', 'Hospitalization', 'HSPT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('퇴원', 'Discharge', 'DSCH', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('예방접종', 'Vaccination', 'VCTN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('혈압', 'Blood Pressure', 'BLPR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('혈당', 'Blood Sugar', 'BLSG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('체온', 'Body Temperature', 'BDTP', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('체중', 'Body Weight', 'BDWT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('신장', 'Height', 'HGHT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('알레르기', 'Allergy', 'ALRG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('증상', 'Symptom', 'SMTM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('복용', 'Medication', 'MDCT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('건강검진', 'Health Checkup', 'HLCK', '');

-- ■ 교육/학교
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('학생', 'Student', 'STDT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('교사', 'Teacher', 'TCHR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('교수', 'Professor', 'PROF', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('강사', 'Instructor', 'INST', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('학교', 'School', 'SCHL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('대학교', 'University', 'UNIV', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('학원', 'Academy', 'ACDM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('강의', 'Lecture', 'LCTR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('수업', 'Class', 'CLSS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('시험', 'Exam', 'EXAM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('성적', 'Grade', 'GRD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('학점', 'Credit', 'CRDT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('졸업', 'Graduation', 'GRDT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('입학', 'Admission', 'ADMN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('장학금', 'Scholarship', 'SCHLR', '금액');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('등록금', 'Tuition', 'TUTN', '금액');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('교과서', 'Textbook', 'TXBK', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('과제', 'Assignment', 'ASGN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('출석', 'Attendance', 'ATND', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('결석', 'Absence', 'ABSN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('자격증', 'Certificate', 'CERT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('연수', 'Training', 'TRNG', '');

-- ■ 부동산/주거
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('임대', 'Lease', 'LEAS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('임차', 'Rent', 'RENT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('월세', 'Monthly Rent', 'MRENT', '금액');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('전세', 'Jeonse Deposit', 'JNSE', '금액');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('보증금', 'Deposit', 'DPST', '금액');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('관리비', 'Maintenance Fee', 'MNTFE', '금액');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('평수', 'Floor Area', 'FLRA', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('층수', 'Floor Number', 'FLNO', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('세대', 'Household', 'HSHD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('동', 'Building Number', 'DONG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('호', 'Unit Number', 'HO', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('인테리어', 'Interior', 'INTR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('리모델링', 'Remodeling', 'RMDL', '');

-- ■ 사람/관계/신분
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('배우자', 'Spouse', 'SPSE', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('부모', 'Parents', 'PRNT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('자녀', 'Children', 'CHLD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('형제', 'Siblings', 'SBLG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('친구', 'Friend', 'FRND', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('이웃', 'Neighbor', 'NGBR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('손님', 'Guest', 'GUST', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('운전자', 'Driver', 'DRVR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('승객', 'Passenger', 'PSGR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('보호자', 'Guardian', 'GRDN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('수혜자', 'Beneficiary', 'BNFC', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('피해자', 'Victim', 'VCTM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('가입자', 'Subscriber', 'SBSC', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('수령자', 'Recipient', 'RCPN', '');

-- ■ IT/디지털 서비스 (TB_WORD에 없는 것들)
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('앱', 'Application', 'APP', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('위젯', 'Widget', 'WDGT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('블루투스', 'Bluetooth', 'BT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('와이파이', 'Wi-Fi', 'WIFI', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('클라우드', 'Cloud', 'CLD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('스트리밍', 'Streaming', 'STRM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('다운로드', 'Download', 'DNLD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('업로드', 'Upload', 'UPLD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('로그인', 'Login', 'LGIN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('로그아웃', 'Logout', 'LGOT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('알림', 'Notification', 'NTFN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('즐겨찾기', 'Bookmark', 'BKMK', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('검색어', 'Search Keyword', 'SRCHKW', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('해시태그', 'Hashtag', 'HTAG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('댓글', 'Comment', 'CMNT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('좋아요', 'Like', 'LIKE', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('팔로워', 'Follower', 'FLWR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('구독', 'Subscription', 'SBSC', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('쿠폰', 'Coupon', 'CUPN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('포인트', 'Point', 'PNT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('멤버십', 'Membership', 'MBRSP', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('리뷰', 'Review', 'REVW', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('별점', 'Star Rating', 'STRT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('장바구니', 'Shopping Cart', 'CART', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('위시리스트', 'Wish List', 'WSHL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('프로필', 'Profile', 'PRFL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('닉네임', 'Nickname', 'NKNM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('아바타', 'Avatar', 'AVTR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('채팅', 'Chatting', 'CHAT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('메신저', 'Messenger', 'MSGR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('팝업', 'Popup', 'PPUP', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('배너', 'Banner', 'BNBR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('썸네일', 'Thumbnail', 'THMB', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('QR코드', 'QR Code', 'QRCD', '');

-- ■ 물류/유통
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('택배', 'Parcel Delivery', 'PRCL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('운송장', 'Waybill', 'WBIL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('송장', 'Invoice', 'INVC', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('포장', 'Packaging', 'PCKG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('팔레트', 'Pallet', 'PLLT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('컨테이너', 'Container', 'CNTN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('바코드', 'Barcode', 'BRCD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('반품', 'Return', 'RTRN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('교환', 'Exchange', 'EXCH', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('입고', 'Warehousing', 'WRHS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('출고', 'Shipment', 'SHPM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('피킹', 'Picking', 'PICK', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('적재', 'Loading', 'LDNG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('하역', 'Unloading', 'UNLD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('통관', 'Customs Clearance', 'CSTM', '');

-- ■ 자연/환경/날씨
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('날씨', 'Weather', 'WTHR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('기온', 'Temperature', 'TEMP', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('습도', 'Humidity', 'HMDT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('풍속', 'Wind Speed', 'WNSP', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('강수량', 'Precipitation', 'PRCP', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('미세먼지', 'Fine Dust', 'FDST', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('자외선', 'Ultraviolet', 'UV', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('지진', 'Earthquake', 'EQKE', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('태풍', 'Typhoon', 'TPHN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('홍수', 'Flood', 'FLOD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('가뭄', 'Drought', 'DRGT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('탄소', 'Carbon', 'CRBN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('재활용', 'Recycling', 'RCYC', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('쓰레기', 'Waste', 'WAST', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('오염', 'Pollution', 'PLTN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('에너지', 'Energy', 'ENRG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('태양광', 'Solar Power', 'SLPW', '');

-- ■ 법률/행정
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('변호사', 'Lawyer', 'LWYR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('판사', 'Judge', 'JUDG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('검사', 'Prosecutor', 'PRSC', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('재판', 'Trial', 'TRIL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('소송', 'Lawsuit', 'LWST', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('벌금', 'Fine', 'FINE', '금액');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('과태료', 'Penalty', 'PNLT', '금액');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('위반', 'Violation', 'VLTN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('민원', 'Civil Complaint', 'CVCP', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('신고', 'Report', 'RPRT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('공증', 'Notarization', 'NOTR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('위임', 'Delegation', 'DLGT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('특허', 'Patent', 'PTNT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('상표', 'Trademark', 'TRMK', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('저작권', 'Copyright', 'CPRT', '');

-- ■ 스포츠/레저/취미
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('축구', 'Soccer', 'SCOR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('야구', 'Baseball', 'BSBL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('농구', 'Basketball', 'BSKT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('배구', 'Volleyball', 'VLBL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('테니스', 'Tennis', 'TNIS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('골프', 'Golf', 'GOLF', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('수영', 'Swimming', 'SWIM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('등산', 'Hiking', 'HIKE', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('캠핑', 'Camping', 'CAMP', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('낚시', 'Fishing', 'FSNG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('스키', 'Ski', 'SKI', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('요가', 'Yoga', 'YOGA', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('필라테스', 'Pilates', 'PLTS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('헬스', 'Fitness', 'FTNS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('마라톤', 'Marathon', 'MRTN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('경기장', 'Stadium', 'STDM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('티켓', 'Ticket', 'TCKT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('예매', 'Reservation', 'RSVN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('공연', 'Performance', 'PFMC', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('전시', 'Exhibition', 'EXHB', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('축제', 'Festival', 'FSTV', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('관광', 'Tourism', 'TRSM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('여행', 'Travel', 'TRVL', '');

-- ■ 동물/식물/자연물
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('강아지', 'Puppy', 'PPPY', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('고양이', 'Cat', 'CAT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('반려동물', 'Pet', 'PET', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('동물병원', 'Veterinary Clinic', 'VTCL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('사료', 'Feed', 'FEED', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('꽃', 'Flower', 'FLWR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('나무', 'Tree', 'TREE', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('식물', 'Plant', 'PLNT', '');

-- ■ 색상/크기/형태 (수식어)
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('빨강', 'Red', 'RED', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('파랑', 'Blue', 'BLUE', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('노랑', 'Yellow', 'YLLW', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('초록', 'Green', 'GRN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('검정', 'Black', 'BLK', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('흰색', 'White', 'WHT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('대형', 'Large', 'LRG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('중형', 'Medium', 'MID', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('소형', 'Small', 'SML', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('미니', 'Mini', 'MINI', '');

-- ■ 기타 일상 단어
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('선물', 'Gift', 'GIFT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('경품', 'Prize', 'PRIZ', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('이벤트', 'Event', 'EVNT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('프로모션', 'Promotion', 'PRMO', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('브랜드', 'Brand', 'BRND', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('모델', 'Model', 'MODL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('버전', 'Version', 'VER', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('시리즈', 'Series', 'SRS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('패키지', 'Package', 'PKG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('옵션', 'Option', 'OPT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('사이즈', 'Size', 'SIZE', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('색상', 'Color', 'COLR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('무게', 'Weight', 'WGHT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('높이', 'Height', 'HGHT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('너비', 'Width', 'WDTH', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('깊이', 'Depth', 'DPTH', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('용량', 'Capacity', 'CPCT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('속도', 'Speed', 'SPD', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('거리', 'Distance', 'DIST', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('면적', 'Area', 'AREA', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('부피', 'Volume', 'VOLM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('밀도', 'Density', 'DNST', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('농도', 'Concentration', 'CNCT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('압력', 'Pressure', 'PRSR', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('전압', 'Voltage', 'VLTG', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('전류', 'Current', 'CRNT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('저항', 'Resistance', 'RSTN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('주파수', 'Frequency', 'FREQ', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('파장', 'Wavelength', 'WVLN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('진동', 'Vibration', 'VBRT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('소음', 'Noise', 'NOIS', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('방수', 'Waterproof', 'WTPF', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('방음', 'Soundproof', 'SDPF', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('단열', 'Insulation', 'INST', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('환기', 'Ventilation', 'VNTL', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('난방', 'Heating', 'HEAT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('냉방', 'Cooling', 'COOL', '');

-- ■ 인사/노무/HR
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('채용', 'Recruitment', 'RCRT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('퇴직', 'Retirement', 'RTMT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('면접', 'Interview', 'ITVW', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('이력서', 'Resume', 'RESM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('연봉', 'Annual Salary', 'ASAL', '금액');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('상여금', 'Bonus', 'BONS', '금액');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('퇴직금', 'Severance Pay', 'SVNC', '금액');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('근태', 'Attendance', 'ATND', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('출퇴근', 'Commute', 'CMUT', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('잔업', 'Overtime', 'OVTM', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('휴가', 'Vacation', 'VCTN', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('병가', 'Sick Leave', 'SCLV', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('출장', 'Business Trip', 'BTRP', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('인사평가', 'Performance Review', 'PFRVW', '');
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('복리후생', 'Welfare Benefits', 'WLFR', '');

-- -------------------------------------------------------------
-- 4. TB_STRUCT_DIAG_HISTORY
--    구조 진단 이력 (재수집 → diff 결과 요약)
--    (세션: 3f1ffb70 / 데이터 구조 진단 기능 추가 시)
-- -------------------------------------------------------------
CREATE TABLE TB_STRUCT_DIAG_HISTORY (
    DIAG_ID             VARCHAR(40)     NOT NULL,
    DS_ID               VARCHAR(40),
    DATA_MODEL_ID       VARCHAR(40),
    SCHEMA_NM           VARCHAR(100),
    DIAG_DT             TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    PREV_COLLECT_DT     TIMESTAMP,
    TOTAL_TABLES        INTEGER         DEFAULT 0,
    TOTAL_COLUMNS       INTEGER         DEFAULT 0,
    ADDED_TABLES        INTEGER         DEFAULT 0,
    ADDED_COLUMNS       INTEGER         DEFAULT 0,
    MODIFIED_COLUMNS    INTEGER         DEFAULT 0,
    DELETED_TABLES      INTEGER         DEFAULT 0,
    DELETED_COLUMNS     INTEGER         DEFAULT 0,
    STATUS              VARCHAR(20)     DEFAULT 'READY',
    CRET_USER_ID        VARCHAR(40),
    CONSTRAINT PK_TB_STRUCT_DIAG_HISTORY PRIMARY KEY (DIAG_ID)
);

COMMENT ON TABLE TB_STRUCT_DIAG_HISTORY IS '구조 진단 이력';
COMMENT ON COLUMN TB_STRUCT_DIAG_HISTORY.DIAG_ID IS '진단 ID';
COMMENT ON COLUMN TB_STRUCT_DIAG_HISTORY.DS_ID IS '데이터소스 ID';
COMMENT ON COLUMN TB_STRUCT_DIAG_HISTORY.DATA_MODEL_ID IS '데이터모델 ID';
COMMENT ON COLUMN TB_STRUCT_DIAG_HISTORY.SCHEMA_NM IS '스키마명';
COMMENT ON COLUMN TB_STRUCT_DIAG_HISTORY.DIAG_DT IS '진단 일시';
COMMENT ON COLUMN TB_STRUCT_DIAG_HISTORY.PREV_COLLECT_DT IS '이전 수집 일시';
COMMENT ON COLUMN TB_STRUCT_DIAG_HISTORY.STATUS IS '상태 (READY/RUNNING/DONE/ERROR)';

-- 기존 테이블에 컬럼 추가용 ALTER (이미 테이블이 존재할 경우 사용)
-- ALTER TABLE TB_STRUCT_DIAG_HISTORY ADD COLUMN DATA_MODEL_ID VARCHAR(40);
-- ALTER TABLE TB_STRUCT_DIAG_HISTORY ADD COLUMN STATUS VARCHAR(20) DEFAULT 'DONE';

-- -------------------------------------------------------------
-- 5. TB_STRUCT_DIAG_DETAIL
--    구조 진단 상세 (변경된 컬럼 목록)
-- -------------------------------------------------------------
CREATE TABLE TB_STRUCT_DIAG_DETAIL (
    DIAG_ID             VARCHAR(40)     NOT NULL,
    SEQ                 INTEGER         NOT NULL,
    TABLE_NM            VARCHAR(200),
    COLUMN_NM           VARCHAR(200),
    CHANGE_TYPE         VARCHAR(20),
    PREV_DATA_TYPE      VARCHAR(50),
    CURR_DATA_TYPE      VARCHAR(50),
    PREV_DATA_LEN       INTEGER,
    CURR_DATA_LEN       INTEGER,
    PREV_NULLABLE       CHAR(1),
    CURR_NULLABLE       CHAR(1),
    CONSTRAINT PK_TB_STRUCT_DIAG_DETAIL PRIMARY KEY (DIAG_ID, SEQ)
);

COMMENT ON TABLE TB_STRUCT_DIAG_DETAIL IS '구조 진단 상세 (변경 컬럼)';
COMMENT ON COLUMN TB_STRUCT_DIAG_DETAIL.CHANGE_TYPE IS 'ADDED / MODIFIED / DELETED';

-- -------------------------------------------------------------
-- 5-1. TB_STRUCT_DIAG_DETAIL OWNER 컬럼 (이전 세션에서 ALTER 추가됨, DDL 문서 동기화)
-- -------------------------------------------------------------
ALTER TABLE TB_STRUCT_DIAG_DETAIL ADD COLUMN IF NOT EXISTS OWNER VARCHAR(100);

-- -------------------------------------------------------------
-- 5-2. TB_DATA_MODEL_INDEX (인덱스 수집)
-- -------------------------------------------------------------
CREATE TABLE TB_DATA_MODEL_INDEX (
    DM_CLCT_ID          VARCHAR(40)     NOT NULL,
    SEQ                 INTEGER         NOT NULL,
    DM_ID               VARCHAR(40),
    OBJ_OWNER           VARCHAR(100),
    TABLE_NM            VARCHAR(200),
    INDEX_NM            VARCHAR(200),
    INDEX_TYPE          VARCHAR(50),
    UNIQUENESS          VARCHAR(10),
    COLUMN_NM           VARCHAR(200),
    COLUMN_POS          INTEGER,
    SORT_ORDER          VARCHAR(10),
    TABLESPACE_NM       VARCHAR(100),
    CONSTRAINT PK_TB_DATA_MODEL_INDEX PRIMARY KEY (DM_CLCT_ID, SEQ)
);

COMMENT ON TABLE TB_DATA_MODEL_INDEX IS '데이터모델 인덱스 수집';
COMMENT ON COLUMN TB_DATA_MODEL_INDEX.DM_CLCT_ID IS '수집 ID';
COMMENT ON COLUMN TB_DATA_MODEL_INDEX.INDEX_TYPE IS 'NORMAL, BITMAP, UNIQUE 등';
COMMENT ON COLUMN TB_DATA_MODEL_INDEX.UNIQUENESS IS 'UNIQUE / NONUNIQUE';
COMMENT ON COLUMN TB_DATA_MODEL_INDEX.COLUMN_POS IS '인덱스 구성 컬럼 순서';
COMMENT ON COLUMN TB_DATA_MODEL_INDEX.SORT_ORDER IS 'ASC / DESC';

-- -------------------------------------------------------------
-- 5-3. TB_DATA_MODEL_CONSTRAINT (제약조건 수집)
-- -------------------------------------------------------------
CREATE TABLE TB_DATA_MODEL_CONSTRAINT (
    DM_CLCT_ID          VARCHAR(40)     NOT NULL,
    SEQ                 INTEGER         NOT NULL,
    DM_ID               VARCHAR(40),
    OBJ_OWNER           VARCHAR(100),
    TABLE_NM            VARCHAR(200),
    CONSTRAINT_NM       VARCHAR(200),
    CONSTRAINT_TYPE     VARCHAR(10),
    COLUMN_NM           VARCHAR(200),
    COLUMN_POS          INTEGER,
    REF_OWNER           VARCHAR(100),
    REF_TABLE_NM        VARCHAR(200),
    REF_COLUMN_NM       VARCHAR(200),
    DELETE_RULE          VARCHAR(20),
    STATUS              VARCHAR(10),
    SEARCH_CONDITION    VARCHAR(2000),
    CONSTRAINT PK_TB_DATA_MODEL_CONSTRAINT PRIMARY KEY (DM_CLCT_ID, SEQ)
);

COMMENT ON TABLE TB_DATA_MODEL_CONSTRAINT IS '데이터모델 제약조건 수집';
COMMENT ON COLUMN TB_DATA_MODEL_CONSTRAINT.CONSTRAINT_TYPE IS 'P(PK), R(FK), U(UK), C(CHECK)';
COMMENT ON COLUMN TB_DATA_MODEL_CONSTRAINT.COLUMN_POS IS '복합키 컬럼 순서';
COMMENT ON COLUMN TB_DATA_MODEL_CONSTRAINT.REF_OWNER IS 'FK 참조 스키마';
COMMENT ON COLUMN TB_DATA_MODEL_CONSTRAINT.REF_TABLE_NM IS 'FK 참조 테이블';
COMMENT ON COLUMN TB_DATA_MODEL_CONSTRAINT.REF_COLUMN_NM IS 'FK 참조 컬럼';
COMMENT ON COLUMN TB_DATA_MODEL_CONSTRAINT.DELETE_RULE IS 'FK 삭제 규칙 (CASCADE, SET NULL 등)';
COMMENT ON COLUMN TB_DATA_MODEL_CONSTRAINT.STATUS IS 'ENABLED / DISABLED';

-- -------------------------------------------------------------
-- 5-4. TB_STRUCT_DIAG_HISTORY 인덱스/제약조건 통계 컬럼 추가
-- -------------------------------------------------------------
ALTER TABLE TB_STRUCT_DIAG_HISTORY ADD COLUMN IF NOT EXISTS TOTAL_INDEXES INTEGER DEFAULT 0;
ALTER TABLE TB_STRUCT_DIAG_HISTORY ADD COLUMN IF NOT EXISTS ADDED_INDEXES INTEGER DEFAULT 0;
ALTER TABLE TB_STRUCT_DIAG_HISTORY ADD COLUMN IF NOT EXISTS MODIFIED_INDEXES INTEGER DEFAULT 0;
ALTER TABLE TB_STRUCT_DIAG_HISTORY ADD COLUMN IF NOT EXISTS DELETED_INDEXES INTEGER DEFAULT 0;
ALTER TABLE TB_STRUCT_DIAG_HISTORY ADD COLUMN IF NOT EXISTS TOTAL_CONSTRAINTS INTEGER DEFAULT 0;
ALTER TABLE TB_STRUCT_DIAG_HISTORY ADD COLUMN IF NOT EXISTS ADDED_CONSTRAINTS INTEGER DEFAULT 0;
ALTER TABLE TB_STRUCT_DIAG_HISTORY ADD COLUMN IF NOT EXISTS MODIFIED_CONSTRAINTS INTEGER DEFAULT 0;
ALTER TABLE TB_STRUCT_DIAG_HISTORY ADD COLUMN IF NOT EXISTS DELETED_CONSTRAINTS INTEGER DEFAULT 0;

-- -------------------------------------------------------------
-- 5-5. TB_STRUCT_DIAG_INDEX_DETAIL (인덱스 변경 상세)
-- -------------------------------------------------------------
CREATE TABLE TB_STRUCT_DIAG_INDEX_DETAIL (
    DIAG_ID             VARCHAR(40)     NOT NULL,
    SEQ                 INTEGER         NOT NULL,
    OWNER               VARCHAR(100),
    TABLE_NM            VARCHAR(200),
    INDEX_NM            VARCHAR(200),
    CHANGE_TYPE         VARCHAR(20),
    PREV_INDEX_TYPE     VARCHAR(50),
    CURR_INDEX_TYPE     VARCHAR(50),
    PREV_UNIQUENESS     VARCHAR(10),
    CURR_UNIQUENESS     VARCHAR(10),
    PREV_COLUMNS        VARCHAR(1000),
    CURR_COLUMNS        VARCHAR(1000),
    CONSTRAINT PK_TB_STRUCT_DIAG_INDEX_DETAIL PRIMARY KEY (DIAG_ID, SEQ)
);

COMMENT ON TABLE TB_STRUCT_DIAG_INDEX_DETAIL IS '구조 진단 상세 - 인덱스 변경';

-- -------------------------------------------------------------
-- 5-6. TB_STRUCT_DIAG_CONSTRAINT_DETAIL (제약조건 변경 상세)
-- -------------------------------------------------------------
CREATE TABLE TB_STRUCT_DIAG_CONSTRAINT_DETAIL (
    DIAG_ID             VARCHAR(40)     NOT NULL,
    SEQ                 INTEGER         NOT NULL,
    OWNER               VARCHAR(100),
    TABLE_NM            VARCHAR(200),
    CONSTRAINT_NM       VARCHAR(200),
    CHANGE_TYPE         VARCHAR(20),
    PREV_CONSTRAINT_TYPE VARCHAR(10),
    CURR_CONSTRAINT_TYPE VARCHAR(10),
    PREV_COLUMNS        VARCHAR(1000),
    CURR_COLUMNS        VARCHAR(1000),
    PREV_REF_TABLE      VARCHAR(200),
    CURR_REF_TABLE      VARCHAR(200),
    PREV_REF_COLUMNS    VARCHAR(1000),
    CURR_REF_COLUMNS    VARCHAR(1000),
    PREV_DELETE_RULE    VARCHAR(20),
    CURR_DELETE_RULE    VARCHAR(20),
    PREV_STATUS         VARCHAR(10),
    CURR_STATUS         VARCHAR(10),
    CONSTRAINT PK_TB_STRUCT_DIAG_CONSTRAINT_DETAIL PRIMARY KEY (DIAG_ID, SEQ)
);

COMMENT ON TABLE TB_STRUCT_DIAG_CONSTRAINT_DETAIL IS '구조 진단 상세 - 제약조건 변경';

-- -------------------------------------------------------------
-- 6. TB_DATA_MODEL 구조진단 결과 컬럼 추가
-- -------------------------------------------------------------
ALTER TABLE TB_DATA_MODEL ADD COLUMN IF NOT EXISTS STRUCT_DIAG_YN CHAR(1) DEFAULT 'N';
ALTER TABLE TB_DATA_MODEL ADD COLUMN IF NOT EXISTS STRUCT_DIAG_DT TIMESTAMP;
COMMENT ON COLUMN TB_DATA_MODEL.STRUCT_DIAG_YN IS '구조진단 일치여부 (Y=일치, N=불일치/미진단)';
COMMENT ON COLUMN TB_DATA_MODEL.STRUCT_DIAG_DT IS '구조진단 최종 실행일시';

-- -------------------------------------------------------------
-- 7. TB_CHANGE_HISTORY / TB_CHANGE_HISTORY_DETAIL
--    변경 이력 추적
-- -------------------------------------------------------------
CREATE TABLE TB_CHANGE_HISTORY (
    CHANGE_ID         VARCHAR(40)     NOT NULL,
    CHANGE_TYPE       VARCHAR(20)     NOT NULL,
    TARGET_TYPE       VARCHAR(20)     NOT NULL,
    TARGET_ID         VARCHAR(40),
    TARGET_NM         VARCHAR(200),
    CHANGE_CNT        INTEGER         DEFAULT 1,
    SUMMARY           VARCHAR(500),
    PREV_VALUE        TEXT,
    CURR_VALUE        TEXT,
    CHANGE_USER_ID    VARCHAR(40),
    CHANGE_DT         TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CHANGE_SOURCE     VARCHAR(20),
    CONSTRAINT PK_TB_CHANGE_HISTORY PRIMARY KEY (CHANGE_ID)
);

CREATE INDEX IDX_CHANGE_HISTORY_DT ON TB_CHANGE_HISTORY (CHANGE_DT DESC);
COMMENT ON COLUMN TB_CHANGE_HISTORY.CHANGE_SOURCE IS 'ADMIN_DIRECT / USER_REQUEST / ADMIN_APPROVE / ADMIN_REJECT / BULK_UPLOAD / AUTO_RECOMMEND';
CREATE INDEX IDX_CHANGE_HISTORY_TARGET ON TB_CHANGE_HISTORY (TARGET_TYPE, CHANGE_DT DESC);

CREATE TABLE TB_CHANGE_HISTORY_DETAIL (
    CHANGE_ID         VARCHAR(40)     NOT NULL,
    SEQ               INTEGER         NOT NULL,
    TARGET_ID         VARCHAR(40),
    TARGET_NM         VARCHAR(200),
    DETAIL_TYPE       VARCHAR(20),
    PREV_VALUE        TEXT,
    CURR_VALUE        TEXT,
    REMARK            VARCHAR(500),
    CONSTRAINT PK_TB_CHANGE_HISTORY_DETAIL PRIMARY KEY (CHANGE_ID, SEQ)
);

COMMENT ON TABLE TB_CHANGE_HISTORY IS '변경 이력 마스터';
COMMENT ON COLUMN TB_CHANGE_HISTORY.CHANGE_TYPE IS 'INSERT, UPDATE, DELETE, BULK_INSERT';
COMMENT ON COLUMN TB_CHANGE_HISTORY.TARGET_TYPE IS 'WORD, TERM, DOMAIN, CODE, CODE_DATA';
COMMENT ON TABLE TB_CHANGE_HISTORY_DETAIL IS '변경 이력 상세 (일괄 등록 시)';

-- -------------------------------------------------------------
-- 8. TB_DATA_MODEL.MODEL_TYPE
--    데이터 모델의 논리/물리 구분 컬럼
--    (세션: 작업1 / 논리·물리 모델 구분 기능)
-- -------------------------------------------------------------
ALTER TABLE TB_DATA_MODEL ADD COLUMN IF NOT EXISTS MODEL_TYPE VARCHAR(10) DEFAULT 'PHYSICAL';
COMMENT ON COLUMN TB_DATA_MODEL.MODEL_TYPE IS '모델유형 (PHYSICAL: 물리, LOGICAL: 논리)';

-- -------------------------------------------------------------
-- 9. TB_WORD_DICT 시드 데이터 보강
--    DP 기반 단어분리 테스트용 + IT/금융/상거래 일반 단어 추가
--    (세션: DP기반 단어분리 / 시드 데이터 보강)
-- -------------------------------------------------------------
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('테슬라', 'Tesla', 'TSLA', '') ON CONFLICT (WORD_KOR) DO NOTHING;
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('코일', 'Coil', 'COIL', '') ON CONFLICT (WORD_KOR) DO NOTHING;
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('서버', 'Server', 'SRVR', '') ON CONFLICT (WORD_KOR) DO NOTHING;
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('데이터베이스', 'Database', 'DB', '') ON CONFLICT (WORD_KOR) DO NOTHING;
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('연결', 'Connection', 'CNNC', '') ON CONFLICT (WORD_KOR) DO NOTHING;
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('로그인', 'Login', 'LGIN', '') ON CONFLICT (WORD_KOR) DO NOTHING;
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('비밀번호', 'Password', 'PSWD', '') ON CONFLICT (WORD_KOR) DO NOTHING;
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('이메일', 'Email', 'EML', '') ON CONFLICT (WORD_KOR) DO NOTHING;
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('계좌', 'Account', 'ACNT', '') ON CONFLICT (WORD_KOR) DO NOTHING;
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('거래', 'Transaction', 'TRNS', '') ON CONFLICT (WORD_KOR) DO NOTHING;
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('잔액', 'Balance', 'BLNC', '') ON CONFLICT (WORD_KOR) DO NOTHING;
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('배송', 'Delivery', 'DLVR', '') ON CONFLICT (WORD_KOR) DO NOTHING;
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('주문', 'Order', 'ORDR', '') ON CONFLICT (WORD_KOR) DO NOTHING;
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('결제', 'Payment', 'PYMT', '') ON CONFLICT (WORD_KOR) DO NOTHING;
INSERT INTO TB_WORD_DICT (WORD_KOR, WORD_ENG, WORD_ABRV, DOMAIN_CLSF_NM) VALUES ('환불', 'Refund', 'RFND', '') ON CONFLICT (WORD_KOR) DO NOTHING;

-- -------------------------------------------------------------
-- 12. TB_BOARD
--     커뮤니티 게시판 (공지사항/QNA)
--     (세션: 승인프로세스 + 커뮤니티 기능 구현 시)
-- -------------------------------------------------------------
CREATE TABLE TB_BOARD (
    BOARD_ID      VARCHAR(40)  NOT NULL,
    BOARD_TYPE    VARCHAR(20)  NOT NULL,  -- NOTICE, QNA
    TITLE         VARCHAR(200) NOT NULL,
    CONTENT       TEXT,
    CRET_USER_ID  VARCHAR(40),
    CRET_DT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDT_DT       TIMESTAMP,
    VIEW_CNT      INTEGER DEFAULT 0,
    CONSTRAINT PK_TB_BOARD PRIMARY KEY (BOARD_ID)
);

-- -------------------------------------------------------------
-- 13. TB_BOARD_COMMENT
--     게시판 댓글
-- -------------------------------------------------------------
CREATE TABLE TB_BOARD_COMMENT (
    COMMENT_ID    VARCHAR(40) NOT NULL,
    BOARD_ID      VARCHAR(40) NOT NULL,
    CONTENT       TEXT,
    CRET_USER_ID  VARCHAR(40),
    CRET_DT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_BOARD_COMMENT PRIMARY KEY (COMMENT_ID)
);

-- -------------------------------------------------------------
-- 14. ndata.TB_DATA_SOURCE 연결 테스트 상태 컬럼 추가
--     데이터소스 수정 시 N 리셋, 연결 테스트 성공 시 Y 갱신
--     (세션: 2026-04-16 / 데이터소스 연결 정합성 설계)
-- -------------------------------------------------------------
ALTER TABLE ndata.tb_data_source ADD COLUMN CONN_TEST_YN CHAR(1) DEFAULT 'N';
ALTER TABLE ndata.tb_data_source ADD COLUMN CONN_TEST_DT TIMESTAMP;

-- -------------------------------------------------------------
-- 15. 단어/용어/도메인 중복 방어 UNIQUE 인덱스
--     코드 레벨 방어 + DB 레벨 이중 안전장치
--     (세션: 2026-04-16 / 중복 등록 방어 강화)
-- -------------------------------------------------------------
CREATE UNIQUE INDEX uix_word_nm ON quality.tb_word (WORD_NM);
CREATE UNIQUE INDEX uix_word_eng_abrv_nm ON quality.tb_word (WORD_ENG_ABRV_NM);
CREATE UNIQUE INDEX uix_terms_nm ON quality.tb_terms (TERMS_NM);
CREATE UNIQUE INDEX uix_domain_nm ON quality.tb_domain (DOMAIN_NM);

-- -------------------------------------------------------------
-- 16. 데이터모델 재설계 1단계 (설계문서 40/41)
--     - 논리모델 지원을 위해 DM_DS_ID NULL 허용
--     - 스냅샷 원천 구분용 CLCT_TYPE 컬럼
--     - 논리명(NM_KR)과 DB 코멘트(COMMENT) 분리
--     (세션: 2026-04-19 / 데이터모델 관리 재설계)
-- -------------------------------------------------------------
ALTER TABLE TB_DATA_MODEL ALTER COLUMN DM_DS_ID DROP NOT NULL;
ALTER TABLE TB_DATA_MODEL ADD COLUMN IF NOT EXISTS MODEL_TYPE VARCHAR(10) DEFAULT 'PHYSICAL';
COMMENT ON COLUMN TB_DATA_MODEL.MODEL_TYPE IS 'PHYSICAL(물리만), LOGICAL(논리만), BOTH(논리+물리)';

-- -------------------------------------------------------------
-- 17. TB_APRV_STATS 항목명 컬럼 (반려 물리삭제 후 이력 조회용)
-- -------------------------------------------------------------
ALTER TABLE TB_APRV_STATS ADD COLUMN IF NOT EXISTS REQ_ITEM_NM VARCHAR(200);
COMMENT ON COLUMN TB_APRV_STATS.REQ_ITEM_NM IS '요청 항목명 (반려 시 원본 삭제되므로 이력 보존용)';

ALTER TABLE TB_DATA_MODEL_CLCT ADD COLUMN IF NOT EXISTS CLCT_TYPE VARCHAR(20) DEFAULT 'DBMS';
COMMENT ON COLUMN TB_DATA_MODEL_CLCT.CLCT_TYPE IS '스냅샷 원천 (DBMS: 수집, MANUAL: 수동편집, ERWIN: ERwin 임포트)';

ALTER TABLE TB_DATA_MODEL_OBJ ADD COLUMN IF NOT EXISTS OBJ_COMMENT VARCHAR(500);
COMMENT ON COLUMN TB_DATA_MODEL_OBJ.OBJ_COMMENT IS 'DB에서 수집한 테이블 코멘트 원본 (수집 시 자동, 읽기 전용)';
COMMENT ON COLUMN TB_DATA_MODEL_OBJ.OBJ_NM_KR IS '테이블 논리명 (편집 가능). 최초 수집 시 OBJ_COMMENT 값 복사';

ALTER TABLE TB_DATA_MODEL_ATTR ADD COLUMN IF NOT EXISTS ATTR_COMMENT VARCHAR(500);
COMMENT ON COLUMN TB_DATA_MODEL_ATTR.ATTR_COMMENT IS 'DB에서 수집한 컬럼 코멘트 원본 (수집 시 자동, 읽기 전용)';
COMMENT ON COLUMN TB_DATA_MODEL_ATTR.ATTR_NM_KR IS '컬럼 논리명 (편집 가능). 최초 수집 시 ATTR_COMMENT 값 복사';

-- ===========================================================
-- 2026-04-20: CLCT 폐기 이관 마무리 — 44번 설계 스펙 이행
-- (이전 세션이 PK는 DM_ID로 바꿨지만 DM_CLCT_ID 컬럼 DROP은 누락)
-- ===========================================================
ALTER TABLE TB_DATA_MODEL_OBJ  DROP COLUMN IF EXISTS DM_CLCT_ID;
ALTER TABLE TB_DATA_MODEL_ATTR DROP COLUMN IF EXISTS DM_CLCT_ID;

-- ===========================================================
-- 2026-04-21: 논리 모델(LOGICAL) 지원 — OBJ_OWNER NOT NULL 제거
-- 배경:
--   논리 모델은 DBMS 스키마(OWNER)가 없어서 사용자 편집 시 OBJ_OWNER를
--   NULL로 저장해야 하는데, 기존 initdb 스키마는
--   tb_data_model_attr.obj_owner 가 NOT NULL DEFAULT '' 이라 INSERT 실패
--   (null value in column "obj_owner" ... violates not-null constraint).
-- 조치:
--   OBJ/ATTR 양쪽 OBJ_OWNER 의 NOT NULL 제약 해제. 기본값 ''도 의미 없어 유지만.
--   수집(물리) 쪽은 여전히 OWNER 를 채우므로 영향 없음.
-- 각 PC 로컬 DB 적용은 52번 마이그레이션 파일에서 동일 문장으로 포함.
-- ===========================================================
ALTER TABLE TB_DATA_MODEL_OBJ  ALTER COLUMN OBJ_OWNER DROP NOT NULL;
ALTER TABLE TB_DATA_MODEL_ATTR ALTER COLUMN OBJ_OWNER DROP NOT NULL;

-- ===========================================================
-- 2026-04-21: CLCT 폐기 확장 — INDEX / CONSTRAINT 도 DM_ID + UPSERT 로 정리
-- 배경:
--   49번 영향도 분석에서 TB_DATA_MODEL_INDEX / TB_DATA_MODEL_CONSTRAINT 는
--   "의도적 유지"로 표기되어 있었으나, 구조 진단 결과는 이미
--   TB_STRUCT_DIAG_INDEX_DETAIL / TB_STRUCT_DIAG_CONSTRAINT_DETAIL 에
--   스냅샷이 별도 저장되므로 원본이 회차 기반일 기술적 이유가 없음.
--   OBJ/ATTR 와 동일한 방식(DM_ID + 자연키 PK + UPSERT + soft-delete)으로 정리.
--
-- 자연키:
--   INDEX      — (DM_ID, OBJ_OWNER, TABLE_NM, INDEX_NM, COLUMN_POS)
--   CONSTRAINT — (DM_ID, OBJ_OWNER, TABLE_NM, CONSTRAINT_NM, COLUMN_POS)
--
-- OBJ_OWNER 는 PostgreSQL PK 제약상 NULL 허용 불가 → 빈 문자열('')로 치환.
-- 수집 데이터는 OBJ_OWNER 를 항상 채우므로 영향 없음.
-- ===========================================================

-- INDEX ------------------------------------------------------
ALTER TABLE TB_DATA_MODEL_INDEX ADD COLUMN IF NOT EXISTS USE_YN     CHAR(1)     DEFAULT 'Y';
ALTER TABLE TB_DATA_MODEL_INDEX ADD COLUMN IF NOT EXISTS DELETED_DT VARCHAR(14);

UPDATE TB_DATA_MODEL_INDEX SET OBJ_OWNER = '' WHERE OBJ_OWNER IS NULL;

-- 중복 정리: 같은 자연키 조합 중 가장 최신 수집건 1개만 남김
DELETE FROM TB_DATA_MODEL_INDEX t1
USING TB_DATA_MODEL_INDEX t2,
      TB_DATA_MODEL_CLCT c1,
      TB_DATA_MODEL_CLCT c2
WHERE c1.DM_CLCT_ID = t1.DM_CLCT_ID
  AND c2.DM_CLCT_ID = t2.DM_CLCT_ID
  AND t1.DM_ID      = t2.DM_ID
  AND COALESCE(t1.OBJ_OWNER,'') = COALESCE(t2.OBJ_OWNER,'')
  AND t1.TABLE_NM   = t2.TABLE_NM
  AND t1.INDEX_NM   = t2.INDEX_NM
  AND t1.COLUMN_POS = t2.COLUMN_POS
  AND (COALESCE(c1.CLCT_END_DT,'') < COALESCE(c2.CLCT_END_DT,'')
       OR (COALESCE(c1.CLCT_END_DT,'') = COALESCE(c2.CLCT_END_DT,'') AND t1.SEQ < t2.SEQ));

ALTER TABLE TB_DATA_MODEL_INDEX ALTER COLUMN DM_ID     SET NOT NULL;
ALTER TABLE TB_DATA_MODEL_INDEX ALTER COLUMN OBJ_OWNER SET NOT NULL;
ALTER TABLE TB_DATA_MODEL_INDEX ALTER COLUMN TABLE_NM  SET NOT NULL;
ALTER TABLE TB_DATA_MODEL_INDEX ALTER COLUMN INDEX_NM  SET NOT NULL;
ALTER TABLE TB_DATA_MODEL_INDEX ALTER COLUMN COLUMN_POS SET NOT NULL;

ALTER TABLE TB_DATA_MODEL_INDEX DROP CONSTRAINT IF EXISTS PK_TB_DATA_MODEL_INDEX;
ALTER TABLE TB_DATA_MODEL_INDEX ADD  CONSTRAINT PK_TB_DATA_MODEL_INDEX
    PRIMARY KEY (DM_ID, OBJ_OWNER, TABLE_NM, INDEX_NM, COLUMN_POS);

ALTER TABLE TB_DATA_MODEL_INDEX DROP COLUMN IF EXISTS DM_CLCT_ID;
ALTER TABLE TB_DATA_MODEL_INDEX DROP COLUMN IF EXISTS SEQ;

COMMENT ON COLUMN TB_DATA_MODEL_INDEX.USE_YN     IS '사용 여부 (Y/N). soft-delete 대상은 N';
COMMENT ON COLUMN TB_DATA_MODEL_INDEX.DELETED_DT IS 'soft-delete 시각 (YYYYMMDDHH24MISS)';

-- CONSTRAINT -------------------------------------------------
ALTER TABLE TB_DATA_MODEL_CONSTRAINT ADD COLUMN IF NOT EXISTS USE_YN     CHAR(1)     DEFAULT 'Y';
ALTER TABLE TB_DATA_MODEL_CONSTRAINT ADD COLUMN IF NOT EXISTS DELETED_DT VARCHAR(14);

UPDATE TB_DATA_MODEL_CONSTRAINT SET OBJ_OWNER = '' WHERE OBJ_OWNER IS NULL;

DELETE FROM TB_DATA_MODEL_CONSTRAINT t1
USING TB_DATA_MODEL_CONSTRAINT t2,
      TB_DATA_MODEL_CLCT c1,
      TB_DATA_MODEL_CLCT c2
WHERE c1.DM_CLCT_ID = t1.DM_CLCT_ID
  AND c2.DM_CLCT_ID = t2.DM_CLCT_ID
  AND t1.DM_ID           = t2.DM_ID
  AND COALESCE(t1.OBJ_OWNER,'') = COALESCE(t2.OBJ_OWNER,'')
  AND t1.TABLE_NM        = t2.TABLE_NM
  AND t1.CONSTRAINT_NM   = t2.CONSTRAINT_NM
  AND t1.COLUMN_POS      = t2.COLUMN_POS
  AND (COALESCE(c1.CLCT_END_DT,'') < COALESCE(c2.CLCT_END_DT,'')
       OR (COALESCE(c1.CLCT_END_DT,'') = COALESCE(c2.CLCT_END_DT,'') AND t1.SEQ < t2.SEQ));

ALTER TABLE TB_DATA_MODEL_CONSTRAINT ALTER COLUMN DM_ID         SET NOT NULL;
ALTER TABLE TB_DATA_MODEL_CONSTRAINT ALTER COLUMN OBJ_OWNER     SET NOT NULL;
ALTER TABLE TB_DATA_MODEL_CONSTRAINT ALTER COLUMN TABLE_NM      SET NOT NULL;
ALTER TABLE TB_DATA_MODEL_CONSTRAINT ALTER COLUMN CONSTRAINT_NM SET NOT NULL;
ALTER TABLE TB_DATA_MODEL_CONSTRAINT ALTER COLUMN COLUMN_POS    SET NOT NULL;

ALTER TABLE TB_DATA_MODEL_CONSTRAINT DROP CONSTRAINT IF EXISTS PK_TB_DATA_MODEL_CONSTRAINT;
ALTER TABLE TB_DATA_MODEL_CONSTRAINT ADD  CONSTRAINT PK_TB_DATA_MODEL_CONSTRAINT
    PRIMARY KEY (DM_ID, OBJ_OWNER, TABLE_NM, CONSTRAINT_NM, COLUMN_POS);

ALTER TABLE TB_DATA_MODEL_CONSTRAINT DROP COLUMN IF EXISTS DM_CLCT_ID;
ALTER TABLE TB_DATA_MODEL_CONSTRAINT DROP COLUMN IF EXISTS SEQ;

COMMENT ON COLUMN TB_DATA_MODEL_CONSTRAINT.USE_YN     IS '사용 여부 (Y/N). soft-delete 대상은 N';
COMMENT ON COLUMN TB_DATA_MODEL_CONSTRAINT.DELETED_DT IS 'soft-delete 시각 (YYYYMMDDHH24MISS)';


-- ============================================================================
-- 2026-04-24 진단 스케줄러 (65번 문서)
-- ============================================================================

-- TB_DIAG_SCHEDULE: 진단 스케줄 정의
CREATE TABLE IF NOT EXISTS TB_DIAG_SCHEDULE (
    SCHEDULE_ID         VARCHAR(40)  NOT NULL,
    SCHEDULE_NM         VARCHAR(200) NOT NULL,
    DIAG_TYPE           VARCHAR(20)  NOT NULL,            -- STANDARD | STRUCT | BOTH
    DATA_MODEL_ID       VARCHAR(40)  NOT NULL,
    SCHEDULE_TYPE       VARCHAR(20)  DEFAULT 'SIMPLE',    -- SIMPLE | CRON
    REPEAT_CYCLE        VARCHAR(20),                      -- DAILY | WEEKLY | MONTHLY
    REPEAT_TIME         VARCHAR(5),                       -- "HH:mm"
    REPEAT_DAY_OF_WEEK  INTEGER,                          -- 1(월)~7(일)
    REPEAT_DAY_OF_MONTH INTEGER,                          -- 1~28
    CRON_EXPR           VARCHAR(100),                     -- SCHEDULE_TYPE='CRON'
    USE_YN              CHAR(1)      DEFAULT 'Y',         -- 활성/비활성
    LAST_EXEC_DT        TIMESTAMP,
    LAST_EXEC_STATUS    VARCHAR(20),                      -- DONE | ERROR | SKIPPED
    LAST_EXEC_LOG_ID    VARCHAR(40),
    CRET_USER_ID        VARCHAR(40),
    CRET_DT             TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDT_USER_ID        VARCHAR(40),
    UPDT_DT             TIMESTAMP,
    CONSTRAINT PK_TB_DIAG_SCHEDULE PRIMARY KEY (SCHEDULE_ID)
);
CREATE INDEX IF NOT EXISTS IX_DIAG_SCHEDULE_ACTIVE
    ON TB_DIAG_SCHEDULE (USE_YN, DATA_MODEL_ID);

COMMENT ON TABLE TB_DIAG_SCHEDULE IS '진단 스케줄 정의 (65번 문서)';
COMMENT ON COLUMN TB_DIAG_SCHEDULE.DIAG_TYPE       IS 'STANDARD | STRUCT | BOTH';
COMMENT ON COLUMN TB_DIAG_SCHEDULE.SCHEDULE_TYPE   IS 'SIMPLE | CRON';
COMMENT ON COLUMN TB_DIAG_SCHEDULE.USE_YN          IS '활성/비활성 토글';
COMMENT ON COLUMN TB_DIAG_SCHEDULE.LAST_EXEC_LOG_ID IS '최근 실행 LOG 참조 (빠른 조회용)';

-- TB_DIAG_SCHEDULE_LOG: 실행 이력
CREATE TABLE IF NOT EXISTS TB_DIAG_SCHEDULE_LOG (
    LOG_ID               VARCHAR(40)  NOT NULL,
    SCHEDULE_ID          VARCHAR(40)  NOT NULL,
    EXEC_DT              TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    EXEC_END_DT          TIMESTAMP,
    EXEC_STATUS          VARCHAR(20),                     -- RUNNING | DONE | ERROR | SKIPPED
    TRIGGER_TYPE         VARCHAR(20),                     -- AUTO | MANUAL
    DIAG_TYPE            VARCHAR(20),
    DIAG_JOB_ID          VARCHAR(40),                     -- STANDARD → TB_DIAG_JOB
    STRUCT_DIAG_ID       VARCHAR(40),                     -- STRUCT → TB_STRUCT_DIAG_HISTORY
    SCHEDULE_NM_SNAPSHOT VARCHAR(200),                    -- 스케줄 삭제 대비
    ERROR_MSG            VARCHAR(2000),
    EXEC_DURATION_SEC    INTEGER,
    CONSTRAINT PK_TB_DIAG_SCHEDULE_LOG PRIMARY KEY (LOG_ID)
);
CREATE INDEX IF NOT EXISTS IX_DIAG_SCHEDULE_LOG_SCHEDULE
    ON TB_DIAG_SCHEDULE_LOG (SCHEDULE_ID, EXEC_DT DESC);

COMMENT ON TABLE TB_DIAG_SCHEDULE_LOG IS '진단 스케줄 실행 이력 (65번 문서)';
COMMENT ON COLUMN TB_DIAG_SCHEDULE_LOG.TRIGGER_TYPE         IS 'AUTO(스케줄러) | MANUAL(runNow)';
COMMENT ON COLUMN TB_DIAG_SCHEDULE_LOG.SCHEDULE_NM_SNAPSHOT IS '실행 당시 스케줄명. 원 스케줄 삭제 후에도 이력에서 조회 가능';
COMMENT ON COLUMN TB_DIAG_SCHEDULE_LOG.ERROR_MSG            IS '실패 원인 요약. prefix 예: [CONFIG], [DB], [TIMEOUT], [DATA_NOT_FOUND], [UNKNOWN]';

-- ==========================================================================
-- 67번 데이터 품질 진단 (값 진단 + 업무 규칙 진단) — 2026-04-28 추가
-- ==========================================================================

-- 67-1. 룰 정의
CREATE TABLE IF NOT EXISTS TB_QUAL_RULE (
    RULE_ID         VARCHAR(40) NOT NULL,
    DM_ID           VARCHAR(40) NOT NULL,
    OBJ_NM          VARCHAR(100),
    ATTR_NM         VARCHAR(100),
    DOMAIN_ID       VARCHAR(40),
    RULE_NM         VARCHAR(200) NOT NULL,
    RULE_TYPE       VARCHAR(20)  NOT NULL,
    RULE_PARAMS     TEXT,
    SEVERITY        VARCHAR(10)  NOT NULL DEFAULT 'WARN',
    USE_YN          CHAR(1)      NOT NULL DEFAULT 'Y',
    INCREMENTAL_COL VARCHAR(100),
    EST_COST        VARCHAR(10),
    DESCR           TEXT,
    CRET_USER_ID    VARCHAR(40),
    CRET_DT         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDT_USER_ID    VARCHAR(40),
    UPDT_DT         TIMESTAMP,
    CONSTRAINT PK_TB_QUAL_RULE PRIMARY KEY (RULE_ID)
);
CREATE INDEX IF NOT EXISTS IX_QUAL_RULE_DM ON TB_QUAL_RULE (DM_ID, USE_YN);

-- 67-2. 진단 실행 이력 (값/룰 공용)
CREATE TABLE IF NOT EXISTS TB_QUAL_DIAG_HISTORY (
    DIAG_ID          VARCHAR(40) NOT NULL,
    DM_ID            VARCHAR(40) NOT NULL,
    DIAG_TYPE        VARCHAR(10) NOT NULL,
    DIAG_DT          TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    END_DT           TIMESTAMP,
    STATUS           VARCHAR(20) NOT NULL DEFAULT 'READY',
    TARGET_OBJ_LIST  TEXT,
    SAMPLE_RATE      INTEGER     DEFAULT 100,
    INCREMENTAL_YN   CHAR(1)     DEFAULT 'N',
    LAST_DIAG_DT     TIMESTAMP,
    TOTAL_RULES      INTEGER     DEFAULT 0,
    TOTAL_COLS       INTEGER     DEFAULT 0,
    TOTAL_VIOLATIONS INTEGER     DEFAULT 0,
    EXEC_USER_ID     VARCHAR(40),
    ERROR_MSG        TEXT,
    CONSTRAINT PK_TB_QUAL_DIAG_HISTORY PRIMARY KEY (DIAG_ID)
);
CREATE INDEX IF NOT EXISTS IX_QUAL_DIAG_DM_TYPE
    ON TB_QUAL_DIAG_HISTORY (DM_ID, DIAG_TYPE, DIAG_DT DESC);

-- 67-3. 값 프로파일링 결과 (UPSERT, 직전 1회분만 보존)
CREATE TABLE IF NOT EXISTS TB_QUAL_PROFILE_RESULT (
    DM_ID         VARCHAR(40)  NOT NULL,
    OBJ_NM        VARCHAR(100) NOT NULL,
    ATTR_NM       VARCHAR(100) NOT NULL,
    DIAG_ID       VARCHAR(40)  NOT NULL,
    TOTAL_CNT     BIGINT,
    NULL_CNT      BIGINT,
    DISTINCT_CNT  BIGINT,
    EMPTY_CNT     BIGINT,
    MIN_VAL       VARCHAR(200),
    MAX_VAL       VARCHAR(200),
    AVG_VAL       NUMERIC(20,4),
    STD_VAL       NUMERIC(20,4),
    MIN_LEN       INTEGER,
    MAX_LEN       INTEGER,
    TOP_VALUES    TEXT,
    UPDATED_DT    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_QUAL_PROFILE_RESULT PRIMARY KEY (DM_ID, OBJ_NM, ATTR_NM)
);

-- 67-4. 룰 진단 결과
CREATE TABLE IF NOT EXISTS TB_QUAL_RULE_RESULT (
    DIAG_ID        VARCHAR(40) NOT NULL,
    RULE_ID        VARCHAR(40) NOT NULL,
    OBJ_NM         VARCHAR(100),
    ATTR_NM        VARCHAR(100),
    TOTAL_CNT      BIGINT,
    VIOLATION_CNT  BIGINT,
    VIOLATION_RATE NUMERIC(7,4),
    SAMPLE_CNT     INTEGER,
    ERROR_MSG      TEXT,
    CONSTRAINT PK_TB_QUAL_RULE_RESULT PRIMARY KEY (DIAG_ID, RULE_ID, COALESCE(OBJ_NM, ''), COALESCE(ATTR_NM, ''))
);
-- (PostgreSQL: COALESCE in PK 안 됨 — alternative 적용)
-- 위 PK 가 PostgreSQL 13 에서 동작 안 하므로 surrogate seq 사용
DROP TABLE IF EXISTS TB_QUAL_RULE_RESULT;
CREATE TABLE IF NOT EXISTS TB_QUAL_RULE_RESULT (
    DIAG_ID        VARCHAR(40)  NOT NULL,
    RULE_ID        VARCHAR(40)  NOT NULL,
    OBJ_NM         VARCHAR(100) NOT NULL DEFAULT '',
    ATTR_NM        VARCHAR(100) NOT NULL DEFAULT '',
    TOTAL_CNT      BIGINT,
    VIOLATION_CNT  BIGINT,
    VIOLATION_RATE NUMERIC(7,4),
    SAMPLE_CNT     INTEGER,
    ERROR_MSG      TEXT,
    CONSTRAINT PK_TB_QUAL_RULE_RESULT PRIMARY KEY (DIAG_ID, RULE_ID, OBJ_NM, ATTR_NM)
);

-- 67-5. 위반 샘플 (룰별 PK 컬럼만 N개)
CREATE TABLE IF NOT EXISTS TB_QUAL_VIOLATION_SAMPLE (
    DIAG_ID        VARCHAR(40)  NOT NULL,
    RULE_ID        VARCHAR(40)  NOT NULL,
    OBJ_NM         VARCHAR(100) NOT NULL DEFAULT '',
    ATTR_NM        VARCHAR(100) NOT NULL DEFAULT '',
    SEQ            INTEGER      NOT NULL,
    PK_VALUES      TEXT,
    VIOLATING_VAL  VARCHAR(500),
    CONSTRAINT PK_TB_QUAL_VIOLATION_SAMPLE PRIMARY KEY (DIAG_ID, RULE_ID, OBJ_NM, ATTR_NM, SEQ)
);

-- 67-6. 룰 카탈로그 (템플릿)
CREATE TABLE IF NOT EXISTS TB_QUAL_RULE_CATALOG (
    CATALOG_ID   VARCHAR(40)  NOT NULL,
    CATALOG_NM   VARCHAR(200) NOT NULL,
    RULE_TYPE    VARCHAR(20),
    RULE_PARAMS  TEXT,
    CATEGORY     VARCHAR(50),
    DESCR        TEXT,
    USE_YN       CHAR(1)      DEFAULT 'Y',
    CONSTRAINT PK_TB_QUAL_RULE_CATALOG PRIMARY KEY (CATALOG_ID)
);

COMMENT ON TABLE TB_QUAL_RULE             IS '데이터 품질 진단 — 룰 정의 (67번 §4.2)';
COMMENT ON TABLE TB_QUAL_DIAG_HISTORY     IS '데이터 품질 진단 실행 이력 (값/룰 공용, 67번 §5)';
COMMENT ON TABLE TB_QUAL_PROFILE_RESULT   IS '값 프로파일링 결과 (UPSERT, 직전 1회분만)';
COMMENT ON TABLE TB_QUAL_RULE_RESULT      IS '업무 규칙 진단 결과 (DIAG_ID + RULE_ID + 도메인 룰의 경우 OBJ/ATTR)';
COMMENT ON TABLE TB_QUAL_VIOLATION_SAMPLE IS '위반 샘플 행 (PK + 위반값, 룰당 기본 100건)';
COMMENT ON TABLE TB_QUAL_RULE_CATALOG     IS '룰 템플릿 (이메일/주민번호 등 표준 정규식)';

-- ============================================================
-- 79번 진단 대상 제외 관리 (2026-05-04)
-- TB_DATA_MODEL_OBJ + TB_DATA_MODEL_ATTR 에 진단 종류별 TARGET_YN + REASON 추가
-- DEFAULT 'Y' (기존 데이터 회귀 없음)
-- ============================================================

-- TB_DATA_MODEL_OBJ
ALTER TABLE TB_DATA_MODEL_OBJ ADD COLUMN IF NOT EXISTS STND_DIAG_TARGET_YN     VARCHAR(1) DEFAULT 'Y';
ALTER TABLE TB_DATA_MODEL_OBJ ADD COLUMN IF NOT EXISTS STND_DIAG_TARGET_REASON VARCHAR(200);
ALTER TABLE TB_DATA_MODEL_OBJ ADD COLUMN IF NOT EXISTS STRUCT_DIAG_TARGET_YN     VARCHAR(1) DEFAULT 'Y';
ALTER TABLE TB_DATA_MODEL_OBJ ADD COLUMN IF NOT EXISTS STRUCT_DIAG_TARGET_REASON VARCHAR(200);
ALTER TABLE TB_DATA_MODEL_OBJ ADD COLUMN IF NOT EXISTS QUAL_DIAG_TARGET_YN     VARCHAR(1) DEFAULT 'Y';
ALTER TABLE TB_DATA_MODEL_OBJ ADD COLUMN IF NOT EXISTS QUAL_DIAG_TARGET_REASON VARCHAR(200);
ALTER TABLE TB_DATA_MODEL_OBJ ADD COLUMN IF NOT EXISTS DIAG_TARGET_UPDT_USER_ID VARCHAR(50);
ALTER TABLE TB_DATA_MODEL_OBJ ADD COLUMN IF NOT EXISTS DIAG_TARGET_UPDT_DT      VARCHAR(14);

COMMENT ON COLUMN TB_DATA_MODEL_OBJ.STND_DIAG_TARGET_YN     IS '표준 진단 대상 (Y=대상/N=제외, DEFAULT Y) — 79번';
COMMENT ON COLUMN TB_DATA_MODEL_OBJ.STND_DIAG_TARGET_REASON IS '표준 OFF 사유 (선택)';
COMMENT ON COLUMN TB_DATA_MODEL_OBJ.STRUCT_DIAG_TARGET_YN   IS '구조 변경 진단 대상';
COMMENT ON COLUMN TB_DATA_MODEL_OBJ.STRUCT_DIAG_TARGET_REASON IS '구조 OFF 사유';
COMMENT ON COLUMN TB_DATA_MODEL_OBJ.QUAL_DIAG_TARGET_YN     IS '품질 진단 대상 (매퍼 통합은 67/70번 정식 구현 후 — 핸드오버 필수)';
COMMENT ON COLUMN TB_DATA_MODEL_OBJ.QUAL_DIAG_TARGET_REASON IS '품질 OFF 사유';
COMMENT ON COLUMN TB_DATA_MODEL_OBJ.DIAG_TARGET_UPDT_USER_ID IS '진단 대상 마지막 변경자';
COMMENT ON COLUMN TB_DATA_MODEL_OBJ.DIAG_TARGET_UPDT_DT      IS '진단 대상 마지막 변경일시 (YYYYMMDDHH24MISS)';

-- TB_DATA_MODEL_ATTR
ALTER TABLE TB_DATA_MODEL_ATTR ADD COLUMN IF NOT EXISTS STND_DIAG_TARGET_YN     VARCHAR(1) DEFAULT 'Y';
ALTER TABLE TB_DATA_MODEL_ATTR ADD COLUMN IF NOT EXISTS STND_DIAG_TARGET_REASON VARCHAR(200);
ALTER TABLE TB_DATA_MODEL_ATTR ADD COLUMN IF NOT EXISTS STRUCT_DIAG_TARGET_YN     VARCHAR(1) DEFAULT 'Y';
ALTER TABLE TB_DATA_MODEL_ATTR ADD COLUMN IF NOT EXISTS STRUCT_DIAG_TARGET_REASON VARCHAR(200);
ALTER TABLE TB_DATA_MODEL_ATTR ADD COLUMN IF NOT EXISTS QUAL_DIAG_TARGET_YN     VARCHAR(1) DEFAULT 'Y';
ALTER TABLE TB_DATA_MODEL_ATTR ADD COLUMN IF NOT EXISTS QUAL_DIAG_TARGET_REASON VARCHAR(200);
ALTER TABLE TB_DATA_MODEL_ATTR ADD COLUMN IF NOT EXISTS DIAG_TARGET_UPDT_USER_ID VARCHAR(50);
ALTER TABLE TB_DATA_MODEL_ATTR ADD COLUMN IF NOT EXISTS DIAG_TARGET_UPDT_DT      VARCHAR(14);

COMMENT ON COLUMN TB_DATA_MODEL_ATTR.STND_DIAG_TARGET_YN     IS '표준 진단 대상 (Y=대상/N=제외, DEFAULT Y) — 79번';
COMMENT ON COLUMN TB_DATA_MODEL_ATTR.STND_DIAG_TARGET_REASON IS '표준 OFF 사유';
COMMENT ON COLUMN TB_DATA_MODEL_ATTR.STRUCT_DIAG_TARGET_YN   IS '구조 변경 진단 대상';
COMMENT ON COLUMN TB_DATA_MODEL_ATTR.STRUCT_DIAG_TARGET_REASON IS '구조 OFF 사유';
COMMENT ON COLUMN TB_DATA_MODEL_ATTR.QUAL_DIAG_TARGET_YN     IS '품질 진단 대상 (매퍼 통합 보류)';
COMMENT ON COLUMN TB_DATA_MODEL_ATTR.QUAL_DIAG_TARGET_REASON IS '품질 OFF 사유';
COMMENT ON COLUMN TB_DATA_MODEL_ATTR.DIAG_TARGET_UPDT_USER_ID IS '진단 대상 마지막 변경자';
COMMENT ON COLUMN TB_DATA_MODEL_ATTR.DIAG_TARGET_UPDT_DT      IS '진단 대상 마지막 변경일시';

-- ==========================================================================
-- 2026-05-06 PC1 — DDL 누락 분 보강 (코드 역산)
-- 5-02 (5a105b8) 커밋 메시지엔 9 신규 테이블 적혀있는데 실제 DDL 파일엔 6개만 있고
-- TB_DOMAIN_RULE / TB_QUAL_COL_RULE / TB_QUAL_PROFILE_HISTORY 가 빠져있음.
-- VO + 매퍼 INSERT/UPSERT 로부터 컬럼·타입·PK 추출. 다른 PC dataq-db 와 정확히
-- 같은 정의가 아닐 위험은 있으나, 매퍼 쿼리가 동일하게 동작하도록 컬럼명/PK는
-- 매퍼 기준으로 작성. 차후 실제 PC2 DB 의 \d 결과와 비교 권장.
-- ==========================================================================

-- TB_DOMAIN_RULE (도메인별 룰 정의 — 1:N)
CREATE TABLE IF NOT EXISTS TB_DOMAIN_RULE (
    DOMAIN_RULE_ID  VARCHAR(40)  NOT NULL,
    DOMAIN_ID       VARCHAR(40)  NOT NULL,
    RULE_NM         VARCHAR(200) NOT NULL,
    RULE_TYPE       VARCHAR(20)  NOT NULL,    -- REGEX/RANGE/LENGTH/ENUM
    RULE_PARAMS     TEXT,                     -- JSON
    SORT_ORD        INTEGER      DEFAULT 1,
    USE_YN          VARCHAR(1)   DEFAULT 'Y',
    DESCR           VARCHAR(500),
    CRET_USER_ID    VARCHAR(50),
    CRET_DT         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDT_USER_ID    VARCHAR(50),
    UPDT_DT         TIMESTAMP,
    CONSTRAINT PK_TB_DOMAIN_RULE PRIMARY KEY (DOMAIN_RULE_ID)
);
CREATE INDEX IF NOT EXISTS ix_domain_rule_domain ON TB_DOMAIN_RULE (DOMAIN_ID, USE_YN);
COMMENT ON TABLE TB_DOMAIN_RULE IS '도메인별 룰 정의 (1:N) — 70번';

-- TB_QUAL_COL_RULE (컬럼-룰 매핑: 도메인룰 OR 사용자커스텀룰 OR 진단제외)
CREATE TABLE IF NOT EXISTS TB_QUAL_COL_RULE (
    DM_ID           VARCHAR(40)  NOT NULL,
    OBJ_NM          VARCHAR(100) NOT NULL,
    ATTR_NM         VARCHAR(100) NOT NULL,
    DOMAIN_RULE_ID  VARCHAR(40),
    CUSTOM_RULE_ID  VARCHAR(40),
    EXCLUDE_YN      VARCHAR(1)   DEFAULT 'N',
    UPDT_USER_ID    VARCHAR(50),
    UPDT_DT         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_QUAL_COL_RULE PRIMARY KEY (DM_ID, OBJ_NM, ATTR_NM)
);
COMMENT ON TABLE TB_QUAL_COL_RULE IS '컬럼별 룰 매핑 (도메인룰 우선 / 커스텀 / 제외) — 70번';

-- TB_QUAL_PROFILE_HISTORY (값 프로파일 시계열 누적)
CREATE TABLE IF NOT EXISTS TB_QUAL_PROFILE_HISTORY (
    DIAG_ID         VARCHAR(40)  NOT NULL,
    DM_ID           VARCHAR(40)  NOT NULL,
    OBJ_NM          VARCHAR(100) NOT NULL,
    ATTR_NM         VARCHAR(100) NOT NULL,
    TOTAL_CNT       BIGINT,
    NULL_CNT        BIGINT,
    DISTINCT_CNT    BIGINT,
    EMPTY_CNT       BIGINT,
    MIN_VAL         VARCHAR(200),
    MAX_VAL         VARCHAR(200),
    AVG_VAL         NUMERIC(20,4),
    STD_VAL         NUMERIC(20,4),
    MIN_LEN         INTEGER,
    MAX_LEN         INTEGER,
    DIAG_DT         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_QUAL_PROFILE_HISTORY PRIMARY KEY (DIAG_ID, DM_ID, OBJ_NM, ATTR_NM)
);
CREATE INDEX IF NOT EXISTS ix_qual_profile_history_attr ON TB_QUAL_PROFILE_HISTORY (DM_ID, OBJ_NM, ATTR_NM, DIAG_DT DESC);
COMMENT ON TABLE TB_QUAL_PROFILE_HISTORY IS '값 프로파일 시계열 누적 (MIN/MAX/AVG/STD/LEN/COUNT) — 70번';
