-- Oracle 테스트 스키마 (50개 테이블)
-- TESTUSER 스키마에서 실행

-- ===== 1. 인사 (HR) =====
CREATE TABLE TB_EMPLOYEE (
  EMP_ID VARCHAR2(20) PRIMARY KEY,
  EMP_NM VARCHAR2(100) NOT NULL,
  EMP_ENG_NM VARCHAR2(100),
  BIRTH_DT DATE,
  GENDER_CD CHAR(1),
  PHONE_NO VARCHAR2(20),
  EMAIL VARCHAR2(200),
  HIRE_DT DATE NOT NULL,
  RESIGN_DT DATE,
  DEPT_CD VARCHAR2(10),
  POSITION_CD VARCHAR2(10),
  STATUS_CD VARCHAR2(10) DEFAULT 'ACTIVE'
);

CREATE TABLE TB_DEPARTMENT (
  DEPT_CD VARCHAR2(10) PRIMARY KEY,
  DEPT_NM VARCHAR2(100) NOT NULL,
  DEPT_ENG_NM VARCHAR2(100),
  UPPER_DEPT_CD VARCHAR2(10),
  DEPT_LVL NUMBER(2),
  SORT_ORD NUMBER(5),
  USE_YN CHAR(1) DEFAULT 'Y'
);

CREATE TABLE TB_POSITION (
  POSITION_CD VARCHAR2(10) PRIMARY KEY,
  POSITION_NM VARCHAR2(50) NOT NULL,
  POSITION_LVL NUMBER(2),
  SORT_ORD NUMBER(5)
);

CREATE TABLE TB_EMP_HISTORY (
  HIST_ID VARCHAR2(20) PRIMARY KEY,
  EMP_ID VARCHAR2(20) NOT NULL,
  CHANGE_TYPE VARCHAR2(20),
  BEFORE_VAL VARCHAR2(200),
  AFTER_VAL VARCHAR2(200),
  CHANGE_DT DATE,
  CHANGE_USER_ID VARCHAR2(20)
);

CREATE TABLE TB_ATTENDANCE (
  ATTEND_ID VARCHAR2(20) PRIMARY KEY,
  EMP_ID VARCHAR2(20) NOT NULL,
  ATTEND_DT DATE NOT NULL,
  CHECK_IN_TIME VARCHAR2(6),
  CHECK_OUT_TIME VARCHAR2(6),
  ATTEND_TYPE VARCHAR2(10),
  REMARK VARCHAR2(500)
);

-- ===== 2. 급여 (PAYROLL) =====
CREATE TABLE TB_SALARY (
  SALARY_ID VARCHAR2(20) PRIMARY KEY,
  EMP_ID VARCHAR2(20) NOT NULL,
  PAY_YEAR VARCHAR2(4) NOT NULL,
  PAY_MONTH VARCHAR2(2) NOT NULL,
  BASE_SALARY NUMBER(15) DEFAULT 0,
  BONUS_AMT NUMBER(15) DEFAULT 0,
  DEDUCTION_AMT NUMBER(15) DEFAULT 0,
  NET_SALARY NUMBER(15) DEFAULT 0,
  PAY_DT DATE
);

CREATE TABLE TB_SALARY_ITEM (
  ITEM_ID VARCHAR2(20) PRIMARY KEY,
  SALARY_ID VARCHAR2(20) NOT NULL,
  ITEM_CD VARCHAR2(20),
  ITEM_NM VARCHAR2(100),
  ITEM_AMT NUMBER(15) DEFAULT 0,
  ITEM_TYPE VARCHAR2(10)
);

CREATE TABLE TB_TAX_INFO (
  TAX_ID VARCHAR2(20) PRIMARY KEY,
  EMP_ID VARCHAR2(20) NOT NULL,
  TAX_YEAR VARCHAR2(4),
  INCOME_TAX NUMBER(15),
  LOCAL_TAX NUMBER(15),
  HEALTH_INS NUMBER(15),
  PENSION NUMBER(15)
);

-- ===== 3. 조직 (ORG) =====
CREATE TABLE TB_COMPANY (
  COMPANY_CD VARCHAR2(10) PRIMARY KEY,
  COMPANY_NM VARCHAR2(200) NOT NULL,
  BIZ_NO VARCHAR2(20),
  CEO_NM VARCHAR2(50),
  ADDRESS VARCHAR2(500),
  PHONE_NO VARCHAR2(20),
  ESTABLISH_DT DATE
);

CREATE TABLE TB_BRANCH (
  BRANCH_CD VARCHAR2(10) PRIMARY KEY,
  COMPANY_CD VARCHAR2(10) NOT NULL,
  BRANCH_NM VARCHAR2(100) NOT NULL,
  BRANCH_TYPE VARCHAR2(20),
  ADDRESS VARCHAR2(500),
  PHONE_NO VARCHAR2(20),
  USE_YN CHAR(1) DEFAULT 'Y'
);

CREATE TABLE TB_TEAM (
  TEAM_CD VARCHAR2(10) PRIMARY KEY,
  DEPT_CD VARCHAR2(10) NOT NULL,
  TEAM_NM VARCHAR2(100) NOT NULL,
  TEAM_LEADER_ID VARCHAR2(20),
  USE_YN CHAR(1) DEFAULT 'Y'
);

-- ===== 4. 프로젝트 (PROJECT) =====
CREATE TABLE TB_PROJECT (
  PROJ_CD VARCHAR2(20) PRIMARY KEY,
  PROJ_NM VARCHAR2(200) NOT NULL,
  PROJ_DESC VARCHAR2(2000),
  START_DT DATE,
  END_DT DATE,
  STATUS_CD VARCHAR2(10),
  BUDGET_AMT NUMBER(18),
  PM_EMP_ID VARCHAR2(20),
  DEPT_CD VARCHAR2(10)
);

CREATE TABLE TB_PROJ_MEMBER (
  MEMBER_ID VARCHAR2(20) PRIMARY KEY,
  PROJ_CD VARCHAR2(20) NOT NULL,
  EMP_ID VARCHAR2(20) NOT NULL,
  ROLE_CD VARCHAR2(10),
  JOIN_DT DATE,
  LEAVE_DT DATE
);

CREATE TABLE TB_PROJ_TASK (
  TASK_ID VARCHAR2(20) PRIMARY KEY,
  PROJ_CD VARCHAR2(20) NOT NULL,
  TASK_NM VARCHAR2(200) NOT NULL,
  TASK_DESC VARCHAR2(2000),
  ASSIGN_EMP_ID VARCHAR2(20),
  STATUS_CD VARCHAR2(10),
  PRIORITY_CD VARCHAR2(5),
  START_DT DATE,
  DUE_DT DATE,
  COMPLETE_DT DATE
);

CREATE TABLE TB_PROJ_MILESTONE (
  MILESTONE_ID VARCHAR2(20) PRIMARY KEY,
  PROJ_CD VARCHAR2(20) NOT NULL,
  MILESTONE_NM VARCHAR2(200),
  TARGET_DT DATE,
  COMPLETE_DT DATE,
  STATUS_CD VARCHAR2(10)
);

CREATE TABLE TB_PROJ_ISSUE (
  ISSUE_ID VARCHAR2(20) PRIMARY KEY,
  PROJ_CD VARCHAR2(20) NOT NULL,
  ISSUE_TITLE VARCHAR2(300),
  ISSUE_DESC VARCHAR2(4000),
  REPORT_EMP_ID VARCHAR2(20),
  ASSIGN_EMP_ID VARCHAR2(20),
  PRIORITY_CD VARCHAR2(5),
  STATUS_CD VARCHAR2(10),
  REPORT_DT DATE,
  RESOLVE_DT DATE
);

-- ===== 5. 자산 (ASSET) =====
CREATE TABLE TB_ASSET (
  ASSET_ID VARCHAR2(20) PRIMARY KEY,
  ASSET_NM VARCHAR2(200) NOT NULL,
  ASSET_TYPE_CD VARCHAR2(20),
  SERIAL_NO VARCHAR2(100),
  PURCHASE_DT DATE,
  PURCHASE_AMT NUMBER(15),
  CURRENT_LOC VARCHAR2(200),
  STATUS_CD VARCHAR2(10),
  REMARK VARCHAR2(1000)
);

CREATE TABLE TB_ASSET_ASSIGN (
  ASSIGN_ID VARCHAR2(20) PRIMARY KEY,
  ASSET_ID VARCHAR2(20) NOT NULL,
  EMP_ID VARCHAR2(20) NOT NULL,
  ASSIGN_DT DATE,
  RETURN_DT DATE,
  REMARK VARCHAR2(500)
);

CREATE TABLE TB_ASSET_MAINT (
  MAINT_ID VARCHAR2(20) PRIMARY KEY,
  ASSET_ID VARCHAR2(20) NOT NULL,
  MAINT_DT DATE,
  MAINT_TYPE VARCHAR2(20),
  MAINT_DESC VARCHAR2(1000),
  COST_AMT NUMBER(15),
  VENDOR_NM VARCHAR2(100)
);

-- ===== 6. 계약 (CONTRACT) =====
CREATE TABLE TB_CONTRACT (
  CONTRACT_ID VARCHAR2(20) PRIMARY KEY,
  CONTRACT_NM VARCHAR2(300) NOT NULL,
  CONTRACT_TYPE VARCHAR2(20),
  PARTNER_NM VARCHAR2(200),
  CONTRACT_AMT NUMBER(18),
  START_DT DATE,
  END_DT DATE,
  STATUS_CD VARCHAR2(10),
  CHARGE_DEPT_CD VARCHAR2(10),
  CHARGE_EMP_ID VARCHAR2(20)
);

CREATE TABLE TB_CONTRACT_DTL (
  DTL_ID VARCHAR2(20) PRIMARY KEY,
  CONTRACT_ID VARCHAR2(20) NOT NULL,
  ITEM_NM VARCHAR2(200),
  ITEM_QTY NUMBER(10),
  UNIT_PRICE NUMBER(15),
  ITEM_AMT NUMBER(18),
  REMARK VARCHAR2(500)
);

CREATE TABLE TB_VENDOR (
  VENDOR_CD VARCHAR2(20) PRIMARY KEY,
  VENDOR_NM VARCHAR2(200) NOT NULL,
  BIZ_NO VARCHAR2(20),
  CEO_NM VARCHAR2(50),
  ADDRESS VARCHAR2(500),
  PHONE_NO VARCHAR2(20),
  EMAIL VARCHAR2(200),
  VENDOR_TYPE VARCHAR2(20),
  USE_YN CHAR(1) DEFAULT 'Y'
);

-- ===== 7. 재무 (FINANCE) =====
CREATE TABLE TB_BUDGET (
  BUDGET_ID VARCHAR2(20) PRIMARY KEY,
  BUDGET_YEAR VARCHAR2(4) NOT NULL,
  DEPT_CD VARCHAR2(10),
  BUDGET_TYPE VARCHAR2(20),
  BUDGET_AMT NUMBER(18),
  EXEC_AMT NUMBER(18) DEFAULT 0,
  REMAIN_AMT NUMBER(18),
  STATUS_CD VARCHAR2(10)
);

CREATE TABLE TB_EXPENSE (
  EXPENSE_ID VARCHAR2(20) PRIMARY KEY,
  EMP_ID VARCHAR2(20) NOT NULL,
  EXPENSE_DT DATE,
  EXPENSE_TYPE VARCHAR2(20),
  EXPENSE_AMT NUMBER(15),
  APPROVAL_STATUS VARCHAR2(10),
  APPROVAL_DT DATE,
  REMARK VARCHAR2(1000)
);

CREATE TABLE TB_EXPENSE_DTL (
  DTL_ID VARCHAR2(20) PRIMARY KEY,
  EXPENSE_ID VARCHAR2(20) NOT NULL,
  ITEM_NM VARCHAR2(200),
  ITEM_AMT NUMBER(15),
  RECEIPT_YN CHAR(1) DEFAULT 'N'
);

CREATE TABLE TB_INVOICE (
  INVOICE_ID VARCHAR2(20) PRIMARY KEY,
  CONTRACT_ID VARCHAR2(20),
  VENDOR_CD VARCHAR2(20),
  INVOICE_DT DATE,
  INVOICE_AMT NUMBER(18),
  TAX_AMT NUMBER(18),
  TOTAL_AMT NUMBER(18),
  PAY_DUE_DT DATE,
  PAY_STATUS VARCHAR2(10)
);

-- ===== 8. 교육 (EDUCATION) =====
CREATE TABLE TB_EDUCATION (
  EDU_ID VARCHAR2(20) PRIMARY KEY,
  EDU_NM VARCHAR2(200) NOT NULL,
  EDU_TYPE VARCHAR2(20),
  EDU_DESC VARCHAR2(2000),
  START_DT DATE,
  END_DT DATE,
  LOCATION VARCHAR2(200),
  INSTRUCTOR VARCHAR2(100),
  MAX_PERSON NUMBER(5)
);

CREATE TABLE TB_EDU_REGISTER (
  REG_ID VARCHAR2(20) PRIMARY KEY,
  EDU_ID VARCHAR2(20) NOT NULL,
  EMP_ID VARCHAR2(20) NOT NULL,
  REG_DT DATE,
  STATUS_CD VARCHAR2(10),
  SCORE NUMBER(5,2),
  REMARK VARCHAR2(500)
);

CREATE TABLE TB_CERTIFICATION (
  CERT_ID VARCHAR2(20) PRIMARY KEY,
  EMP_ID VARCHAR2(20) NOT NULL,
  CERT_NM VARCHAR2(200) NOT NULL,
  CERT_NO VARCHAR2(100),
  ISSUE_ORG VARCHAR2(200),
  ISSUE_DT DATE,
  EXPIRE_DT DATE
);

-- ===== 9. 고객 (CUSTOMER) =====
CREATE TABLE TB_CUSTOMER (
  CUST_ID VARCHAR2(20) PRIMARY KEY,
  CUST_NM VARCHAR2(200) NOT NULL,
  CUST_TYPE VARCHAR2(20),
  BIZ_NO VARCHAR2(20),
  CEO_NM VARCHAR2(50),
  ADDRESS VARCHAR2(500),
  PHONE_NO VARCHAR2(20),
  EMAIL VARCHAR2(200),
  GRADE_CD VARCHAR2(10),
  REG_DT DATE
);

CREATE TABLE TB_CUST_CONTACT (
  CONTACT_ID VARCHAR2(20) PRIMARY KEY,
  CUST_ID VARCHAR2(20) NOT NULL,
  CONTACT_NM VARCHAR2(100) NOT NULL,
  POSITION VARCHAR2(50),
  PHONE_NO VARCHAR2(20),
  EMAIL VARCHAR2(200),
  MAIN_YN CHAR(1) DEFAULT 'N'
);

CREATE TABLE TB_CUST_HISTORY (
  HIST_ID VARCHAR2(20) PRIMARY KEY,
  CUST_ID VARCHAR2(20) NOT NULL,
  HIST_DT DATE,
  HIST_TYPE VARCHAR2(20),
  HIST_DESC VARCHAR2(2000),
  CHARGE_EMP_ID VARCHAR2(20)
);

-- ===== 10. 주문/매출 (ORDER) =====
CREATE TABLE TB_ORDER (
  ORDER_ID VARCHAR2(20) PRIMARY KEY,
  CUST_ID VARCHAR2(20) NOT NULL,
  ORDER_DT DATE NOT NULL,
  ORDER_TYPE VARCHAR2(20),
  TOTAL_AMT NUMBER(18),
  DISCOUNT_AMT NUMBER(15) DEFAULT 0,
  NET_AMT NUMBER(18),
  STATUS_CD VARCHAR2(10),
  DELIVERY_DT DATE,
  CHARGE_EMP_ID VARCHAR2(20)
);

CREATE TABLE TB_ORDER_DTL (
  DTL_ID VARCHAR2(20) PRIMARY KEY,
  ORDER_ID VARCHAR2(20) NOT NULL,
  PRODUCT_CD VARCHAR2(20) NOT NULL,
  PRODUCT_NM VARCHAR2(200),
  QTY NUMBER(10) NOT NULL,
  UNIT_PRICE NUMBER(15),
  ITEM_AMT NUMBER(18),
  REMARK VARCHAR2(500)
);

CREATE TABLE TB_PRODUCT (
  PRODUCT_CD VARCHAR2(20) PRIMARY KEY,
  PRODUCT_NM VARCHAR2(200) NOT NULL,
  PRODUCT_TYPE VARCHAR2(20),
  CATEGORY_CD VARCHAR2(20),
  UNIT_PRICE NUMBER(15),
  STOCK_QTY NUMBER(10) DEFAULT 0,
  USE_YN CHAR(1) DEFAULT 'Y',
  REMARK VARCHAR2(1000)
);

CREATE TABLE TB_PRODUCT_CATEGORY (
  CATEGORY_CD VARCHAR2(20) PRIMARY KEY,
  CATEGORY_NM VARCHAR2(100) NOT NULL,
  UPPER_CATEGORY_CD VARCHAR2(20),
  CATEGORY_LVL NUMBER(2),
  SORT_ORD NUMBER(5)
);

-- ===== 11. 시스템/공통 (SYSTEM) =====
CREATE TABLE TB_COMMON_CODE (
  CODE_GRP VARCHAR2(30) NOT NULL,
  CODE_CD VARCHAR2(20) NOT NULL,
  CODE_NM VARCHAR2(100) NOT NULL,
  CODE_DESC VARCHAR2(500),
  SORT_ORD NUMBER(5),
  USE_YN CHAR(1) DEFAULT 'Y',
  PRIMARY KEY (CODE_GRP, CODE_CD)
);

CREATE TABLE TB_MENU (
  MENU_ID VARCHAR2(20) PRIMARY KEY,
  MENU_NM VARCHAR2(100) NOT NULL,
  UPPER_MENU_ID VARCHAR2(20),
  MENU_URL VARCHAR2(300),
  MENU_LVL NUMBER(2),
  SORT_ORD NUMBER(5),
  ICON VARCHAR2(50),
  USE_YN CHAR(1) DEFAULT 'Y'
);

CREATE TABLE TB_ROLE (
  ROLE_CD VARCHAR2(20) PRIMARY KEY,
  ROLE_NM VARCHAR2(100) NOT NULL,
  ROLE_DESC VARCHAR2(500),
  USE_YN CHAR(1) DEFAULT 'Y'
);

CREATE TABLE TB_USER_ROLE (
  USER_ID VARCHAR2(20) NOT NULL,
  ROLE_CD VARCHAR2(20) NOT NULL,
  ASSIGN_DT DATE,
  PRIMARY KEY (USER_ID, ROLE_CD)
);

CREATE TABLE TB_ROLE_MENU (
  ROLE_CD VARCHAR2(20) NOT NULL,
  MENU_ID VARCHAR2(20) NOT NULL,
  READ_YN CHAR(1) DEFAULT 'Y',
  WRITE_YN CHAR(1) DEFAULT 'N',
  PRIMARY KEY (ROLE_CD, MENU_ID)
);

CREATE TABLE TB_AUDIT_LOG (
  LOG_ID VARCHAR2(40) PRIMARY KEY,
  USER_ID VARCHAR2(20),
  ACTION_TYPE VARCHAR2(20),
  TARGET_TABLE VARCHAR2(100),
  TARGET_ID VARCHAR2(100),
  ACTION_DESC VARCHAR2(2000),
  ACTION_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  IP_ADDR VARCHAR2(50)
);

CREATE TABLE TB_NOTIFICATION (
  NOTI_ID VARCHAR2(20) PRIMARY KEY,
  USER_ID VARCHAR2(20) NOT NULL,
  NOTI_TYPE VARCHAR2(20),
  NOTI_TITLE VARCHAR2(200),
  NOTI_CONTENT VARCHAR2(2000),
  READ_YN CHAR(1) DEFAULT 'N',
  CRET_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TB_FILE_STORAGE (
  FILE_ID VARCHAR2(40) PRIMARY KEY,
  FILE_NM VARCHAR2(300) NOT NULL,
  FILE_PATH VARCHAR2(500),
  FILE_SIZE NUMBER(15),
  FILE_TYPE VARCHAR2(50),
  REF_TABLE VARCHAR2(100),
  REF_ID VARCHAR2(40),
  CRET_USER_ID VARCHAR2(20),
  CRET_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TB_BATCH_JOB (
  JOB_ID VARCHAR2(20) PRIMARY KEY,
  JOB_NM VARCHAR2(200) NOT NULL,
  JOB_TYPE VARCHAR2(20),
  CRON_EXPR VARCHAR2(50),
  LAST_EXEC_DT TIMESTAMP,
  NEXT_EXEC_DT TIMESTAMP,
  STATUS_CD VARCHAR2(10),
  REMARK VARCHAR2(500)
);

CREATE TABLE TB_BATCH_LOG (
  LOG_ID VARCHAR2(40) PRIMARY KEY,
  JOB_ID VARCHAR2(20) NOT NULL,
  START_DT TIMESTAMP,
  END_DT TIMESTAMP,
  STATUS_CD VARCHAR2(10),
  PROCESS_CNT NUMBER(10),
  ERROR_MSG VARCHAR2(2000)
);

CREATE TABLE TB_SYSTEM_CONFIG (
  CONFIG_KEY VARCHAR2(100) PRIMARY KEY,
  CONFIG_VAL VARCHAR2(1000),
  CONFIG_DESC VARCHAR2(500),
  UPDT_DT TIMESTAMP,
  UPDT_USER_ID VARCHAR2(20)
);
