-- Cubrid 11.2 testdb 의 진단 대상 3 테이블 (DBA 스키마)
-- 적용: csql -u dba testdb -i 01_qual_test_ddl_cubrid.sql

DROP TABLE IF EXISTS TB_TEST_MEMBER;
DROP TABLE IF EXISTS TB_TEST_ORDER;
DROP TABLE IF EXISTS TB_TEST_PRODUCT;

CREATE TABLE TB_TEST_MEMBER (
    MEMBER_ID    VARCHAR(20)   NOT NULL,
    EMAIL        VARCHAR(100),
    PHONE        VARCHAR(20),
    NAME         VARCHAR(50),
    AGE          INTEGER,
    GENDER       VARCHAR(2),
    REG_DT       DATETIME      DEFAULT SYS_DATETIME NOT NULL,
    UPDT_DT      DATETIME,
    CONSTRAINT PK_TB_TEST_MEMBER PRIMARY KEY (MEMBER_ID)
);

CREATE TABLE TB_TEST_ORDER (
    ORDER_ID     VARCHAR(20)   NOT NULL,
    MEMBER_ID    VARCHAR(20),
    AMOUNT       NUMERIC(15,2),
    STATUS       VARCHAR(10),
    START_DT     DATE,
    END_DT       DATE,
    REG_DT       DATETIME      DEFAULT SYS_DATETIME NOT NULL,
    UPDT_DT      DATETIME,
    CONSTRAINT PK_TB_TEST_ORDER PRIMARY KEY (ORDER_ID)
);

CREATE TABLE TB_TEST_PRODUCT (
    PRODUCT_CODE VARCHAR(20),
    NAME         VARCHAR(100),
    PRICE        NUMERIC(15,2),
    CATEGORY     VARCHAR(20),
    REG_DT       DATETIME      DEFAULT SYS_DATETIME NOT NULL,
    UPDT_DT      DATETIME
);
