-- Cubrid 테스트용 dataQ 메타 등록 (PostgreSQL dataq-db 의 ndata + quality)
-- ds_id = 'TESTCUBRID', dm_id = 'TESTCUBRIDDM00000000A1'

INSERT INTO ndata.TB_DATA_SOURCE (
    DS_ID, DSN, DS_TP, DBMS_TP, DRIVER_NM,
    SVR_ADDR, PORT, USER_ID, PWD, CHARSET,
    DB_NAME, CONN_PROPS, SECURE_YN, CONN_TEST_YN
) VALUES (
    'TESTCUBRID',
    '품질진단 테스트 (Cubrid 11.2 testdb)',
    1,
    'Cubrid',
    'Cubrid',
    'host.docker.internal',
    '33000',
    'dba',
    '',
    'UTF-8',
    'testdb',
    NULL,
    false,
    'N'
)
ON CONFLICT (DS_ID) DO UPDATE SET
    DSN = EXCLUDED.DSN, SVR_ADDR = EXCLUDED.SVR_ADDR,
    PORT = EXCLUDED.PORT, USER_ID = EXCLUDED.USER_ID,
    DB_NAME = EXCLUDED.DB_NAME;

INSERT INTO quality.TB_DATA_MODEL (
    DM_ID, DM_NM, DM_DS_ID, VER, MODEL_TYPE, USE_YN,
    CRET_DT, CRET_USER_ID, STRUCT_DIAG_YN
) VALUES (
    'TESTCUBRIDDM00000000A1', 'TEST_CUBRID_MODEL', 'TESTCUBRID',
    '1.0', 'PHYSICAL', 'Y',
    to_char(now(), 'YYYYMMDDHH24MISS'), 'space', 'N'
)
ON CONFLICT (DM_ID) DO UPDATE SET DM_DS_ID = EXCLUDED.DM_DS_ID, USE_YN = 'Y';

INSERT INTO quality.TB_DATA_MODEL_OBJ (DM_ID, OBJ_NM, OBJ_NM_KR, OBJ_OWNER, OBJ_ATTR_CNT, USE_YN) VALUES
('TESTCUBRIDDM00000000A1', 'TB_TEST_MEMBER',  '품질진단_회원_큐브리드', 'PUBLIC', 8, 'Y'),
('TESTCUBRIDDM00000000A1', 'TB_TEST_ORDER',   '품질진단_주문_큐브리드', 'PUBLIC', 8, 'Y'),
('TESTCUBRIDDM00000000A1', 'TB_TEST_PRODUCT', '품질진단_상품_큐브리드', 'PUBLIC', 6, 'Y')
ON CONFLICT (DM_ID, OBJ_NM) DO UPDATE SET OBJ_OWNER = EXCLUDED.OBJ_OWNER, USE_YN = 'Y';

INSERT INTO quality.TB_DATA_MODEL_ATTR (
    DM_ID, OBJ_NM, ATTR_NM, ATTR_NM_KR,
    DATA_TYPE, DATA_LEN, DATA_DECIMAL_LEN,
    NULLABLE_YN, PK_YN, FK_YN, ATTR_ORD, OBJ_OWNER, USE_YN
) VALUES
('TESTCUBRIDDM00000000A1','TB_TEST_MEMBER','MEMBER_ID','회원ID','VARCHAR',20,0,'N','Y','N',1,'PUBLIC','Y'),
('TESTCUBRIDDM00000000A1','TB_TEST_MEMBER','EMAIL','이메일','VARCHAR',100,0,'Y','N','N',2,'PUBLIC','Y'),
('TESTCUBRIDDM00000000A1','TB_TEST_MEMBER','PHONE','전화번호','VARCHAR',20,0,'Y','N','N',3,'PUBLIC','Y'),
('TESTCUBRIDDM00000000A1','TB_TEST_MEMBER','NAME','이름','VARCHAR',50,0,'Y','N','N',4,'PUBLIC','Y'),
('TESTCUBRIDDM00000000A1','TB_TEST_MEMBER','AGE','나이','INTEGER',0,0,'Y','N','N',5,'PUBLIC','Y'),
('TESTCUBRIDDM00000000A1','TB_TEST_MEMBER','GENDER','성별','VARCHAR',2,0,'Y','N','N',6,'PUBLIC','Y'),
('TESTCUBRIDDM00000000A1','TB_TEST_MEMBER','REG_DT','등록일시','DATETIME',0,0,'N','N','N',7,'PUBLIC','Y'),
('TESTCUBRIDDM00000000A1','TB_TEST_MEMBER','UPDT_DT','수정일시','DATETIME',0,0,'Y','N','N',8,'PUBLIC','Y'),
('TESTCUBRIDDM00000000A1','TB_TEST_ORDER','ORDER_ID','주문ID','VARCHAR',20,0,'N','Y','N',1,'PUBLIC','Y'),
('TESTCUBRIDDM00000000A1','TB_TEST_ORDER','MEMBER_ID','회원ID','VARCHAR',20,0,'Y','N','Y',2,'PUBLIC','Y'),
('TESTCUBRIDDM00000000A1','TB_TEST_ORDER','AMOUNT','금액','NUMERIC',15,2,'Y','N','N',3,'PUBLIC','Y'),
('TESTCUBRIDDM00000000A1','TB_TEST_ORDER','STATUS','상태','VARCHAR',10,0,'Y','N','N',4,'PUBLIC','Y'),
('TESTCUBRIDDM00000000A1','TB_TEST_ORDER','START_DT','시작일','DATE',0,0,'Y','N','N',5,'PUBLIC','Y'),
('TESTCUBRIDDM00000000A1','TB_TEST_ORDER','END_DT','종료일','DATE',0,0,'Y','N','N',6,'PUBLIC','Y'),
('TESTCUBRIDDM00000000A1','TB_TEST_ORDER','REG_DT','등록일시','DATETIME',0,0,'N','N','N',7,'PUBLIC','Y'),
('TESTCUBRIDDM00000000A1','TB_TEST_ORDER','UPDT_DT','수정일시','DATETIME',0,0,'Y','N','N',8,'PUBLIC','Y'),
('TESTCUBRIDDM00000000A1','TB_TEST_PRODUCT','PRODUCT_CODE','상품코드','VARCHAR',20,0,'Y','N','N',1,'PUBLIC','Y'),
('TESTCUBRIDDM00000000A1','TB_TEST_PRODUCT','NAME','상품명','VARCHAR',100,0,'Y','N','N',2,'PUBLIC','Y'),
('TESTCUBRIDDM00000000A1','TB_TEST_PRODUCT','PRICE','가격','NUMERIC',15,2,'Y','N','N',3,'PUBLIC','Y'),
('TESTCUBRIDDM00000000A1','TB_TEST_PRODUCT','CATEGORY','카테고리','VARCHAR',20,0,'Y','N','N',4,'PUBLIC','Y'),
('TESTCUBRIDDM00000000A1','TB_TEST_PRODUCT','REG_DT','등록일시','DATETIME',0,0,'N','N','N',5,'PUBLIC','Y'),
('TESTCUBRIDDM00000000A1','TB_TEST_PRODUCT','UPDT_DT','수정일시','DATETIME',0,0,'Y','N','N',6,'PUBLIC','Y')
ON CONFLICT (DM_ID, OBJ_NM, ATTR_NM) DO UPDATE SET DATA_TYPE = EXCLUDED.DATA_TYPE, USE_YN = 'Y';
