-- Cubrid 모델용 룰 매핑 시드 (도메인 룰은 Oracle 모델과 공유)
DELETE FROM quality.TB_QUAL_COL_RULE WHERE DM_ID = 'TESTCUBRIDDM00000000A1';
DELETE FROM quality.TB_QUAL_RULE     WHERE DM_ID = 'TESTCUBRIDDM00000000A1';

INSERT INTO quality.TB_QUAL_RULE (
    RULE_ID, DM_ID, OBJ_NM, ATTR_NM, RULE_NM, RULE_TYPE, RULE_PARAMS,
    SEVERITY, USE_YN, EST_COST, DESCR, CRET_USER_ID, CRET_DT
) VALUES
('CUB_AGE_RANGE',     'TESTCUBRIDDM00000000A1', 'TB_TEST_MEMBER',  'AGE',          'CUB_AGE_RANGE',     'RANGE',     '{"min":0,"max":150}',           'ERROR', 'Y', 'MID', '나이 0~150', 'space', CURRENT_TIMESTAMP),
('CUB_GENDER_ENUM',   'TESTCUBRIDDM00000000A1', 'TB_TEST_MEMBER',  'GENDER',       'CUB_GENDER_ENUM',   'ENUM',      '{"values":["M","F","U"]}',      'WARN',  'Y', 'LOW', 'M/F/U',     'space', CURRENT_TIMESTAMP),
('CUB_AMOUNT_POS',    'TESTCUBRIDDM00000000A1', 'TB_TEST_ORDER',   'AMOUNT',       'CUB_AMOUNT_POS',    'RANGE',     '{"min":0}',                     'ERROR', 'Y', 'MID', '금액 0+',   'space', CURRENT_TIMESTAMP),
('CUB_STATUS_ENUM',   'TESTCUBRIDDM00000000A1', 'TB_TEST_ORDER',   'STATUS',       'CUB_STATUS_ENUM',   'ENUM',      '{"values":["PAID","PENDING","SHIPPED","CANCELED"]}', 'WARN', 'Y', 'LOW', '주문상태', 'space', CURRENT_TIMESTAMP),
('CUB_DATE_COMPARE',  'TESTCUBRIDDM00000000A1', 'TB_TEST_ORDER',   'END_DT',       'CUB_DATE_COMPARE',  'COMPARE',   '{"leftCol":"END_DT","op":">=","rightCol":"START_DT"}', 'ERROR','Y','MID','종료>=시작', 'space', CURRENT_TIMESTAMP),
('CUB_MEMBER_FK',     'TESTCUBRIDDM00000000A1', 'TB_TEST_ORDER',   'MEMBER_ID',    'CUB_MEMBER_FK',     'REFERENCE', '{"refTable":"TB_TEST_MEMBER","refCol":"MEMBER_ID"}',   'ERROR','Y','MID','회원존재',  'space', CURRENT_TIMESTAMP),
('CUB_CODE_LEN8',     'TESTCUBRIDDM00000000A1', 'TB_TEST_PRODUCT', 'PRODUCT_CODE', 'CUB_CODE_LEN8',     'LENGTH',    '{"minLen":8,"maxLen":8}',       'WARN',  'Y', 'MID', '코드8자',   'space', CURRENT_TIMESTAMP),
('CUB_NAME_NN',       'TESTCUBRIDDM00000000A1', 'TB_TEST_PRODUCT', 'NAME',         'CUB_NAME_NN',       'NOT_NULL',  '{}',                            'WARN',  'Y', 'LOW', '상품명NN',  'space', CURRENT_TIMESTAMP),
('CUB_PRICE_POS',     'TESTCUBRIDDM00000000A1', 'TB_TEST_PRODUCT', 'PRICE',        'CUB_PRICE_POS',     'RANGE',     '{"min":0}',                     'ERROR', 'Y', 'MID', '가격0+',    'space', CURRENT_TIMESTAMP),
('CUB_CATEGORY_ENUM', 'TESTCUBRIDDM00000000A1', 'TB_TEST_PRODUCT', 'CATEGORY',     'CUB_CATEGORY_ENUM', 'ENUM',      '{"values":["ELEC","CLOTH","FOOD","BOOK"]}', 'WARN','Y','LOW','카테고리',  'space', CURRENT_TIMESTAMP);

INSERT INTO quality.TB_QUAL_COL_RULE (DM_ID, OBJ_NM, ATTR_NM, DOMAIN_RULE_ID, CUSTOM_RULE_ID, EXCLUDE_YN, UPDT_USER_ID, UPDT_DT) VALUES
('TESTCUBRIDDM00000000A1','TB_TEST_MEMBER','MEMBER_ID',NULL,                NULL, 'Y','space',CURRENT_TIMESTAMP),
('TESTCUBRIDDM00000000A1','TB_TEST_MEMBER','EMAIL',    'DR_TEST_EMAIL_1',   NULL, 'N','space',CURRENT_TIMESTAMP),
('TESTCUBRIDDM00000000A1','TB_TEST_MEMBER','PHONE',    'DR_TEST_PHONE_DASH',NULL, 'N','space',CURRENT_TIMESTAMP),
('TESTCUBRIDDM00000000A1','TB_TEST_MEMBER','NAME',     NULL,                NULL, 'Y','space',CURRENT_TIMESTAMP),
('TESTCUBRIDDM00000000A1','TB_TEST_MEMBER','AGE',      NULL,'CUB_AGE_RANGE',      'N','space',CURRENT_TIMESTAMP),
('TESTCUBRIDDM00000000A1','TB_TEST_MEMBER','GENDER',   NULL,'CUB_GENDER_ENUM',    'N','space',CURRENT_TIMESTAMP),
('TESTCUBRIDDM00000000A1','TB_TEST_MEMBER','REG_DT',   NULL,                NULL, 'Y','space',CURRENT_TIMESTAMP),
('TESTCUBRIDDM00000000A1','TB_TEST_MEMBER','UPDT_DT',  NULL,                NULL, 'Y','space',CURRENT_TIMESTAMP),
('TESTCUBRIDDM00000000A1','TB_TEST_ORDER', 'ORDER_ID', NULL,                NULL, 'Y','space',CURRENT_TIMESTAMP),
('TESTCUBRIDDM00000000A1','TB_TEST_ORDER', 'MEMBER_ID',NULL,'CUB_MEMBER_FK',      'N','space',CURRENT_TIMESTAMP),
('TESTCUBRIDDM00000000A1','TB_TEST_ORDER', 'AMOUNT',   NULL,'CUB_AMOUNT_POS',     'N','space',CURRENT_TIMESTAMP),
('TESTCUBRIDDM00000000A1','TB_TEST_ORDER', 'STATUS',   NULL,'CUB_STATUS_ENUM',    'N','space',CURRENT_TIMESTAMP),
('TESTCUBRIDDM00000000A1','TB_TEST_ORDER', 'START_DT', NULL,                NULL, 'Y','space',CURRENT_TIMESTAMP),
('TESTCUBRIDDM00000000A1','TB_TEST_ORDER', 'END_DT',   NULL,'CUB_DATE_COMPARE',   'N','space',CURRENT_TIMESTAMP),
('TESTCUBRIDDM00000000A1','TB_TEST_ORDER', 'REG_DT',   NULL,                NULL, 'Y','space',CURRENT_TIMESTAMP),
('TESTCUBRIDDM00000000A1','TB_TEST_ORDER', 'UPDT_DT',  NULL,                NULL, 'Y','space',CURRENT_TIMESTAMP),
('TESTCUBRIDDM00000000A1','TB_TEST_PRODUCT','PRODUCT_CODE',NULL,'CUB_CODE_LEN8',  'N','space',CURRENT_TIMESTAMP),
('TESTCUBRIDDM00000000A1','TB_TEST_PRODUCT','NAME',    NULL,'CUB_NAME_NN',        'N','space',CURRENT_TIMESTAMP),
('TESTCUBRIDDM00000000A1','TB_TEST_PRODUCT','PRICE',   NULL,'CUB_PRICE_POS',      'N','space',CURRENT_TIMESTAMP),
('TESTCUBRIDDM00000000A1','TB_TEST_PRODUCT','CATEGORY',NULL,'CUB_CATEGORY_ENUM',  'N','space',CURRENT_TIMESTAMP),
('TESTCUBRIDDM00000000A1','TB_TEST_PRODUCT','REG_DT',  NULL,                NULL, 'Y','space',CURRENT_TIMESTAMP),
('TESTCUBRIDDM00000000A1','TB_TEST_PRODUCT','UPDT_DT', NULL,                NULL, 'Y','space',CURRENT_TIMESTAMP);
