-- Oracle 테스트 DB 초기화 SQL (AL32UTF8 신규 컨테이너용)
-- gvenzl/oracle-xe:21-slim-faststart 기반 (SID=XE, PDB=XEPDB1)
-- 실행: docker exec -i oracle-xe sqlplus -s 'sys/oracle@localhost:1521/XEPDB1 as sysdba' @init_oracle_testdb.sql
-- 또는 컨테이너 내에서 SYS로 실행
-- NLS_LANG=AMERICAN_AMERICA.AL32UTF8

ALTER SESSION SET CONTAINER = XEPDB1;

-- ====================
-- 스키마(유저) 생성
-- ====================
CREATE USER SALES_APP IDENTIFIED BY "salesapp123" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
CREATE USER HRM_APP   IDENTIFIED BY "hrmapp123"   DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
CREATE USER INV_APP   IDENTIFIED BY "invapp123"   DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
CREATE USER TESTUSER  IDENTIFIED BY "test123"     DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO SALES_APP;
GRANT CONNECT, RESOURCE TO HRM_APP;
GRANT CONNECT, RESOURCE TO INV_APP;
GRANT CONNECT TO TESTUSER;
GRANT SELECT ANY TABLE TO TESTUSER;
GRANT SELECT ANY DICTIONARY TO TESTUSER;

-- ====================
-- SALES_APP 테이블
-- ====================
CREATE TABLE SALES_APP.TB_CUST (
  CUST_NO   VARCHAR2(20)   NOT NULL,
  CUST_NM   VARCHAR2(100)  NOT NULL,
  CUST_ADDR VARCHAR2(500),
  CUST_EML  VARCHAR2(100),
  GNDR_CD   VARCHAR2(1),
  BRDT      DATE,
  REG_DT    TIMESTAMP(6),
  MDFCN_DT  TIMESTAMP(6),
  CONSTRAINT PK_TB_CUST PRIMARY KEY (CUST_NO)
);

CREATE TABLE SALES_APP.TB_ORDR (
  ORDR_NO   VARCHAR2(30)  NOT NULL,
  CUST_NO   VARCHAR2(20)  NOT NULL,
  ORDR_YMD  DATE          NOT NULL,
  ORDR_AMT  NUMBER(15),
  DSCNT_AMT NUMBER(12),
  STTS_CD   VARCHAR2(10),
  REG_DT    TIMESTAMP(6),
  CONSTRAINT PK_TB_ORDR PRIMARY KEY (ORDR_NO),
  CONSTRAINT FK_ORDR_CUST FOREIGN KEY (CUST_NO) REFERENCES SALES_APP.TB_CUST (CUST_NO)
);
CREATE INDEX SALES_APP.IX_ORDR_CUST ON SALES_APP.TB_ORDR (CUST_NO);
CREATE INDEX SALES_APP.IX_ORDR_YMD  ON SALES_APP.TB_ORDR (ORDR_YMD);

CREATE TABLE SALES_APP.TB_GDS (
  GOODS_ID   VARCHAR2(20)  NOT NULL,
  GOODS_NAME VARCHAR2(200),
  PRICE      NUMBER(12),
  QTY        NUMBER(10),
  REG_DATE   VARCHAR2(8),
  CONSTRAINT PK_TB_GDS PRIMARY KEY (GOODS_ID)
);

CREATE TABLE SALES_APP.TB_STLM (
  STLM_NO   VARCHAR2(30)  NOT NULL,
  ORDR_NO   VARCHAR2(30),
  CARD_NO   VARCHAR2(20),
  STLM_AMT  NUMBER(15),
  STLM_DT   TIMESTAMP(6),
  DSCNT_AMT NUMBER(12),
  RFND_YN   CHAR(1),
  CONSTRAINT PK_TB_STLM PRIMARY KEY (STLM_NO),
  CONSTRAINT FK_STLM_ORDR FOREIGN KEY (ORDR_NO) REFERENCES SALES_APP.TB_ORDR (ORDR_NO)
);

CREATE TABLE SALES_APP.TB_CPN (
  CPN_NO     VARCHAR2(30)  NOT NULL,
  CPN_NM     VARCHAR2(100),
  DSCNT_RATE NUMBER(5,2),
  START_DATE DATE,
  END_DATE   DATE,
  USE_YN     CHAR(1),
  CONSTRAINT PK_TB_CPN PRIMARY KEY (CPN_NO)
);

-- ====================
-- HRM_APP 테이블
-- ====================
CREATE TABLE HRM_APP.TB_DEPT (
  DEPT_CD        VARCHAR2(10)  NOT NULL,
  DEPT_NM        VARCHAR2(100),
  PARENT_DEPT_CD VARCHAR2(10),
  USE_YN         CHAR(1),
  REG_DT         TIMESTAMP(6),
  CONSTRAINT PK_TB_DEPT PRIMARY KEY (DEPT_CD)
);

CREATE TABLE HRM_APP.TB_TEAM (
  TEAM_CD VARCHAR2(10)  NOT NULL,
  TEAM_NM VARCHAR2(100),
  DEPT_CD VARCHAR2(10),
  CONSTRAINT PK_TB_TEAM PRIMARY KEY (TEAM_CD),
  CONSTRAINT FK_TEAM_DEPT FOREIGN KEY (DEPT_CD) REFERENCES HRM_APP.TB_DEPT (DEPT_CD)
);

CREATE TABLE HRM_APP.TB_EMP (
  EMP_NO       VARCHAR2(20)  NOT NULL,
  EMP_NM       VARCHAR2(100) NOT NULL,
  DEPT_CD      VARCHAR2(10),
  TEAM_CD      VARCHAR2(10),
  EML          VARCHAR2(100),
  PHONE_NUMBER VARCHAR2(20),
  BRDT         DATE,
  HIRE_DATE    DATE,
  REG_DT       TIMESTAMP(6),
  CONSTRAINT PK_TB_EMP PRIMARY KEY (EMP_NO),
  CONSTRAINT FK_EMP_DEPT FOREIGN KEY (DEPT_CD) REFERENCES HRM_APP.TB_DEPT (DEPT_CD)
);
CREATE INDEX HRM_APP.IX_EMP_DEPT ON HRM_APP.TB_EMP (DEPT_CD);

CREATE TABLE HRM_APP.COMPANY_INFO (
  COMPANY_ID   VARCHAR2(10)  NOT NULL,
  COMPANY_NAME VARCHAR2(200),
  CEO_NAME     VARCHAR2(100),
  ADDRESS      VARCHAR2(500),
  TELEPHONE    VARCHAR2(20),
  CONSTRAINT PK_COMPANY_INFO PRIMARY KEY (COMPANY_ID)
);

-- ====================
-- INV_APP 테이블
-- ====================
CREATE TABLE INV_APP.TB_WRHUS (
  WRHUS_CD VARCHAR2(10)  NOT NULL,
  WRHUS_NM VARCHAR2(100),
  ADDR     VARCHAR2(500),
  EMP_NO   VARCHAR2(20),
  CONSTRAINT PK_TB_WRHUS PRIMARY KEY (WRHUS_CD)
);

CREATE TABLE INV_APP.TB_INVT (
  GDS_CD   VARCHAR2(20)  NOT NULL,
  WRHUS_CD VARCHAR2(10)  NOT NULL,
  INVT_QTY NUMBER(10),
  UPD_DT   TIMESTAMP(6),
  CONSTRAINT PK_TB_INVT PRIMARY KEY (GDS_CD, WRHUS_CD),
  CONSTRAINT FK_INVT_WRHUS FOREIGN KEY (WRHUS_CD) REFERENCES INV_APP.TB_WRHUS (WRHUS_CD)
);

CREATE TABLE INV_APP.TB_WRHS (
  WRHS_NO  VARCHAR2(30)  NOT NULL,
  GDS_CD   VARCHAR2(20),
  WRHUS_CD VARCHAR2(10),
  WRHS_QTY NUMBER(10),
  WRHS_DT  TIMESTAMP(6),
  EMP_NO   VARCHAR2(20),
  CONSTRAINT PK_TB_WRHS PRIMARY KEY (WRHS_NO)
);

CREATE TABLE INV_APP.TB_SPMT (
  SPMT_NO  VARCHAR2(30)  NOT NULL,
  GDS_CD   VARCHAR2(20),
  WRHUS_CD VARCHAR2(10),
  SPMT_QTY NUMBER(10),
  SPMT_DT  TIMESTAMP(6),
  DLVR_NO  VARCHAR2(30),
  CONSTRAINT PK_TB_SPMT PRIMARY KEY (SPMT_NO)
);

CREATE TABLE INV_APP.DELIVERY_LOG (
  DELIVERY_ID   VARCHAR2(30)  NOT NULL,
  ORDER_NO      VARCHAR2(30),
  DELIVERY_DATE DATE,
  CUSTOMER_NAME VARCHAR2(100),
  DELIVERY_ADDR VARCHAR2(500),
  STATUS        VARCHAR2(10),
  CONSTRAINT PK_DELIVERY_LOG PRIMARY KEY (DELIVERY_ID)
);

-- ====================
-- 한글 코멘트 (테이블 + 컬럼)
-- ====================

-- SALES_APP.TB_CUST
COMMENT ON TABLE  SALES_APP.TB_CUST IS '고객';
COMMENT ON COLUMN SALES_APP.TB_CUST.CUST_NO   IS '고객번호';
COMMENT ON COLUMN SALES_APP.TB_CUST.CUST_NM   IS '고객명';
COMMENT ON COLUMN SALES_APP.TB_CUST.CUST_ADDR IS '고객주소';
COMMENT ON COLUMN SALES_APP.TB_CUST.CUST_EML  IS '고객이메일';
COMMENT ON COLUMN SALES_APP.TB_CUST.GNDR_CD   IS '성별코드';
COMMENT ON COLUMN SALES_APP.TB_CUST.BRDT      IS '생년월일';
COMMENT ON COLUMN SALES_APP.TB_CUST.REG_DT    IS '등록일시';
COMMENT ON COLUMN SALES_APP.TB_CUST.MDFCN_DT  IS '수정일시';

-- SALES_APP.TB_ORDR
COMMENT ON TABLE  SALES_APP.TB_ORDR IS '주문';
COMMENT ON COLUMN SALES_APP.TB_ORDR.ORDR_NO   IS '주문번호';
COMMENT ON COLUMN SALES_APP.TB_ORDR.CUST_NO   IS '고객번호';
COMMENT ON COLUMN SALES_APP.TB_ORDR.ORDR_YMD  IS '주문일자';
COMMENT ON COLUMN SALES_APP.TB_ORDR.ORDR_AMT  IS '주문금액';
COMMENT ON COLUMN SALES_APP.TB_ORDR.DSCNT_AMT IS '할인금액';
COMMENT ON COLUMN SALES_APP.TB_ORDR.STTS_CD   IS '상태코드';
COMMENT ON COLUMN SALES_APP.TB_ORDR.REG_DT    IS '등록일시';

-- SALES_APP.TB_GDS (비표준)
COMMENT ON TABLE  SALES_APP.TB_GDS IS '상품';
COMMENT ON COLUMN SALES_APP.TB_GDS.GOODS_ID   IS '상품아이디';
COMMENT ON COLUMN SALES_APP.TB_GDS.GOODS_NAME IS '상품이름';
COMMENT ON COLUMN SALES_APP.TB_GDS.PRICE      IS '가격';
COMMENT ON COLUMN SALES_APP.TB_GDS.QTY        IS '수량';
COMMENT ON COLUMN SALES_APP.TB_GDS.REG_DATE   IS '등록일자';

-- SALES_APP.TB_STLM
COMMENT ON TABLE  SALES_APP.TB_STLM IS '결제';
COMMENT ON COLUMN SALES_APP.TB_STLM.STLM_NO   IS '결제번호';
COMMENT ON COLUMN SALES_APP.TB_STLM.ORDR_NO   IS '주문번호';
COMMENT ON COLUMN SALES_APP.TB_STLM.CARD_NO   IS '카드번호';
COMMENT ON COLUMN SALES_APP.TB_STLM.STLM_AMT  IS '결제금액';
COMMENT ON COLUMN SALES_APP.TB_STLM.STLM_DT   IS '결제일시';
COMMENT ON COLUMN SALES_APP.TB_STLM.DSCNT_AMT IS '할인금액';
COMMENT ON COLUMN SALES_APP.TB_STLM.RFND_YN   IS '환불여부';

-- SALES_APP.TB_CPN (비표준)
COMMENT ON TABLE  SALES_APP.TB_CPN IS '쿠폰';
COMMENT ON COLUMN SALES_APP.TB_CPN.CPN_NO     IS '쿠폰번호';
COMMENT ON COLUMN SALES_APP.TB_CPN.CPN_NM     IS '쿠폰명';
COMMENT ON COLUMN SALES_APP.TB_CPN.DSCNT_RATE IS '할인율';
COMMENT ON COLUMN SALES_APP.TB_CPN.START_DATE IS '시작일자';
COMMENT ON COLUMN SALES_APP.TB_CPN.END_DATE   IS '종료일자';
COMMENT ON COLUMN SALES_APP.TB_CPN.USE_YN     IS '사용여부';

-- HRM_APP.TB_DEPT
COMMENT ON TABLE  HRM_APP.TB_DEPT IS '부서';
COMMENT ON COLUMN HRM_APP.TB_DEPT.DEPT_CD        IS '부서코드';
COMMENT ON COLUMN HRM_APP.TB_DEPT.DEPT_NM        IS '부서명';
COMMENT ON COLUMN HRM_APP.TB_DEPT.PARENT_DEPT_CD IS '상위부서코드';
COMMENT ON COLUMN HRM_APP.TB_DEPT.USE_YN         IS '사용여부';
COMMENT ON COLUMN HRM_APP.TB_DEPT.REG_DT         IS '등록일시';

-- HRM_APP.TB_TEAM
COMMENT ON TABLE  HRM_APP.TB_TEAM IS '팀';
COMMENT ON COLUMN HRM_APP.TB_TEAM.TEAM_CD IS '팀코드';
COMMENT ON COLUMN HRM_APP.TB_TEAM.TEAM_NM IS '팀명';
COMMENT ON COLUMN HRM_APP.TB_TEAM.DEPT_CD IS '부서코드';

-- HRM_APP.TB_EMP (비표준 PHONE_NUMBER, HIRE_DATE)
COMMENT ON TABLE  HRM_APP.TB_EMP IS '직원';
COMMENT ON COLUMN HRM_APP.TB_EMP.EMP_NO       IS '직원번호';
COMMENT ON COLUMN HRM_APP.TB_EMP.EMP_NM       IS '직원명';
COMMENT ON COLUMN HRM_APP.TB_EMP.DEPT_CD      IS '부서코드';
COMMENT ON COLUMN HRM_APP.TB_EMP.TEAM_CD      IS '팀코드';
COMMENT ON COLUMN HRM_APP.TB_EMP.EML          IS '이메일';
COMMENT ON COLUMN HRM_APP.TB_EMP.PHONE_NUMBER IS '전화번호';
COMMENT ON COLUMN HRM_APP.TB_EMP.BRDT         IS '생년월일';
COMMENT ON COLUMN HRM_APP.TB_EMP.HIRE_DATE    IS '입사일자';
COMMENT ON COLUMN HRM_APP.TB_EMP.REG_DT       IS '등록일시';

-- HRM_APP.COMPANY_INFO (비표준: 테이블 접두어 누락, 풀네임)
COMMENT ON TABLE  HRM_APP.COMPANY_INFO IS '회사정보';
COMMENT ON COLUMN HRM_APP.COMPANY_INFO.COMPANY_ID   IS '회사아이디';
COMMENT ON COLUMN HRM_APP.COMPANY_INFO.COMPANY_NAME IS '회사이름';
COMMENT ON COLUMN HRM_APP.COMPANY_INFO.CEO_NAME     IS '대표자이름';
COMMENT ON COLUMN HRM_APP.COMPANY_INFO.ADDRESS      IS '주소';
COMMENT ON COLUMN HRM_APP.COMPANY_INFO.TELEPHONE    IS '전화번호';

-- INV_APP.TB_WRHUS
COMMENT ON TABLE  INV_APP.TB_WRHUS IS '창고';
COMMENT ON COLUMN INV_APP.TB_WRHUS.WRHUS_CD IS '창고코드';
COMMENT ON COLUMN INV_APP.TB_WRHUS.WRHUS_NM IS '창고명';
COMMENT ON COLUMN INV_APP.TB_WRHUS.ADDR     IS '주소';
COMMENT ON COLUMN INV_APP.TB_WRHUS.EMP_NO   IS '담당자번호';

-- INV_APP.TB_INVT
COMMENT ON TABLE  INV_APP.TB_INVT IS '재고';
COMMENT ON COLUMN INV_APP.TB_INVT.GDS_CD   IS '상품코드';
COMMENT ON COLUMN INV_APP.TB_INVT.WRHUS_CD IS '창고코드';
COMMENT ON COLUMN INV_APP.TB_INVT.INVT_QTY IS '재고수량';
COMMENT ON COLUMN INV_APP.TB_INVT.UPD_DT   IS '수정일시';

-- INV_APP.TB_WRHS (입고)
COMMENT ON TABLE  INV_APP.TB_WRHS IS '입고';
COMMENT ON COLUMN INV_APP.TB_WRHS.WRHS_NO  IS '입고번호';
COMMENT ON COLUMN INV_APP.TB_WRHS.GDS_CD   IS '상품코드';
COMMENT ON COLUMN INV_APP.TB_WRHS.WRHUS_CD IS '창고코드';
COMMENT ON COLUMN INV_APP.TB_WRHS.WRHS_QTY IS '입고수량';
COMMENT ON COLUMN INV_APP.TB_WRHS.WRHS_DT  IS '입고일시';
COMMENT ON COLUMN INV_APP.TB_WRHS.EMP_NO   IS '담당자번호';

-- INV_APP.TB_SPMT (출고)
COMMENT ON TABLE  INV_APP.TB_SPMT IS '출고';
COMMENT ON COLUMN INV_APP.TB_SPMT.SPMT_NO  IS '출고번호';
COMMENT ON COLUMN INV_APP.TB_SPMT.GDS_CD   IS '상품코드';
COMMENT ON COLUMN INV_APP.TB_SPMT.WRHUS_CD IS '창고코드';
COMMENT ON COLUMN INV_APP.TB_SPMT.SPMT_QTY IS '출고수량';
COMMENT ON COLUMN INV_APP.TB_SPMT.SPMT_DT  IS '출고일시';
COMMENT ON COLUMN INV_APP.TB_SPMT.DLVR_NO  IS '배송번호';

-- INV_APP.DELIVERY_LOG (비표준: 접두어 누락, 풀네임)
COMMENT ON TABLE  INV_APP.DELIVERY_LOG IS '배송이력';
COMMENT ON COLUMN INV_APP.DELIVERY_LOG.DELIVERY_ID   IS '배송아이디';
COMMENT ON COLUMN INV_APP.DELIVERY_LOG.ORDER_NO      IS '주문번호';
COMMENT ON COLUMN INV_APP.DELIVERY_LOG.DELIVERY_DATE IS '배송일자';
COMMENT ON COLUMN INV_APP.DELIVERY_LOG.CUSTOMER_NAME IS '고객이름';
COMMENT ON COLUMN INV_APP.DELIVERY_LOG.DELIVERY_ADDR IS '배송주소';
COMMENT ON COLUMN INV_APP.DELIVERY_LOG.STATUS        IS '상태';

-- ====================
-- 최소 테스트 데이터
-- ====================
INSERT INTO SALES_APP.TB_CUST (CUST_NO, CUST_NM, CUST_ADDR, CUST_EML, GNDR_CD, BRDT, REG_DT)
VALUES ('C0000001', '홍길동', '서울시 강남구 테헤란로 123', 'hong@test.com', 'M', DATE '1990-01-01', SYSTIMESTAMP);
INSERT INTO SALES_APP.TB_CUST (CUST_NO, CUST_NM, CUST_ADDR, CUST_EML, GNDR_CD, BRDT, REG_DT)
VALUES ('C0000002', '김철수', '서울시 마포구 월드컵로 45', 'kim@test.com', 'F', DATE '1992-05-20', SYSTIMESTAMP);

INSERT INTO HRM_APP.TB_DEPT (DEPT_CD, DEPT_NM, USE_YN, REG_DT) VALUES ('D001', '영업부', 'Y', SYSTIMESTAMP);
INSERT INTO HRM_APP.TB_DEPT (DEPT_CD, DEPT_NM, USE_YN, REG_DT) VALUES ('D002', '개발부', 'Y', SYSTIMESTAMP);

INSERT INTO INV_APP.TB_WRHUS (WRHUS_CD, WRHUS_NM, ADDR) VALUES ('W01', '서울창고', '서울시 강서구 공항대로 100');
INSERT INTO INV_APP.TB_WRHUS (WRHUS_CD, WRHUS_NM, ADDR) VALUES ('W02', '부산창고', '부산시 사상구 감전로 50');

COMMIT;
EXIT;
