-- 테이블 코멘트
COMMENT ON TABLE TB_EMPLOYEE IS '임직원';
COMMENT ON TABLE TB_DEPARTMENT IS '부서';
COMMENT ON TABLE TB_POSITION IS '직위';
COMMENT ON TABLE TB_EMP_HISTORY IS '인사이력';
COMMENT ON TABLE TB_ATTENDANCE IS '근태';
COMMENT ON TABLE TB_SALARY IS '급여';
COMMENT ON TABLE TB_SALARY_ITEM IS '급여항목';
COMMENT ON TABLE TB_TAX_INFO IS '세금정보';
COMMENT ON TABLE TB_COMPANY IS '회사';
COMMENT ON TABLE TB_BRANCH IS '지점';
COMMENT ON TABLE TB_TEAM IS '팀';
COMMENT ON TABLE TB_PROJECT IS '프로젝트';
COMMENT ON TABLE TB_PROJ_MEMBER IS '프로젝트구성원';
COMMENT ON TABLE TB_PROJ_TASK IS '프로젝트작업';
COMMENT ON TABLE TB_PROJ_MILESTONE IS '프로젝트마일스톤';
COMMENT ON TABLE TB_PROJ_ISSUE IS '프로젝트이슈';
COMMENT ON TABLE TB_ASSET IS '자산';
COMMENT ON TABLE TB_ASSET_ASSIGN IS '자산배정';
COMMENT ON TABLE TB_ASSET_MAINT IS '자산유지보수';
COMMENT ON TABLE TB_CONTRACT IS '계약';
COMMENT ON TABLE TB_CONTRACT_DTL IS '계약상세';
COMMENT ON TABLE TB_VENDOR IS '거래처';
COMMENT ON TABLE TB_BUDGET IS '예산';
COMMENT ON TABLE TB_EXPENSE IS '경비';
COMMENT ON TABLE TB_EXPENSE_DTL IS '경비상세';
COMMENT ON TABLE TB_INVOICE IS '세금계산서';
COMMENT ON TABLE TB_EDUCATION IS '교육';
COMMENT ON TABLE TB_EDU_REGISTER IS '교육수강';
COMMENT ON TABLE TB_CERTIFICATION IS '자격증';
COMMENT ON TABLE TB_CUSTOMER IS '고객';
COMMENT ON TABLE TB_CUST_CONTACT IS '고객담당자';
COMMENT ON TABLE TB_CUST_HISTORY IS '고객이력';
COMMENT ON TABLE TB_ORDER IS '주문';
COMMENT ON TABLE TB_ORDER_DTL IS '주문상세';
COMMENT ON TABLE TB_PRODUCT IS '상품';
COMMENT ON TABLE TB_PRODUCT_CATEGORY IS '상품분류';
COMMENT ON TABLE TB_COMMON_CODE IS '공통코드';
COMMENT ON TABLE TB_MENU IS '메뉴';
COMMENT ON TABLE TB_ROLE IS '역할';
COMMENT ON TABLE TB_USER_ROLE IS '사용자역할';
COMMENT ON TABLE TB_ROLE_MENU IS '역할메뉴권한';
COMMENT ON TABLE TB_AUDIT_LOG IS '감사로그';
COMMENT ON TABLE TB_NOTIFICATION IS '알림';
COMMENT ON TABLE TB_FILE_STORAGE IS '파일저장소';
COMMENT ON TABLE TB_BATCH_JOB IS '배치작업';
COMMENT ON TABLE TB_BATCH_LOG IS '배치로그';
COMMENT ON TABLE TB_SYSTEM_CONFIG IS '시스템설정';
COMMENT ON TABLE TB_LEAVE_REQUEST IS '휴가신청';
COMMENT ON TABLE TB_MEETING_ROOM IS '회의실';
COMMENT ON TABLE TB_MEETING_RESERVE IS '회의실예약';

-- TB_EMPLOYEE
COMMENT ON COLUMN TB_EMPLOYEE.EMP_ID IS '임직원ID';
COMMENT ON COLUMN TB_EMPLOYEE.EMP_NM IS '임직원명';
COMMENT ON COLUMN TB_EMPLOYEE.EMP_ENG_NM IS '임직원영문명';
COMMENT ON COLUMN TB_EMPLOYEE.BIRTH_DT IS '생년월일';
COMMENT ON COLUMN TB_EMPLOYEE.GENDER_CD IS '성별코드';
COMMENT ON COLUMN TB_EMPLOYEE.PHONE_NO IS '전화번호';
COMMENT ON COLUMN TB_EMPLOYEE.EMAIL IS '이메일';
COMMENT ON COLUMN TB_EMPLOYEE.HIRE_DT IS '입사일자';
COMMENT ON COLUMN TB_EMPLOYEE.RESIGN_DT IS '퇴사일자';
COMMENT ON COLUMN TB_EMPLOYEE.DEPT_CD IS '부서코드';
COMMENT ON COLUMN TB_EMPLOYEE.POSITION_CD IS '직위코드';
COMMENT ON COLUMN TB_EMPLOYEE.STATUS_CD IS '상태코드';

-- TB_DEPARTMENT
COMMENT ON COLUMN TB_DEPARTMENT.DEPT_CD IS '부서코드';
COMMENT ON COLUMN TB_DEPARTMENT.DEPT_NM IS '부서명';
COMMENT ON COLUMN TB_DEPARTMENT.DEPT_ENG_NM IS '부서영문명';
COMMENT ON COLUMN TB_DEPARTMENT.UPPER_DEPT_CD IS '상위부서코드';
COMMENT ON COLUMN TB_DEPARTMENT.DEPT_LVL IS '부서레벨';
COMMENT ON COLUMN TB_DEPARTMENT.SORT_ORD IS '정렬순서';
COMMENT ON COLUMN TB_DEPARTMENT.USE_YN IS '사용여부';

-- TB_POSITION
COMMENT ON COLUMN TB_POSITION.POSITION_CD IS '직위코드';
COMMENT ON COLUMN TB_POSITION.POSITION_NM IS '직위명';
COMMENT ON COLUMN TB_POSITION.POSITION_LVL IS '직위레벨';
COMMENT ON COLUMN TB_POSITION.SORT_ORD IS '정렬순서';

-- TB_EMP_HISTORY
COMMENT ON COLUMN TB_EMP_HISTORY.HIST_ID IS '이력ID';
COMMENT ON COLUMN TB_EMP_HISTORY.EMP_ID IS '임직원ID';
COMMENT ON COLUMN TB_EMP_HISTORY.CHANGE_TYPE IS '변경유형';
COMMENT ON COLUMN TB_EMP_HISTORY.BEFORE_VAL IS '변경전값';
COMMENT ON COLUMN TB_EMP_HISTORY.AFTER_VAL IS '변경후값';
COMMENT ON COLUMN TB_EMP_HISTORY.CHANGE_DT IS '변경일자';
COMMENT ON COLUMN TB_EMP_HISTORY.CHANGE_USER_ID IS '변경자ID';

-- TB_ATTENDANCE
COMMENT ON COLUMN TB_ATTENDANCE.ATTEND_ID IS '근태ID';
COMMENT ON COLUMN TB_ATTENDANCE.EMP_ID IS '임직원ID';
COMMENT ON COLUMN TB_ATTENDANCE.ATTEND_DT IS '근태일자';
COMMENT ON COLUMN TB_ATTENDANCE.CHECK_IN_TIME IS '출근시간';
COMMENT ON COLUMN TB_ATTENDANCE.CHECK_OUT_TIME IS '퇴근시간';
COMMENT ON COLUMN TB_ATTENDANCE.ATTEND_TYPE IS '근태유형';
COMMENT ON COLUMN TB_ATTENDANCE.REMARK IS '비고';

-- TB_SALARY
COMMENT ON COLUMN TB_SALARY.SALARY_ID IS '급여ID';
COMMENT ON COLUMN TB_SALARY.EMP_ID IS '임직원ID';
COMMENT ON COLUMN TB_SALARY.PAY_YEAR IS '지급연도';
COMMENT ON COLUMN TB_SALARY.PAY_MONTH IS '지급월';
COMMENT ON COLUMN TB_SALARY.BASE_SALARY IS '기본급';
COMMENT ON COLUMN TB_SALARY.BONUS_AMT IS '상여금액';
COMMENT ON COLUMN TB_SALARY.DEDUCTION_AMT IS '공제금액';
COMMENT ON COLUMN TB_SALARY.NET_SALARY IS '실수령액';
COMMENT ON COLUMN TB_SALARY.PAY_DT IS '지급일자';

-- TB_SALARY_ITEM
COMMENT ON COLUMN TB_SALARY_ITEM.ITEM_ID IS '항목ID';
COMMENT ON COLUMN TB_SALARY_ITEM.SALARY_ID IS '급여ID';
COMMENT ON COLUMN TB_SALARY_ITEM.ITEM_CD IS '항목코드';
COMMENT ON COLUMN TB_SALARY_ITEM.ITEM_NM IS '항목명';
COMMENT ON COLUMN TB_SALARY_ITEM.ITEM_AMT IS '항목금액';
COMMENT ON COLUMN TB_SALARY_ITEM.ITEM_TYPE IS '항목유형';

-- TB_TAX_INFO
COMMENT ON COLUMN TB_TAX_INFO.TAX_ID IS '세금ID';
COMMENT ON COLUMN TB_TAX_INFO.EMP_ID IS '임직원ID';
COMMENT ON COLUMN TB_TAX_INFO.TAX_YEAR IS '과세연도';
COMMENT ON COLUMN TB_TAX_INFO.INCOME_TAX IS '소득세';
COMMENT ON COLUMN TB_TAX_INFO.LOCAL_TAX IS '지방세';
COMMENT ON COLUMN TB_TAX_INFO.HEALTH_INS IS '건강보험';
COMMENT ON COLUMN TB_TAX_INFO.PENSION IS '국민연금';

-- TB_COMPANY
COMMENT ON COLUMN TB_COMPANY.COMPANY_CD IS '회사코드';
COMMENT ON COLUMN TB_COMPANY.COMPANY_NM IS '회사명';
COMMENT ON COLUMN TB_COMPANY.BIZ_NO IS '사업자번호';
COMMENT ON COLUMN TB_COMPANY.CEO_NM IS '대표자명';
COMMENT ON COLUMN TB_COMPANY.ADDRESS IS '주소';
COMMENT ON COLUMN TB_COMPANY.PHONE_NO IS '전화번호';
COMMENT ON COLUMN TB_COMPANY.ESTABLISH_DT IS '설립일자';

-- TB_BRANCH
COMMENT ON COLUMN TB_BRANCH.BRANCH_CD IS '지점코드';
COMMENT ON COLUMN TB_BRANCH.COMPANY_CD IS '회사코드';
COMMENT ON COLUMN TB_BRANCH.BRANCH_NM IS '지점명';
COMMENT ON COLUMN TB_BRANCH.BRANCH_TYPE IS '지점유형';
COMMENT ON COLUMN TB_BRANCH.ADDRESS IS '주소';
COMMENT ON COLUMN TB_BRANCH.PHONE_NO IS '전화번호';
COMMENT ON COLUMN TB_BRANCH.USE_YN IS '사용여부';

-- TB_TEAM
COMMENT ON COLUMN TB_TEAM.TEAM_CD IS '팀코드';
COMMENT ON COLUMN TB_TEAM.DEPT_CD IS '부서코드';
COMMENT ON COLUMN TB_TEAM.TEAM_NM IS '팀명';
COMMENT ON COLUMN TB_TEAM.TEAM_LEADER_ID IS '팀장ID';
COMMENT ON COLUMN TB_TEAM.USE_YN IS '사용여부';

-- TB_PROJECT
COMMENT ON COLUMN TB_PROJECT.PROJ_CD IS '프로젝트코드';
COMMENT ON COLUMN TB_PROJECT.PROJ_NM IS '프로젝트명';
COMMENT ON COLUMN TB_PROJECT.PROJ_DESC IS '프로젝트설명';
COMMENT ON COLUMN TB_PROJECT.START_DT IS '시작일자';
COMMENT ON COLUMN TB_PROJECT.END_DT IS '종료일자';
COMMENT ON COLUMN TB_PROJECT.STATUS_CD IS '상태코드';
COMMENT ON COLUMN TB_PROJECT.BUDGET_AMT IS '예산금액';
COMMENT ON COLUMN TB_PROJECT.PM_EMP_ID IS 'PM임직원ID';
COMMENT ON COLUMN TB_PROJECT.DEPT_CD IS '부서코드';

-- TB_PROJ_MEMBER
COMMENT ON COLUMN TB_PROJ_MEMBER.MEMBER_ID IS '구성원ID';
COMMENT ON COLUMN TB_PROJ_MEMBER.PROJ_CD IS '프로젝트코드';
COMMENT ON COLUMN TB_PROJ_MEMBER.EMP_ID IS '임직원ID';
COMMENT ON COLUMN TB_PROJ_MEMBER.ROLE_CD IS '역할코드';
COMMENT ON COLUMN TB_PROJ_MEMBER.JOIN_DT IS '참여일자';
COMMENT ON COLUMN TB_PROJ_MEMBER.LEAVE_DT IS '이탈일자';

-- TB_PROJ_TASK
COMMENT ON COLUMN TB_PROJ_TASK.TASK_ID IS '작업ID';
COMMENT ON COLUMN TB_PROJ_TASK.PROJ_CD IS '프로젝트코드';
COMMENT ON COLUMN TB_PROJ_TASK.TASK_NM IS '작업명';
COMMENT ON COLUMN TB_PROJ_TASK.TASK_DESC IS '작업설명';
COMMENT ON COLUMN TB_PROJ_TASK.ASSIGN_EMP_ID IS '담당자ID';
COMMENT ON COLUMN TB_PROJ_TASK.STATUS_CD IS '상태코드';
COMMENT ON COLUMN TB_PROJ_TASK.PRIORITY_CD IS '우선순위코드';
COMMENT ON COLUMN TB_PROJ_TASK.START_DT IS '시작일자';
COMMENT ON COLUMN TB_PROJ_TASK.DUE_DT IS '마감일자';
COMMENT ON COLUMN TB_PROJ_TASK.COMPLETE_DT IS '완료일자';

-- TB_PROJ_MILESTONE
COMMENT ON COLUMN TB_PROJ_MILESTONE.MILESTONE_ID IS '마일스톤ID';
COMMENT ON COLUMN TB_PROJ_MILESTONE.PROJ_CD IS '프로젝트코드';
COMMENT ON COLUMN TB_PROJ_MILESTONE.MILESTONE_NM IS '마일스톤명';
COMMENT ON COLUMN TB_PROJ_MILESTONE.TARGET_DT IS '목표일자';
COMMENT ON COLUMN TB_PROJ_MILESTONE.COMPLETE_DT IS '완료일자';
COMMENT ON COLUMN TB_PROJ_MILESTONE.STATUS_CD IS '상태코드';

-- TB_PROJ_ISSUE
COMMENT ON COLUMN TB_PROJ_ISSUE.ISSUE_ID IS '이슈ID';
COMMENT ON COLUMN TB_PROJ_ISSUE.PROJ_CD IS '프로젝트코드';
COMMENT ON COLUMN TB_PROJ_ISSUE.ISSUE_TITLE IS '이슈제목';
COMMENT ON COLUMN TB_PROJ_ISSUE.ISSUE_DESC IS '이슈설명';
COMMENT ON COLUMN TB_PROJ_ISSUE.REPORT_EMP_ID IS '보고자ID';
COMMENT ON COLUMN TB_PROJ_ISSUE.ASSIGN_EMP_ID IS '담당자ID';
COMMENT ON COLUMN TB_PROJ_ISSUE.PRIORITY_CD IS '우선순위코드';
COMMENT ON COLUMN TB_PROJ_ISSUE.STATUS_CD IS '상태코드';
COMMENT ON COLUMN TB_PROJ_ISSUE.REPORT_DT IS '보고일자';
COMMENT ON COLUMN TB_PROJ_ISSUE.RESOLVE_DT IS '해결일자';

-- TB_ASSET
COMMENT ON COLUMN TB_ASSET.ASSET_ID IS '자산ID';
COMMENT ON COLUMN TB_ASSET.ASSET_NM IS '자산명';
COMMENT ON COLUMN TB_ASSET.ASSET_TYPE_CD IS '자산유형코드';
COMMENT ON COLUMN TB_ASSET.SERIAL_NO IS '시리얼번호';
COMMENT ON COLUMN TB_ASSET.PURCHASE_DT IS '구매일자';
COMMENT ON COLUMN TB_ASSET.PURCHASE_AMT IS '구매금액';
COMMENT ON COLUMN TB_ASSET.CURRENT_LOC IS '현재위치';
COMMENT ON COLUMN TB_ASSET.STATUS_CD IS '상태코드';
COMMENT ON COLUMN TB_ASSET.REMARK IS '비고';

-- TB_ASSET_ASSIGN
COMMENT ON COLUMN TB_ASSET_ASSIGN.ASSIGN_ID IS '배정ID';
COMMENT ON COLUMN TB_ASSET_ASSIGN.ASSET_ID IS '자산ID';
COMMENT ON COLUMN TB_ASSET_ASSIGN.EMP_ID IS '임직원ID';
COMMENT ON COLUMN TB_ASSET_ASSIGN.ASSIGN_DT IS '배정일자';
COMMENT ON COLUMN TB_ASSET_ASSIGN.RETURN_DT IS '반납일자';
COMMENT ON COLUMN TB_ASSET_ASSIGN.REMARK IS '비고';

-- TB_ASSET_MAINT
COMMENT ON COLUMN TB_ASSET_MAINT.MAINT_ID IS '유지보수ID';
COMMENT ON COLUMN TB_ASSET_MAINT.ASSET_ID IS '자산ID';
COMMENT ON COLUMN TB_ASSET_MAINT.MAINT_DT IS '유지보수일자';
COMMENT ON COLUMN TB_ASSET_MAINT.MAINT_TYPE IS '유지보수유형';
COMMENT ON COLUMN TB_ASSET_MAINT.MAINT_DESC IS '유지보수내용';
COMMENT ON COLUMN TB_ASSET_MAINT.COST_AMT IS '비용금액';
COMMENT ON COLUMN TB_ASSET_MAINT.VENDOR_NM IS '업체명';

-- TB_CONTRACT
COMMENT ON COLUMN TB_CONTRACT.CONTRACT_ID IS '계약ID';
COMMENT ON COLUMN TB_CONTRACT.CONTRACT_NM IS '계약명';
COMMENT ON COLUMN TB_CONTRACT.CONTRACT_TYPE IS '계약유형';
COMMENT ON COLUMN TB_CONTRACT.PARTNER_NM IS '거래처명';
COMMENT ON COLUMN TB_CONTRACT.CONTRACT_AMT IS '계약금액';
COMMENT ON COLUMN TB_CONTRACT.START_DT IS '시작일자';
COMMENT ON COLUMN TB_CONTRACT.END_DT IS '종료일자';
COMMENT ON COLUMN TB_CONTRACT.STATUS_CD IS '상태코드';
COMMENT ON COLUMN TB_CONTRACT.CHARGE_DEPT_CD IS '담당부서코드';
COMMENT ON COLUMN TB_CONTRACT.CHARGE_EMP_ID IS '담당자ID';

-- TB_CONTRACT_DTL
COMMENT ON COLUMN TB_CONTRACT_DTL.DTL_ID IS '상세ID';
COMMENT ON COLUMN TB_CONTRACT_DTL.CONTRACT_ID IS '계약ID';
COMMENT ON COLUMN TB_CONTRACT_DTL.ITEM_NM IS '항목명';
COMMENT ON COLUMN TB_CONTRACT_DTL.ITEM_QTY IS '항목수량';
COMMENT ON COLUMN TB_CONTRACT_DTL.UNIT_PRICE IS '단가';
COMMENT ON COLUMN TB_CONTRACT_DTL.ITEM_AMT IS '항목금액';
COMMENT ON COLUMN TB_CONTRACT_DTL.REMARK IS '비고';

-- TB_VENDOR
COMMENT ON COLUMN TB_VENDOR.VENDOR_CD IS '거래처코드';
COMMENT ON COLUMN TB_VENDOR.VENDOR_NM IS '거래처명';
COMMENT ON COLUMN TB_VENDOR.BIZ_NO IS '사업자번호';
COMMENT ON COLUMN TB_VENDOR.CEO_NM IS '대표자명';
COMMENT ON COLUMN TB_VENDOR.ADDRESS IS '주소';
COMMENT ON COLUMN TB_VENDOR.PHONE_NO IS '전화번호';
COMMENT ON COLUMN TB_VENDOR.EMAIL IS '이메일';
COMMENT ON COLUMN TB_VENDOR.VENDOR_TYPE IS '거래처유형';
COMMENT ON COLUMN TB_VENDOR.USE_YN IS '사용여부';

-- TB_BUDGET
COMMENT ON COLUMN TB_BUDGET.BUDGET_ID IS '예산ID';
COMMENT ON COLUMN TB_BUDGET.BUDGET_YEAR IS '예산연도';
COMMENT ON COLUMN TB_BUDGET.DEPT_CD IS '부서코드';
COMMENT ON COLUMN TB_BUDGET.BUDGET_TYPE IS '예산유형';
COMMENT ON COLUMN TB_BUDGET.BUDGET_AMT IS '예산금액';
COMMENT ON COLUMN TB_BUDGET.EXEC_AMT IS '집행금액';
COMMENT ON COLUMN TB_BUDGET.REMAIN_AMT IS '잔여금액';
COMMENT ON COLUMN TB_BUDGET.STATUS_CD IS '상태코드';

-- TB_EXPENSE
COMMENT ON COLUMN TB_EXPENSE.EXPENSE_ID IS '경비ID';
COMMENT ON COLUMN TB_EXPENSE.EMP_ID IS '임직원ID';
COMMENT ON COLUMN TB_EXPENSE.EXPENSE_DT IS '경비일자';
COMMENT ON COLUMN TB_EXPENSE.EXPENSE_TYPE IS '경비유형';
COMMENT ON COLUMN TB_EXPENSE.EXPENSE_AMT IS '경비금액';
COMMENT ON COLUMN TB_EXPENSE.APPROVAL_STATUS IS '승인상태';
COMMENT ON COLUMN TB_EXPENSE.APPROVAL_DT IS '승인일자';
COMMENT ON COLUMN TB_EXPENSE.REMARK IS '비고';

-- TB_EXPENSE_DTL
COMMENT ON COLUMN TB_EXPENSE_DTL.DTL_ID IS '상세ID';
COMMENT ON COLUMN TB_EXPENSE_DTL.EXPENSE_ID IS '경비ID';
COMMENT ON COLUMN TB_EXPENSE_DTL.ITEM_NM IS '항목명';
COMMENT ON COLUMN TB_EXPENSE_DTL.ITEM_AMT IS '항목금액';
COMMENT ON COLUMN TB_EXPENSE_DTL.RECEIPT_YN IS '영수증여부';

-- TB_INVOICE
COMMENT ON COLUMN TB_INVOICE.INVOICE_ID IS '세금계산서ID';
COMMENT ON COLUMN TB_INVOICE.CONTRACT_ID IS '계약ID';
COMMENT ON COLUMN TB_INVOICE.VENDOR_CD IS '거래처코드';
COMMENT ON COLUMN TB_INVOICE.INVOICE_DT IS '발행일자';
COMMENT ON COLUMN TB_INVOICE.INVOICE_AMT IS '공급가액';
COMMENT ON COLUMN TB_INVOICE.TAX_AMT IS '세액';
COMMENT ON COLUMN TB_INVOICE.TOTAL_AMT IS '합계금액';
COMMENT ON COLUMN TB_INVOICE.PAY_DUE_DT IS '지급기한일자';
COMMENT ON COLUMN TB_INVOICE.PAY_STATUS IS '지급상태';

-- TB_EDUCATION
COMMENT ON COLUMN TB_EDUCATION.EDU_ID IS '교육ID';
COMMENT ON COLUMN TB_EDUCATION.EDU_NM IS '교육명';
COMMENT ON COLUMN TB_EDUCATION.EDU_TYPE IS '교육유형';
COMMENT ON COLUMN TB_EDUCATION.EDU_DESC IS '교육설명';
COMMENT ON COLUMN TB_EDUCATION.START_DT IS '시작일자';
COMMENT ON COLUMN TB_EDUCATION.END_DT IS '종료일자';
COMMENT ON COLUMN TB_EDUCATION.LOCATION IS '장소';
COMMENT ON COLUMN TB_EDUCATION.INSTRUCTOR IS '강사';
COMMENT ON COLUMN TB_EDUCATION.MAX_PERSON IS '최대인원';

-- TB_EDU_REGISTER
COMMENT ON COLUMN TB_EDU_REGISTER.REG_ID IS '수강ID';
COMMENT ON COLUMN TB_EDU_REGISTER.EDU_ID IS '교육ID';
COMMENT ON COLUMN TB_EDU_REGISTER.EMP_ID IS '임직원ID';
COMMENT ON COLUMN TB_EDU_REGISTER.REG_DT IS '수강일자';
COMMENT ON COLUMN TB_EDU_REGISTER.STATUS_CD IS '상태코드';
COMMENT ON COLUMN TB_EDU_REGISTER.SCORE IS '점수';
COMMENT ON COLUMN TB_EDU_REGISTER.REMARK IS '비고';

-- TB_CERTIFICATION
COMMENT ON COLUMN TB_CERTIFICATION.CERT_ID IS '자격증ID';
COMMENT ON COLUMN TB_CERTIFICATION.EMP_ID IS '임직원ID';
COMMENT ON COLUMN TB_CERTIFICATION.CERT_NM IS '자격증명';
COMMENT ON COLUMN TB_CERTIFICATION.CERT_NO IS '자격증번호';
COMMENT ON COLUMN TB_CERTIFICATION.ISSUE_ORG IS '발급기관';
COMMENT ON COLUMN TB_CERTIFICATION.ISSUE_DT IS '발급일자';
COMMENT ON COLUMN TB_CERTIFICATION.EXPIRE_DT IS '만료일자';

-- TB_CUSTOMER
COMMENT ON COLUMN TB_CUSTOMER.CUST_ID IS '고객ID';
COMMENT ON COLUMN TB_CUSTOMER.CUST_NM IS '고객명';
COMMENT ON COLUMN TB_CUSTOMER.CUST_TYPE IS '고객유형';
COMMENT ON COLUMN TB_CUSTOMER.BIZ_NO IS '사업자번호';
COMMENT ON COLUMN TB_CUSTOMER.CEO_NM IS '대표자명';
COMMENT ON COLUMN TB_CUSTOMER.ADDRESS IS '주소';
COMMENT ON COLUMN TB_CUSTOMER.PHONE_NO IS '전화번호';
COMMENT ON COLUMN TB_CUSTOMER.EMAIL IS '이메일';
COMMENT ON COLUMN TB_CUSTOMER.GRADE_CD IS '등급코드';
COMMENT ON COLUMN TB_CUSTOMER.REG_DT IS '등록일자';

-- TB_CUST_CONTACT
COMMENT ON COLUMN TB_CUST_CONTACT.CONTACT_ID IS '담당자ID';
COMMENT ON COLUMN TB_CUST_CONTACT.CUST_ID IS '고객ID';
COMMENT ON COLUMN TB_CUST_CONTACT.CONTACT_NM IS '담당자명';
COMMENT ON COLUMN TB_CUST_CONTACT.POSITION IS '직책';
COMMENT ON COLUMN TB_CUST_CONTACT.PHONE_NO IS '전화번호';
COMMENT ON COLUMN TB_CUST_CONTACT.EMAIL IS '이메일';
COMMENT ON COLUMN TB_CUST_CONTACT.MAIN_YN IS '대표여부';

-- TB_CUST_HISTORY
COMMENT ON COLUMN TB_CUST_HISTORY.HIST_ID IS '이력ID';
COMMENT ON COLUMN TB_CUST_HISTORY.CUST_ID IS '고객ID';
COMMENT ON COLUMN TB_CUST_HISTORY.HIST_DT IS '이력일자';
COMMENT ON COLUMN TB_CUST_HISTORY.HIST_TYPE IS '이력유형';
COMMENT ON COLUMN TB_CUST_HISTORY.HIST_DESC IS '이력내용';
COMMENT ON COLUMN TB_CUST_HISTORY.CHARGE_EMP_ID IS '담당자ID';

-- TB_ORDER
COMMENT ON COLUMN TB_ORDER.ORDER_ID IS '주문ID';
COMMENT ON COLUMN TB_ORDER.CUST_ID IS '고객ID';
COMMENT ON COLUMN TB_ORDER.ORDER_DT IS '주문일자';
COMMENT ON COLUMN TB_ORDER.ORDER_TYPE IS '주문유형';
COMMENT ON COLUMN TB_ORDER.TOTAL_AMT IS '총금액';
COMMENT ON COLUMN TB_ORDER.DISCOUNT_AMT IS '할인금액';
COMMENT ON COLUMN TB_ORDER.NET_AMT IS '순금액';
COMMENT ON COLUMN TB_ORDER.STATUS_CD IS '상태코드';
COMMENT ON COLUMN TB_ORDER.DELIVERY_DT IS '배송일자';
COMMENT ON COLUMN TB_ORDER.CHARGE_EMP_ID IS '담당자ID';

-- TB_ORDER_DTL
COMMENT ON COLUMN TB_ORDER_DTL.DTL_ID IS '상세ID';
COMMENT ON COLUMN TB_ORDER_DTL.ORDER_ID IS '주문ID';
COMMENT ON COLUMN TB_ORDER_DTL.PRODUCT_CD IS '상품코드';
COMMENT ON COLUMN TB_ORDER_DTL.PRODUCT_NM IS '상품명';
COMMENT ON COLUMN TB_ORDER_DTL.QTY IS '수량';
COMMENT ON COLUMN TB_ORDER_DTL.UNIT_PRICE IS '단가';
COMMENT ON COLUMN TB_ORDER_DTL.ITEM_AMT IS '항목금액';
COMMENT ON COLUMN TB_ORDER_DTL.REMARK IS '비고';

-- TB_PRODUCT
COMMENT ON COLUMN TB_PRODUCT.PRODUCT_CD IS '상품코드';
COMMENT ON COLUMN TB_PRODUCT.PRODUCT_NM IS '상품명';
COMMENT ON COLUMN TB_PRODUCT.PRODUCT_TYPE IS '상품유형';
COMMENT ON COLUMN TB_PRODUCT.CATEGORY_CD IS '분류코드';
COMMENT ON COLUMN TB_PRODUCT.UNIT_PRICE IS '단가';
COMMENT ON COLUMN TB_PRODUCT.STOCK_QTY IS '재고수량';
COMMENT ON COLUMN TB_PRODUCT.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_PRODUCT.REMARK IS '비고';

-- TB_PRODUCT_CATEGORY
COMMENT ON COLUMN TB_PRODUCT_CATEGORY.CATEGORY_CD IS '분류코드';
COMMENT ON COLUMN TB_PRODUCT_CATEGORY.CATEGORY_NM IS '분류명';
COMMENT ON COLUMN TB_PRODUCT_CATEGORY.UPPER_CATEGORY_CD IS '상위분류코드';
COMMENT ON COLUMN TB_PRODUCT_CATEGORY.CATEGORY_LVL IS '분류레벨';
COMMENT ON COLUMN TB_PRODUCT_CATEGORY.SORT_ORD IS '정렬순서';

-- TB_COMMON_CODE
COMMENT ON COLUMN TB_COMMON_CODE.CODE_GRP IS '코드그룹';
COMMENT ON COLUMN TB_COMMON_CODE.CODE_CD IS '코드';
COMMENT ON COLUMN TB_COMMON_CODE.CODE_NM IS '코드명';
COMMENT ON COLUMN TB_COMMON_CODE.CODE_DESC IS '코드설명';
COMMENT ON COLUMN TB_COMMON_CODE.SORT_ORD IS '정렬순서';
COMMENT ON COLUMN TB_COMMON_CODE.USE_YN IS '사용여부';

-- TB_MENU
COMMENT ON COLUMN TB_MENU.MENU_ID IS '메뉴ID';
COMMENT ON COLUMN TB_MENU.MENU_NM IS '메뉴명';
COMMENT ON COLUMN TB_MENU.UPPER_MENU_ID IS '상위메뉴ID';
COMMENT ON COLUMN TB_MENU.MENU_URL IS '메뉴URL';
COMMENT ON COLUMN TB_MENU.MENU_LVL IS '메뉴레벨';
COMMENT ON COLUMN TB_MENU.SORT_ORD IS '정렬순서';
COMMENT ON COLUMN TB_MENU.ICON IS '아이콘';
COMMENT ON COLUMN TB_MENU.USE_YN IS '사용여부';

-- TB_ROLE
COMMENT ON COLUMN TB_ROLE.ROLE_CD IS '역할코드';
COMMENT ON COLUMN TB_ROLE.ROLE_NM IS '역할명';
COMMENT ON COLUMN TB_ROLE.ROLE_DESC IS '역할설명';
COMMENT ON COLUMN TB_ROLE.USE_YN IS '사용여부';

-- TB_USER_ROLE
COMMENT ON COLUMN TB_USER_ROLE.USER_ID IS '사용자ID';
COMMENT ON COLUMN TB_USER_ROLE.ROLE_CD IS '역할코드';
COMMENT ON COLUMN TB_USER_ROLE.ASSIGN_DT IS '배정일자';

-- TB_ROLE_MENU
COMMENT ON COLUMN TB_ROLE_MENU.ROLE_CD IS '역할코드';
COMMENT ON COLUMN TB_ROLE_MENU.MENU_ID IS '메뉴ID';
COMMENT ON COLUMN TB_ROLE_MENU.READ_YN IS '읽기여부';
COMMENT ON COLUMN TB_ROLE_MENU.WRITE_YN IS '쓰기여부';

-- TB_AUDIT_LOG
COMMENT ON COLUMN TB_AUDIT_LOG.LOG_ID IS '로그ID';
COMMENT ON COLUMN TB_AUDIT_LOG.USER_ID IS '사용자ID';
COMMENT ON COLUMN TB_AUDIT_LOG.ACTION_TYPE IS '행위유형';
COMMENT ON COLUMN TB_AUDIT_LOG.TARGET_TABLE IS '대상테이블';
COMMENT ON COLUMN TB_AUDIT_LOG.TARGET_ID IS '대상ID';
COMMENT ON COLUMN TB_AUDIT_LOG.ACTION_DESC IS '행위설명';
COMMENT ON COLUMN TB_AUDIT_LOG.ACTION_DT IS '행위일시';
COMMENT ON COLUMN TB_AUDIT_LOG.IP_ADDR IS 'IP주소';

-- TB_NOTIFICATION
COMMENT ON COLUMN TB_NOTIFICATION.NOTI_ID IS '알림ID';
COMMENT ON COLUMN TB_NOTIFICATION.USER_ID IS '사용자ID';
COMMENT ON COLUMN TB_NOTIFICATION.NOTI_TYPE IS '알림유형';
COMMENT ON COLUMN TB_NOTIFICATION.NOTI_TITLE IS '알림제목';
COMMENT ON COLUMN TB_NOTIFICATION.NOTI_CONTENT IS '알림내용';
COMMENT ON COLUMN TB_NOTIFICATION.READ_YN IS '읽음여부';
COMMENT ON COLUMN TB_NOTIFICATION.CRET_DT IS '생성일시';

-- TB_FILE_STORAGE
COMMENT ON COLUMN TB_FILE_STORAGE.FILE_ID IS '파일ID';
COMMENT ON COLUMN TB_FILE_STORAGE.FILE_NM IS '파일명';
COMMENT ON COLUMN TB_FILE_STORAGE.FILE_PATH IS '파일경로';
COMMENT ON COLUMN TB_FILE_STORAGE.FILE_SIZE IS '파일크기';
COMMENT ON COLUMN TB_FILE_STORAGE.FILE_TYPE IS '파일유형';
COMMENT ON COLUMN TB_FILE_STORAGE.REF_TABLE IS '참조테이블';
COMMENT ON COLUMN TB_FILE_STORAGE.REF_ID IS '참조ID';
COMMENT ON COLUMN TB_FILE_STORAGE.CRET_USER_ID IS '생성자ID';
COMMENT ON COLUMN TB_FILE_STORAGE.CRET_DT IS '생성일시';

-- TB_BATCH_JOB
COMMENT ON COLUMN TB_BATCH_JOB.JOB_ID IS '작업ID';
COMMENT ON COLUMN TB_BATCH_JOB.JOB_NM IS '작업명';
COMMENT ON COLUMN TB_BATCH_JOB.JOB_TYPE IS '작업유형';
COMMENT ON COLUMN TB_BATCH_JOB.CRON_EXPR IS 'CRON표현식';
COMMENT ON COLUMN TB_BATCH_JOB.LAST_EXEC_DT IS '최종실행일시';
COMMENT ON COLUMN TB_BATCH_JOB.NEXT_EXEC_DT IS '다음실행일시';
COMMENT ON COLUMN TB_BATCH_JOB.STATUS_CD IS '상태코드';
COMMENT ON COLUMN TB_BATCH_JOB.REMARK IS '비고';

-- TB_BATCH_LOG
COMMENT ON COLUMN TB_BATCH_LOG.LOG_ID IS '로그ID';
COMMENT ON COLUMN TB_BATCH_LOG.JOB_ID IS '작업ID';
COMMENT ON COLUMN TB_BATCH_LOG.START_DT IS '시작일시';
COMMENT ON COLUMN TB_BATCH_LOG.END_DT IS '종료일시';
COMMENT ON COLUMN TB_BATCH_LOG.STATUS_CD IS '상태코드';
COMMENT ON COLUMN TB_BATCH_LOG.PROCESS_CNT IS '처리건수';
COMMENT ON COLUMN TB_BATCH_LOG.ERROR_MSG IS '오류메시지';

-- TB_SYSTEM_CONFIG
COMMENT ON COLUMN TB_SYSTEM_CONFIG.CONFIG_KEY IS '설정키';
COMMENT ON COLUMN TB_SYSTEM_CONFIG.CONFIG_VAL IS '설정값';
COMMENT ON COLUMN TB_SYSTEM_CONFIG.CONFIG_DESC IS '설정설명';
COMMENT ON COLUMN TB_SYSTEM_CONFIG.UPDT_DT IS '수정일시';
COMMENT ON COLUMN TB_SYSTEM_CONFIG.UPDT_USER_ID IS '수정자ID';

-- TB_LEAVE_REQUEST
COMMENT ON COLUMN TB_LEAVE_REQUEST.REQ_ID IS '신청ID';
COMMENT ON COLUMN TB_LEAVE_REQUEST.EMP_ID IS '임직원ID';
COMMENT ON COLUMN TB_LEAVE_REQUEST.LEAVE_TYPE IS '휴가유형';
COMMENT ON COLUMN TB_LEAVE_REQUEST.START_DT IS '시작일자';
COMMENT ON COLUMN TB_LEAVE_REQUEST.END_DT IS '종료일자';
COMMENT ON COLUMN TB_LEAVE_REQUEST.DAYS IS '일수';
COMMENT ON COLUMN TB_LEAVE_REQUEST.STATUS_CD IS '상태코드';
COMMENT ON COLUMN TB_LEAVE_REQUEST.APPROVE_EMP_ID IS '승인자ID';
COMMENT ON COLUMN TB_LEAVE_REQUEST.REMARK IS '비고';

-- TB_MEETING_ROOM
COMMENT ON COLUMN TB_MEETING_ROOM.ROOM_CD IS '회의실코드';
COMMENT ON COLUMN TB_MEETING_ROOM.ROOM_NM IS '회의실명';
COMMENT ON COLUMN TB_MEETING_ROOM.LOCATION IS '위치';
COMMENT ON COLUMN TB_MEETING_ROOM.CAPACITY IS '수용인원';
COMMENT ON COLUMN TB_MEETING_ROOM.USE_YN IS '사용여부';

-- TB_MEETING_RESERVE
COMMENT ON COLUMN TB_MEETING_RESERVE.RESERVE_ID IS '예약ID';
COMMENT ON COLUMN TB_MEETING_RESERVE.ROOM_CD IS '회의실코드';
COMMENT ON COLUMN TB_MEETING_RESERVE.RESERVE_DT IS '예약일자';
COMMENT ON COLUMN TB_MEETING_RESERVE.START_TIME IS '시작시간';
COMMENT ON COLUMN TB_MEETING_RESERVE.END_TIME IS '종료시간';
COMMENT ON COLUMN TB_MEETING_RESERVE.EMP_ID IS '임직원ID';
COMMENT ON COLUMN TB_MEETING_RESERVE.TITLE IS '제목';
COMMENT ON COLUMN TB_MEETING_RESERVE.REMARK IS '비고';
