-- SALES_APP 스키마 테이블/컬럼 코멘트 재적재
-- NLS_LANG=AMERICAN_AMERICA.AL32UTF8 환경에서 SYS로 실행할 것

-- ====================
-- TB_CUST (고객)
-- ====================
COMMENT ON TABLE SALES_APP.TB_CUST IS '고객';
COMMENT ON COLUMN SALES_APP.TB_CUST.CUST_NO   IS '고객번호';
COMMENT ON COLUMN SALES_APP.TB_CUST.CUST_NM   IS '고객명';
COMMENT ON COLUMN SALES_APP.TB_CUST.CUST_ADDR IS '고객주소';
COMMENT ON COLUMN SALES_APP.TB_CUST.CUST_EML  IS '고객이메일';
COMMENT ON COLUMN SALES_APP.TB_CUST.GNDR_CD   IS '성별코드';
COMMENT ON COLUMN SALES_APP.TB_CUST.BRDT      IS '생년월일';
COMMENT ON COLUMN SALES_APP.TB_CUST.REG_DT    IS '등록일시';
COMMENT ON COLUMN SALES_APP.TB_CUST.MDFCN_DT  IS '수정일시';

-- ====================
-- TB_ORDR (주문)
-- ====================
COMMENT ON TABLE SALES_APP.TB_ORDR IS '주문';
COMMENT ON COLUMN SALES_APP.TB_ORDR.ORDR_NO   IS '주문번호';
COMMENT ON COLUMN SALES_APP.TB_ORDR.CUST_NO   IS '고객번호';
COMMENT ON COLUMN SALES_APP.TB_ORDR.ORDR_YMD  IS '주문일자';
COMMENT ON COLUMN SALES_APP.TB_ORDR.ORDR_AMT  IS '주문금액';
COMMENT ON COLUMN SALES_APP.TB_ORDR.DSCNT_AMT IS '할인금액';
COMMENT ON COLUMN SALES_APP.TB_ORDR.STTS_CD   IS '상태코드';
COMMENT ON COLUMN SALES_APP.TB_ORDR.REG_DT    IS '등록일시';

-- ====================
-- TB_GDS (상품) - 비표준 컬럼 포함
-- ====================
COMMENT ON TABLE SALES_APP.TB_GDS IS '상품';
COMMENT ON COLUMN SALES_APP.TB_GDS.GOODS_ID   IS '상품아이디';
COMMENT ON COLUMN SALES_APP.TB_GDS.GOODS_NAME IS '상품이름';
COMMENT ON COLUMN SALES_APP.TB_GDS.PRICE      IS '가격';
COMMENT ON COLUMN SALES_APP.TB_GDS.QTY        IS '수량';
COMMENT ON COLUMN SALES_APP.TB_GDS.REG_DATE   IS '등록일자';

-- ====================
-- TB_STLM (결제)
-- ====================
COMMENT ON TABLE SALES_APP.TB_STLM IS '결제';
COMMENT ON COLUMN SALES_APP.TB_STLM.STLM_NO   IS '결제번호';
COMMENT ON COLUMN SALES_APP.TB_STLM.ORDR_NO   IS '주문번호';
COMMENT ON COLUMN SALES_APP.TB_STLM.CARD_NO   IS '카드번호';
COMMENT ON COLUMN SALES_APP.TB_STLM.STLM_AMT  IS '결제금액';
COMMENT ON COLUMN SALES_APP.TB_STLM.STLM_DT   IS '결제일시';
COMMENT ON COLUMN SALES_APP.TB_STLM.DSCNT_AMT IS '할인금액';
COMMENT ON COLUMN SALES_APP.TB_STLM.RFND_YN   IS '환불여부';

-- ====================
-- TB_CPN (쿠폰) - 비표준 컬럼 포함
-- ====================
COMMENT ON TABLE SALES_APP.TB_CPN IS '쿠폰';
COMMENT ON COLUMN SALES_APP.TB_CPN.CPN_NO     IS '쿠폰번호';
COMMENT ON COLUMN SALES_APP.TB_CPN.CPN_NM     IS '쿠폰명';
COMMENT ON COLUMN SALES_APP.TB_CPN.DSCNT_RATE IS '할인율';
COMMENT ON COLUMN SALES_APP.TB_CPN.START_DATE IS '시작일자';
COMMENT ON COLUMN SALES_APP.TB_CPN.END_DATE   IS '종료일자';
COMMENT ON COLUMN SALES_APP.TB_CPN.USE_YN     IS '사용여부';

COMMIT;
EXIT;
